// Mobile App pen-testing — senior-level PT questions.
// Authority sources: OWASP MASVS, OWASP MASTG, OWASP Mobile Top 10, Android/iOS official developer docs.

window.QUESTION_BANK.mobile = [
  {
    id: 'mob-001',
    topic: 'mobile',
    subtopic: 'ssl-pinning',
    difficulty: 'senior',
    question: 'You install your Burp CA into the Android device but the app still rejects HTTPS connections. The app uses certificate pinning. Which of the following is the most direct, scriptable bypass on a rooted device?',
    choices: [
      'Re-package the APK without HTTPS support',
      'Use Frida or Objection to hook the pinning verification function in OkHttp / TrustManager and force it to return success at runtime',
      'Disable IPv6 on the device',
      'Switch the device into airplane mode',
    ],
    correctIndex: 1,
    explanation: 'On a rooted device, runtime instrumentation with Frida (or its Objection wrapper) can replace the pinning check in common libraries (OkHttp CertificatePinner, X509TrustManager, network_security_config) so pinning fails open. OWASP MASTG\'s Android testing chapter walks through this exact technique.',
    distractorRationale: {
      0: 'Re-packaging without HTTPS would just break the app and prove nothing about the pinning protection.',
      2: 'IPv6 has nothing to do with TLS certificate validation.',
      3: 'Airplane mode prevents traffic entirely, which is the opposite of what is needed for testing.',
    },
    source: { name: 'OWASP MASTG — Android Network APIs (Testing Network Communication)', url: 'https://mas.owasp.org/MASTG/0x05g-Testing-Network-Communication/' },
  },

  {
    id: 'mob-002',
    topic: 'mobile',
    subtopic: 'storage',
    difficulty: 'senior',
    question: 'On Android, where is the OWASP-recommended location for sensitive secrets (e.g., refresh tokens) so they are protected by hardware-backed keys when available?',
    choices: [
      'In SharedPreferences with `MODE_PRIVATE`',
      'In the Android Keystore (using KeyStore-generated keys with `setUserAuthenticationRequired` and StrongBox where supported), encrypting the secret before persisting it',
      'In a file under /sdcard with chmod 600',
      'In the app\'s SQLite database with Base64 encoding',
    ],
    correctIndex: 1,
    explanation: 'The Android Keystore stores keys in a hardware-backed Trusted Execution Environment / StrongBox where available, so the key material itself never leaves secure storage. OWASP MASVS-STORAGE controls and the Android developer documentation both direct sensitive data through Keystore-backed encryption, not application-level storage.',
    distractorRationale: {
      0: 'MODE_PRIVATE only restricts file permissions; on a rooted device or with backup misconfig the data is still readable in plaintext.',
      2: 'External storage (/sdcard) is world-readable on older Android and chmod metadata is unreliable across vendors.',
      3: 'Base64 is encoding, not encryption — a trivial reversible transformation.',
    },
    source: { name: 'Android Developers — Android Keystore system', url: 'https://developer.android.com/privacy-and-security/keystore' },
  },

  {
    id: 'mob-003',
    topic: 'mobile',
    subtopic: 'ios-keychain',
    difficulty: 'senior',
    question: 'You find an iOS app storing a session token in `UserDefaults`. Why is the senior-level finding to recommend moving it to the iOS Keychain instead?',
    choices: [
      'Keychain values are exposed by default in iTunes backups while UserDefaults are not',
      'UserDefaults is stored in a plist that is included in unencrypted iTunes/Finder backups by default and is readable from a jailbroken device, while the Keychain offers per-item access-control flags (e.g., `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`) and is not in unencrypted backups',
      'UserDefaults requires more memory than the Keychain',
      'Keychain values are stored on Apple\'s servers',
    ],
    correctIndex: 1,
    explanation: 'UserDefaults persists to a plist inside the app sandbox. That plist is included in unencrypted iCloud/iTunes backups and readable on jailbroken devices. The Keychain provides Secure Enclave-backed per-item access-control attributes that bind unlock to passcode/biometrics and exclude items from unencrypted backups. OWASP MASTG iOS chapter is explicit about this.',
    distractorRationale: {
      0: 'This reverses the truth — UserDefaults are exposed in backups, Keychain items are not (when configured correctly).',
      2: 'Memory usage is irrelevant to either choice.',
      3: 'Keychain stores items locally (with optional iCloud Keychain sync if explicitly enabled), not on Apple\'s servers by default.',
    },
    source: { name: 'OWASP MASTG — iOS Data Storage', url: 'https://mas.owasp.org/MASTG/0x06d-Testing-Data-Storage/' },
  },

  {
    id: 'mob-004',
    topic: 'mobile',
    subtopic: 'deeplinks',
    difficulty: 'senior',
    question: 'An Android app declares an intent-filter with `android:exported="true"` and accepts arbitrary URI parameters that are passed straight into a WebView\'s `loadUrl()`. Which class of vulnerability does this most directly enable?',
    choices: [
      'Local file inclusion via SharedPreferences',
      'Universal cross-site scripting / arbitrary URL loading via deep-link redirection (open redirect inside the app), potentially leading to credential theft if the WebView shares cookies with the user session',
      'Buffer overflow in the Java runtime',
      'SQL injection in the Play Store',
    ],
    correctIndex: 1,
    explanation: 'An exported activity that loads attacker-controlled URLs into a WebView is the canonical "deep-link / intent redirection" issue: any other app or browser can launch the activity with an attacker URL, leading to phishing, token theft (because the WebView shares cookies and may have JavaScript bridges) and CSRF-like flows. OWASP Mobile Top 10 (M8 Security Misconfiguration) and MASTG cover this.',
    distractorRationale: {
      0: 'SharedPreferences is unrelated to intent handling.',
      2: 'Buffer overflows are not the relevant class for managed-runtime WebView misuse.',
      3: 'There is no Play Store SQLi at play here; the issue is in-app intent handling.',
    },
    source: { name: 'OWASP MASTG — Android Platform APIs (Intent / Deep Link Handling)', url: 'https://mas.owasp.org/MASTG/0x05h-Testing-Platform-Interaction/' },
  },

  {
    id: 'mob-005',
    topic: 'mobile',
    subtopic: 'root-detection',
    difficulty: 'senior',
    question: 'A banking app refuses to start on a rooted device. From a senior pentester perspective, which framing is most accurate?',
    choices: [
      'Root detection is a robust, primary security control and should always be relied on',
      'Root detection is a defense-in-depth resilience control — it raises the bar but is bypassable with Frida/Magisk Hide/Zygisk and must NOT be the primary defence for sensitive data; the underlying secrets must still be protected by Keystore/Secure Enclave and TLS pinning',
      'Root detection prevents reverse engineering of the APK',
      'Root detection is enforced by Google Play Protect, not the app',
    ],
    correctIndex: 1,
    explanation: 'OWASP MASVS-RESILIENCE classifies anti-tampering, anti-debug and root/jailbreak detection as defence-in-depth — they slow attackers but are not primary controls because runtime instrumentation can defeat them. The senior-level point is that secrets must be protected at the storage and transport layers regardless of runtime resilience.',
    distractorRationale: {
      0: 'Calling root detection a "primary control" is a junior-level misconception; MASVS explicitly places it under resilience.',
      2: 'Reverse engineering of a static APK is unrelated to whether the device is rooted.',
      3: 'Play Protect is a different mechanism (app-store and on-device scanning); it does not implement the in-app root check.',
    },
    source: { name: 'OWASP MASVS — Resilience requirements (MASVS-RESILIENCE)', url: 'https://mas.owasp.org/MASVS/12-MASVS-RESILIENCE/' },
  },

  {
    id: 'mob-006',
    topic: 'mobile',
    subtopic: 'masvs',
    difficulty: 'senior',
    question: 'Which OWASP MASVS control category covers requirements such as "the app does not store sensitive data outside the app container" and "the keyboard cache is not used for sensitive input"?',
    choices: [
      'MASVS-NETWORK',
      'MASVS-STORAGE',
      'MASVS-CRYPTO',
      'MASVS-RESILIENCE',
    ],
    correctIndex: 1,
    explanation: 'MASVS-STORAGE collects controls about how, where, and whether sensitive data is persisted on the device — including keyboard cache, screenshots, app container scope, and clipboard exposure. The official MASVS site lists each category and its controls.',
    distractorRationale: {
      0: 'MASVS-NETWORK covers TLS configuration, pinning and traffic confidentiality.',
      2: 'MASVS-CRYPTO covers correct use of cryptographic primitives, key generation and key management.',
      3: 'MASVS-RESILIENCE covers anti-tampering and anti-instrumentation.',
    },
    source: { name: 'OWASP MASVS — Storage requirements (MASVS-STORAGE)', url: 'https://mas.owasp.org/MASVS/08-MASVS-STORAGE/' },
  },

  {
    id: 'mob-007',
    topic: 'mobile',
    subtopic: 'frida-objection',
    difficulty: 'senior',
    question: 'How does Objection relate to Frida, and which is the right tool when?',
    choices: [
      'Objection is a runtime mobile-exploration toolkit built ON TOP OF Frida — it provides a CLI with pre-canned scripts (SSL pinning bypass, root-detection bypass, dump keychain). Use Frida directly when you need to write custom hooks; use Objection when a common task already has a built-in command',
      'They are competing products with no relation',
      'Frida is for Android only; Objection for iOS only',
      'Objection replaces Frida entirely',
    ],
    correctIndex: 0,
    explanation: 'Objection wraps Frida\'s instrumentation API into a workflow-friendly CLI for common pentest tasks. The Frida and Objection docs say so explicitly. Senior testers know when to drop into Frida\'s JS API for a custom hook vs leveraging an Objection one-liner.',
    distractorRationale: {
      1: 'They are explicitly related; Objection requires Frida.',
      2: 'Both work on Android and iOS.',
      3: 'Objection does not replace Frida — it depends on it.',
    },
    source: { name: 'OWASP MASTG — Tools (Frida, Objection)', url: 'https://mas.owasp.org/MASTG/0x08a-Testing-Tools/' },
  },

  {
    id: 'mob-008',
    topic: 'mobile',
    subtopic: 'apk-rev',
    difficulty: 'senior',
    question: 'You want to inspect an Android APK\'s code and resources statically. Which tool combination is canonical for senior mobile reversing?',
    choices: [
      'apktool (decode resources / smali) and jadx (decompile DEX to readable Java), plus baksmali/smali if you need to patch and rebuild',
      'Wireshark + Burp',
      'Mimikatz + BloodHound',
      'Nessus + Nikto',
    ],
    correctIndex: 0,
    explanation: 'apktool unpacks the APK into smali and resources you can inspect/patch and rebuild. jadx decompiles DEX bytecode into readable Java with a useful UI for navigation. Together they cover most of static APK reverse engineering. OWASP MASTG recommends both as primary tools.',
    distractorRationale: {
      1: 'Network capture/proxy tools are for traffic, not APK analysis.',
      2: 'AD-attack tools are unrelated.',
      3: 'Network vulnerability scanners are unrelated.',
    },
    source: { name: 'OWASP MASTG — Android Static Analysis (Tools)', url: 'https://mas.owasp.org/MASTG/0x05a-Tampering-and-Reverse-Engineering-Android/' },
  },

  {
    id: 'mob-009',
    topic: 'mobile',
    subtopic: 'webview-bridge',
    difficulty: 'senior',
    question: 'An Android app exposes a Java method to JavaScript via `WebView.addJavascriptInterface`. The WebView loads partially attacker-influenced URLs. Why is this a critical finding pre-API-17 and still a senior-level review item afterwards?',
    choices: [
      'Pre-API-17 (Android 4.2), addJavascriptInterface exposed Reflection so JS could load any class and execute arbitrary code on the device. From API-17 onward, only @JavascriptInterface-annotated methods are exposed; the senior risk is that those methods themselves can leak sensitive functionality (exfiltrate tokens, trigger payments) to compromised content.',
      'It blocks all JavaScript in the WebView',
      'It enforces Content Security Policy',
      'It encrypts the WebView traffic with TPM',
    ],
    correctIndex: 0,
    explanation: 'The pre-Android-4.2 reflection bug enabled trivial RCE. After the fix, the API still exposes only annotated methods, but the senior risk is that those methods are often "trusted bridges" that perform sensitive actions and can be abused if the WebView is fed attacker content. OWASP MASTG covers both eras.',
    distractorRationale: {
      1: 'It enables JS-to-Java interop, not blocks it.',
      2: 'CSP is HTTP-header enforced; this API does not enforce it.',
      3: 'There is no TPM-level encryption tied to this API.',
    },
    source: { name: 'OWASP MASTG — Android WebViews', url: 'https://mas.owasp.org/MASTG/0x05h-Testing-Platform-Interaction/' },
  },

  {
    id: 'mob-010',
    topic: 'mobile',
    subtopic: 'logcat',
    difficulty: 'senior',
    question: 'On Android API < 24, why was sensitive data logged via `Log.d` a serious finding, and what changed in modern Android?',
    choices: [
      'Pre-API-24, any app with `READ_LOGS` could read every other app\'s log output. Since API-24, logcat is restricted per-app, but the finding remains relevant on rooted devices or when the app exposes logs via debug builds — sensitive data should never be logged regardless',
      'logcat encrypts data with the device passcode',
      'logcat is unique to iOS',
      'logcat only stores network packets',
    ],
    correctIndex: 0,
    explanation: 'Older Android exposed logcat globally to apps holding READ_LOGS, leaking tokens that developers logged for debugging. Modern Android isolates logs per app, but rooted devices and accidentally enabled debug builds re-expose them. OWASP MASTG\'s storage chapter calls this out.',
    distractorRationale: {
      1: 'logcat output is not encrypted.',
      2: 'logcat is Android-specific.',
      3: 'It logs all messages, not just packets.',
    },
    source: { name: 'OWASP MASTG — Android Data Storage (logging)', url: 'https://mas.owasp.org/MASTG/0x05d-Testing-Data-Storage/' },
  },

  {
    id: 'mob-011',
    topic: 'mobile',
    subtopic: 'exported-components',
    difficulty: 'senior',
    question: 'In an Android Manifest you find an Activity with `android:exported="true"` and no `permission`. What is the senior-level finding rationale?',
    choices: [
      'Any other app on the device can launch this Activity and pass arbitrary intents/extras to it. If the Activity performs privileged actions (financial, IPC bridges), this is exploitable cross-app. Recommendation: set `exported="false"` unless the component is intentionally part of the app\'s public surface, and protect anything intentional with a signature-level permission',
      'It is required for all activities to function',
      'It enables Doze mode',
      'It improves battery life',
    ],
    correctIndex: 0,
    explanation: 'Exported activities, services, providers, and receivers form the cross-app attack surface. Misconfigured exports are a top OWASP MASTG finding — the relevant Android docs explain that exported defaults changed in API-31, but legacy apps still ship loose exports.',
    distractorRationale: {
      1: 'Most activities can be `exported="false"` and still work in-app.',
      2: 'Doze is a power-management feature, unrelated.',
      3: 'Battery is unrelated.',
    },
    source: { name: 'Android Developers — Activity element (android:exported)', url: 'https://developer.android.com/guide/topics/manifest/activity-element' },
  },

  {
    id: 'mob-012',
    topic: 'mobile',
    subtopic: 'obfuscation',
    difficulty: 'senior',
    question: 'How should a senior pentester treat findings about ProGuard / R8 obfuscation in Android apps?',
    choices: [
      'Obfuscation is a defence-in-depth control under MASVS-RESILIENCE — it slows reverse engineering but does not provide confidentiality. Critical findings (hardcoded keys, business-logic flaws) are not "fixed" by adding obfuscation; the underlying issues must be addressed independently',
      'Obfuscation should always be the primary defence',
      'Obfuscation is identical to AES encryption',
      'Obfuscation is mandated by the iOS App Store',
    ],
    correctIndex: 0,
    explanation: 'OWASP MASVS-RESILIENCE classifies obfuscation as defence in depth. Senior reports are explicit about the distinction: a hardcoded API key is still a hardcoded API key after R8 — obfuscation just slows the attacker. Treating it as primary security is a junior framing.',
    distractorRationale: {
      1: 'Obfuscation is supplementary, not primary.',
      2: 'It is not encryption.',
      3: 'iOS App Store does not mandate ProGuard (which is Android-only).',
    },
    source: { name: 'OWASP MASVS — Resilience (V8 / MASVS-RESILIENCE)', url: 'https://mas.owasp.org/MASVS/12-MASVS-RESILIENCE/' },
  },

  {
    id: 'mob-013',
    topic: 'mobile',
    subtopic: 'ios-ats',
    difficulty: 'senior',
    question: 'You find an iOS app with `NSAllowsArbitraryLoads = true` in its Info.plist. What does this disable, and why is it a finding?',
    choices: [
      'It disables Apple\'s App Transport Security (ATS), which by default enforces TLS 1.2+, forward secrecy, and certificate validation for outbound HTTPS connections. Disabling it sitewide allows plaintext HTTP and weak TLS — a regression from a platform-enforced control',
      'It disables Bluetooth',
      'It disables push notifications',
      'It disables the camera',
    ],
    correctIndex: 0,
    explanation: 'ATS is iOS\'s outbound HTTP hardening. NSAllowsArbitraryLoads bypasses it globally; per-domain exceptions (NSExceptionDomains) are the correct narrow-scope alternative when justified. Apple\'s ATS docs and OWASP MASTG iOS network testing chapter describe this.',
    distractorRationale: {
      1: 'ATS does not control Bluetooth.',
      2: 'It is unrelated to push notifications.',
      3: 'It does not disable the camera.',
    },
    source: { name: 'Apple Developer — App Transport Security (NSAppTransportSecurity)', url: 'https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity' },
  },

  {
    id: 'mob-014',
    topic: 'mobile',
    subtopic: 'biometrics',
    difficulty: 'senior',
    question: 'On Android, why is `BiometricPrompt` (with CryptoObject) preferred over implementing your own biometric check on top of a stored boolean "isUnlocked"?',
    choices: [
      'BiometricPrompt + CryptoObject ties biometric authentication to a Keystore key that requires user authentication for unlock. The cryptographic key is unlocked only by a successful biometric — so an attacker cannot bypass the check by toggling a boolean in the app\'s state. It also delegates the comparison to the OS / hardware, not the app',
      'It animates the prompt nicely',
      'It is required by Google for adverts',
      'It speeds up the app',
    ],
    correctIndex: 0,
    explanation: 'A boolean "isUnlocked" can be flipped at runtime via Frida. BiometricPrompt with a CryptoObject binds the user\'s biometric to a Keystore key whose use is gated by `setUserAuthenticationRequired`, so bypassing the boolean does not unlock the key. Android\'s biometric docs and OWASP MASTG describe this binding.',
    distractorRationale: {
      1: 'UI polish is not the security argument.',
      2: 'Biometric prompts are not advert-related.',
      3: 'Performance is not the rationale.',
    },
    source: { name: 'Android Developers — Biometric authentication with CryptoObject', url: 'https://developer.android.com/training/sign-in/biometric-auth' },
  },

  {
    id: 'mob-015',
    topic: 'mobile',
    subtopic: 'burp-android-ca',
    difficulty: 'senior',
    question: 'You install Burp\'s CA on an Android 7+ device as a USER certificate. The app still does not trust your CA. Why, and what is the senior-level workaround?',
    choices: [
      'Since Android 7 (API-24), apps by default only trust SYSTEM CAs, not user CAs. To intercept, install Burp\'s CA into the system trust store on a rooted device (or via Magisk module / `mv` to /system/etc/security/cacerts), or modify the app\'s `network_security_config.xml` if you have repackaging rights',
      'Android always trusts user CAs',
      'You must use Wireshark instead of Burp',
      'You must downgrade Burp to a 1.x version',
    ],
    correctIndex: 0,
    explanation: 'Android 7 changed the default trust store: apps only trust system CAs unless they opt in via network_security_config to user CAs. Senior testers move the CA into /system/etc/security/cacerts (root required) or repackage with a custom config. Android\'s network security configuration docs describe the change.',
    distractorRationale: {
      1: 'It does not — that is the change introduced in API-24.',
      2: 'Wireshark passively sniffs but does not break TLS.',
      3: 'Burp version is not the issue.',
    },
    source: { name: 'Android Developers — Network security configuration', url: 'https://developer.android.com/privacy-and-security/security-config' },
  },

  {
    id: 'mob-016',
    topic: 'mobile',
    subtopic: 'apk-signing',
    difficulty: 'senior',
    question: 'Why does APK Signature Scheme v2/v3 supersede v1, and what is the security implication of an APK signed only with v1?',
    choices: [
      'v1 (JAR signing) signs files individually, leaving room for tampering attacks like Janus (CVE-2017-13156) on certain Android versions; v2/v3 sign the whole APK\'s integrity block atomically. Apps signed only with v1 may be tamperable on legacy targets and are a finding to flag',
      'v1 is faster than v2',
      'v2 is mandatory for the iOS App Store',
      'v3 disables Google Play Services',
    ],
    correctIndex: 0,
    explanation: 'JAR signing (v1) signed individual entries with manifests, leaving signature-validation gaps that Janus exploited. APK Signature Scheme v2/v3 covers the entire APK with stronger integrity. Android Developers documents the timeline; OWASP MASTG flags v1-only signing as a tamper-resistance gap.',
    distractorRationale: {
      1: 'Speed is not the security argument.',
      2: 'iOS does not use APK signing.',
      3: 'v3 does not disable Google Play.',
    },
    source: { name: 'Android Developers — APK Signature Scheme v2 / v3', url: 'https://source.android.com/docs/security/features/apksigning/v2' },
  },

  {
    id: 'mob-017',
    topic: 'mobile',
    subtopic: 'mobile-top10',
    difficulty: 'senior',
    question: 'Which OWASP Mobile Top 10 (2024) category covers "the app stores authentication tokens insecurely or transmits them poorly"?',
    choices: [
      'M1 — Improper Credential Usage',
      'M3 — Insecure Authentication / Authorization',
      'M9 — Insecure Data Storage',
      'M10 — Insufficient Cryptography',
    ],
    correctIndex: 0,
    explanation: 'OWASP Mobile Top 10 2024 names M1 "Improper Credential Usage" specifically about credentials/tokens — handling, storage, transmission, hardcoded credentials. The OWASP project page lists all ten categories and their definitions.',
    distractorRationale: {
      1: 'M3 in 2024 is broader auth/authorization, not specifically credential mishandling.',
      2: 'Insecure Data Storage is M9 in 2024 and is broader (PII, files, etc.).',
      3: 'M10 covers cryptography weaknesses, not credential storage per se.',
    },
    source: { name: 'OWASP Mobile Top 10 (2024)', url: 'https://owasp.org/www-project-mobile-top-10/' },
  },

  {
    id: 'mob-018',
    topic: 'mobile',
    subtopic: 'reverse-ios',
    difficulty: 'senior',
    question: 'For dynamic instrumentation of an iOS app on a non-jailbroken device, which approach is most viable for a senior tester?',
    choices: [
      'Use a test build with Frida Gadget injected via re-signing (e.g., with Sideloadly or fastlane), or test on a jailbroken device. Apple\'s code-signing model prevents arbitrary instrumentation on stock devices',
      'Run Mimikatz on the iPhone',
      'Decompile the IPA to .NET',
      'Modify the kernel via TFTP',
    ],
    correctIndex: 0,
    explanation: 'iOS\'s code-signing model means runtime instrumentation generally requires either a developer-signed build with Frida Gadget bundled, or a jailbroken device. OWASP MASTG\'s iOS chapter and Frida\'s docs cover both paths and the trade-offs.',
    distractorRationale: {
      1: 'Mimikatz is a Windows credential tool.',
      2: 'iOS apps are not .NET binaries.',
      3: 'TFTP-kernel-mod is not how iOS jailbreaks work.',
    },
    source: { name: 'OWASP MASTG — iOS Tampering and Reverse Engineering', url: 'https://mas.owasp.org/MASTG/0x06b-Tampering-and-Reverse-Engineering-iOS/' },
  },

  {
    id: 'mob-019',
    topic: 'mobile',
    subtopic: 'mobsf',
    difficulty: 'senior',
    question: 'MobSF (Mobile Security Framework) is best described as which kind of tool, and what is the senior caveat about using it?',
    choices: [
      'An open-source automated mobile static + dynamic analysis platform that produces a baseline report. Caveat: automated tools miss business-logic flaws and have false positives — senior reports treat MobSF output as a starting point that must be triaged manually, not as the engagement deliverable',
      'A network packet sniffer',
      'A jailbreak tool for iOS',
      'A firmware extractor for routers',
    ],
    correctIndex: 0,
    explanation: 'MobSF automates many static and basic dynamic checks (manifest, permissions, hardcoded patterns, basic Frida hooks). It accelerates baseline coverage, but every senior pentester knows to triage findings and add manual analysis (auth flows, API logic, key handling). OWASP MASTG references it as one of several tools.',
    distractorRationale: {
      1: 'Wireshark/tcpdump are sniffers; not MobSF.',
      2: 'MobSF does not jailbreak.',
      3: 'It is not a router-firmware tool.',
    },
    source: { name: 'OWASP MASTG — Tools (MobSF)', url: 'https://mas.owasp.org/MASTG/0x08a-Testing-Tools/' },
  },

  {
    id: 'mob-020',
    topic: 'mobile',
    subtopic: 'mobile-api',
    difficulty: 'senior',
    question: 'Why do experienced mobile pentesters say "most mobile findings are actually API findings"?',
    choices: [
      'The mobile client typically delegates auth, business logic, and data access to a back-end API. The phone itself is just a UI; the bulk of impactful findings — IDOR, broken object-level auth, missing rate limit, mass assignment — live on the API. Senior methodology pivots quickly from on-device tests to proxy-the-API, OWASP API Security Top 10',
      'Phones never have local logic',
      'Mobile apps cannot store data locally',
      'iOS apps run on the server',
    ],
    correctIndex: 0,
    explanation: 'OWASP MASTG and the OWASP API Security Top 10 are explicit that mobile-client testing includes thorough API testing. The client is one attack surface, but the high-impact findings (data exposure, BOLA, mass assignment) almost always sit on the API. Senior reports typically have an API section that dwarfs the on-device section.',
    distractorRationale: {
      1: 'They do; but the most impactful logic is server-side.',
      2: 'They can; the point is server-side logic dominates impact.',
      3: 'iOS apps run on the device.',
    },
    source: { name: 'OWASP API Security Top 10', url: 'https://owasp.org/API-Security/editions/2023/en/0x00-header/' },
  },

  {
    id: 'mob-021', topic: 'mobile', subtopic: 'android-permissions-runtime', difficulty: 'senior',
    question: 'On Android 6.0+ (API 23), dangerous permissions follow the runtime permission model. What is the senior implication for testing?',
    choices: ['Permissions in the dangerous category (camera, location, contacts, microphone, etc.) require runtime grant by the user; install-time install no longer suffices. Senior testers verify that the app handles denial gracefully (no crashes), does not leak data when permission is missing, and respects revocation', 'All permissions are install-time', 'Permissions are signed by Google', 'Permissions are decided by the BIOS'],
    correctIndex: 0,
    explanation: 'Runtime permissions (introduced in M, expanded since) are documented in Android Developers. OWASP MASTG covers test cases for the model.',
    distractorRationale: { 1: 'API 22 and below were install-time; modern is runtime for dangerous permissions.', 2: 'Google does not sign per-permission.', 3: 'BIOS is unrelated.' },
    source: { name: 'Android Developers — Request app permissions (runtime permissions)', url: 'https://developer.android.com/training/permissions/requesting' },
  },

  {
    id: 'mob-022', topic: 'mobile', subtopic: 'content-provider', difficulty: 'senior',
    question: 'A `ContentProvider` is exported (`android:exported="true"`) without `android:permission` and without `<grant-uri-permissions>` constraints. Why is this dangerous?',
    choices: ['Other apps can query, insert, update, or delete data via `content://<authority>/...` URIs without authentication. The senior recommendation is to set `exported="false"` (default since API 17 for providers without intent filters) or apply a signature-level permission', 'It causes a buffer overflow', 'It enables Bluetooth pairing', 'It disables the keyboard'],
    correctIndex: 0,
    explanation: 'OWASP MASTG\'s Android platform-interaction chapter covers exported providers. Many real-world data-leak findings are `content://` exposures of attached SQLite databases or file paths.',
    distractorRationale: { 1: 'No memory corruption.', 2: 'No Bluetooth involvement.', 3: 'No keyboard involvement.' },
    source: { name: 'Android Developers — Provider element (exported)', url: 'https://developer.android.com/guide/topics/manifest/provider-element' },
  },

  {
    id: 'mob-023', topic: 'mobile', subtopic: 'broadcast-receiver', difficulty: 'senior',
    question: 'An app registers a `BroadcastReceiver` with `android:exported="true"` that triggers a privileged action. What attack does this enable?',
    choices: ['Other apps can send intents to the receiver, triggering the privileged action without permission. Mitigation: set `exported="false"` for receivers that do not need cross-app reach, or require a signature-level permission so only the app\'s own components can invoke it', 'It leaks credentials over Bluetooth', 'It bypasses TLS', 'It causes battery drain only'],
    correctIndex: 0,
    explanation: 'Receiver-based attacks are a frequent OWASP MASTG finding. Android docs recommend `exported="false"` for internal receivers and explicit permission gating for external ones.',
    distractorRationale: { 1: 'No Bluetooth involvement.', 2: 'Unrelated to TLS.', 3: 'Not a battery issue.' },
    source: { name: 'Android Developers — Receiver element (exported)', url: 'https://developer.android.com/guide/topics/manifest/receiver-element' },
  },

  {
    id: 'mob-024', topic: 'mobile', subtopic: 'implicit-vs-explicit-intents', difficulty: 'senior',
    question: 'For sensitive cross-component navigation, why does Android development guidance prefer explicit intents over implicit intents?',
    choices: ['Explicit intents target a specific component by ClassName/ComponentName; implicit intents broadcast intent filters and any matching app may handle them, including malicious ones (intent redirection). Explicit intents prevent intent hijacking for sensitive flows', 'Explicit intents are encrypted', 'Implicit intents always require root', 'Explicit intents work only on iOS'],
    correctIndex: 0,
    explanation: 'OWASP MASTG and Android docs both emphasise explicit intents for sensitive flows. The risk is that a malicious app registers a matching intent filter and is selected as the handler.',
    distractorRationale: { 1: 'Neither variant is encrypted by default.', 2: 'No root requirement.', 3: 'Android-only construct.' },
    source: { name: 'Android Developers — Intents and Intent Filters (explicit intents)', url: 'https://developer.android.com/guide/components/intents-filters' },
  },

  {
    id: 'mob-025', topic: 'mobile', subtopic: 'strandhogg', difficulty: 'senior',
    question: 'StrandHogg (CVE-2020-0096) is which class of attack on Android?',
    choices: ['Task affinity / task hijacking — a malicious app sets `taskAffinity` to match a target app and uses `allowTaskReparenting`/`singleTask` flags so when the user launches the target, the malicious activity appears in its task stack instead, enabling phishing of credentials', 'A buffer overflow in the kernel', 'An SSL pinning bypass', 'A keyboard-cache leak'],
    correctIndex: 0,
    explanation: 'Promon\'s StrandHogg research and the follow-up StrandHogg 2.0 exploited Android\'s task model. Google patched the underlying behaviour in subsequent Android releases. OWASP MASTG covers task-hijack patterns.',
    distractorRationale: { 1: 'Not a memory bug.', 2: 'Not pinning related.', 3: 'Not keyboard-cache.' },
    source: { name: 'Promon — StrandHogg vulnerability disclosure', url: 'https://promon.io/security-news/strandhogg' },
  },

  {
    id: 'mob-026', topic: 'mobile', subtopic: 'android-allowbackup', difficulty: 'senior',
    question: '`android:allowBackup="true"` (or default true on API < 31) enables what, and why is it a finding?',
    choices: ['Auto Backup includes the app\'s data in cloud / `adb backup` extracts. Sensitive app data may be exfiltrated via a USB-connected device with debugging enabled, or via a compromised Google account. Recommendation: set `android:allowBackup="false"` (or use `fullBackupOnly` rules) for apps holding sensitive data', 'It enables clipboard sharing', 'It runs the app in safe mode', 'It disables HTTPS'],
    correctIndex: 0,
    explanation: 'OWASP MASTG\'s storage chapter and Android docs both flag this. Many financial apps explicitly disable backups for sensitive data.',
    distractorRationale: { 1: 'Clipboard is a different surface.', 2: 'No safe-mode behaviour.', 3: 'HTTPS is unrelated.' },
    source: { name: 'Android Developers — Application element (allowBackup)', url: 'https://developer.android.com/guide/topics/manifest/application-element#allowbackup' },
  },

  {
    id: 'mob-027', topic: 'mobile', subtopic: 'webview-allowfileaccess', difficulty: 'senior',
    question: 'A WebView calls `setAllowFileAccessFromFileURLs(true)` and loads attacker-influenced content. What does this enable?',
    choices: ['JavaScript running in a `file://` URL can read other local files via XHR (e.g., the app\'s SharedPreferences, databases) — a same-origin policy relaxation that defeats the WebView sandbox. Modern Android defaults this to false; senior testers flag any app that re-enables it', 'It enables Bluetooth audio', 'It runs WebView in safe mode', 'It enforces TLS pinning'],
    correctIndex: 0,
    explanation: 'Android docs document setAllowFileAccessFromFileURLs and setAllowUniversalAccessFromFileURLs as historical compatibility flags that should remain false. Many CVEs trace back to apps re-enabling them.',
    distractorRationale: { 1: 'Bluetooth is unrelated.', 2: 'No safe-mode mechanic.', 3: 'TLS pinning is separate.' },
    source: { name: 'Android Developers — WebSettings.setAllowFileAccessFromFileURLs', url: 'https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccessFromFileURLs(boolean)' },
  },

  {
    id: 'mob-028', topic: 'mobile', subtopic: 'flag-secure', difficulty: 'senior',
    question: 'Setting `WindowManager.LayoutParams.FLAG_SECURE` on a sensitive Android Activity does what?',
    choices: ['Prevents screenshots and screen recording (including by the OS\'s Recents view) and blocks the window from being captured on non-secure outputs (Miracast etc.). Recommendation: set on screens displaying sensitive data such as banking or password fields', 'It encrypts the activity', 'It runs the activity in an isolated user', 'It disables Wi-Fi'],
    correctIndex: 0,
    explanation: 'FLAG_SECURE is documented in Android Developers and recommended by OWASP MASTG for any screen displaying secrets. It is a defence in depth, not a strong security control alone.',
    distractorRationale: { 1: 'No encryption involved.', 2: 'No isolation.', 3: 'No Wi-Fi effect.' },
    source: { name: 'Android Developers — WindowManager.LayoutParams.FLAG_SECURE', url: 'https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE' },
  },

  {
    id: 'mob-029', topic: 'mobile', subtopic: 'ios-data-protection', difficulty: 'senior',
    question: 'iOS Data Protection classes determine when files are accessible. Which class provides the strongest protection?',
    choices: ['NSFileProtectionComplete — the file is encrypted with a key derived from the user passcode and Secure Enclave, available only when the device is unlocked. Reads while locked fail. Used for the most sensitive data; default for many app sandbox files', 'NSFileProtectionNone (no protection)', 'NSFileProtectionPublic', 'NSFileProtectionMaximum'],
    correctIndex: 0,
    explanation: 'Apple\'s File Protection documentation enumerates the classes (Complete, CompleteUnlessOpen, CompleteUntilFirstUserAuthentication, None). Complete is strongest. OWASP MASTG iOS chapter discusses choosing the right class.',
    distractorRationale: { 1: 'No protection is the weakest.', 2: 'Not a real class name.', 3: 'Not a real class name.' },
    source: { name: 'Apple Developer — File Protection (NSFileProtectionType)', url: 'https://developer.apple.com/documentation/foundation/nsfileprotectiontype' },
  },

  {
    id: 'mob-030', topic: 'mobile', subtopic: 'ios-keychain-access-groups', difficulty: 'senior',
    question: 'iOS Keychain access groups allow what, and what is the senior risk?',
    choices: ['Multiple apps with the same Team ID and a shared keychain access group can read each other\'s items — designed for app-suites. Risk: if a less-secure companion app in the same access group is compromised, sensitive items shared into the group are exposed. Recommendation: scope items narrowly, do not share unless required', 'Keychain access groups encrypt the items', 'They store items on iCloud only', 'They disable the Secure Enclave'],
    correctIndex: 0,
    explanation: 'Apple\'s Keychain documentation explains access group sharing. OWASP MASTG iOS data-storage chapter calls out audit of access groups.',
    distractorRationale: { 1: 'Encryption is a Keychain property, not the access group.', 2: 'iCloud Keychain is separate.', 3: 'Secure Enclave is independent.' },
    source: { name: 'Apple Developer — Sharing access to keychain items among a collection of apps', url: 'https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps' },
  },

  {
    id: 'mob-031', topic: 'mobile', subtopic: 'drozer', difficulty: 'senior',
    question: 'Drozer is a:',
    choices: ['Mobile (Android) attack/assessment framework: lets you probe IPC surface, content providers, exported activities/services, intent fuzzing, and SQLi against ContentProviders. Useful for IPC-side reconnaissance from a single command-line', 'Network sniffer', 'Wi-Fi cracker', 'iOS jailbreaking tool'],
    correctIndex: 0,
    explanation: 'WithSecure Labs maintains drozer; it has been a long-standing Android-pentest tool. The repository docs walk through modules.',
    distractorRationale: { 1: 'Not a sniffer.', 2: 'Not Wi-Fi.', 3: 'Android, not iOS.' },
    source: { name: 'WithSecure Labs — drozer GitHub', url: 'https://github.com/WithSecureLabs/drozer' },
  },

  {
    id: 'mob-032', topic: 'mobile', subtopic: 'trustkit', difficulty: 'senior',
    question: 'TrustKit is a:',
    choices: ['Mobile (iOS/Android) library that simplifies and standardises TLS pinning configuration, with reporting hooks. Used by apps to pin certificates without writing low-level pinning code. Senior testers verify that pins match the actual leaf/intermediate/SPKI of the production cert', 'A web framework', 'A jailbreak tool', 'A logging library'],
    correctIndex: 0,
    explanation: 'TrustKit is an open-source pinning library by Datatheorem, used widely. The README describes pin formats, fallback policies, and reporting.',
    distractorRationale: { 1: 'Not a web framework.', 2: 'Not a jailbreak.', 3: 'Not a logger.' },
    source: { name: 'Datatheorem — TrustKit GitHub', url: 'https://github.com/datatheorem/TrustKit' },
  },

  {
    id: 'mob-033', topic: 'mobile', subtopic: 'aab-bundle', difficulty: 'senior',
    question: 'Android App Bundle (.aab) is the modern publishing format on Play Store. What does it change for testers?',
    choices: ['Apps are uploaded as bundles; Google generates the actual APKs (`split APKs`) for each device. To analyse an installed app you usually pull the active split APKs from the device or use bundletool to generate APKs from the .aab. Single monolithic .apk extraction may miss feature modules', 'Bundles are unencrypted text', 'Bundles run in a VM only', 'Bundles disable Frida'],
    correctIndex: 0,
    explanation: 'Android Developers documents the bundle model and `bundletool`. Senior mobile testers update their tooling to support split APKs (apktool, jadx, MobSF all handle aab/splits today).',
    distractorRationale: { 1: 'They are zip-archive based with binary content.', 2: 'They run on the device.', 3: 'Frida works regardless.' },
    source: { name: 'Android Developers — About Android App Bundles', url: 'https://developer.android.com/guide/app-bundle' },
  },

  {
    id: 'mob-034', topic: 'mobile', subtopic: 'r8-shrinking', difficulty: 'senior',
    question: 'R8 (Android\'s default code shrinker since AGP 3.4) does what, and how does it relate to ProGuard?',
    choices: ['R8 replaces ProGuard for shrinking, optimisation, obfuscation, and dexing — performing all four in one pass with better optimisations. ProGuard configuration files (`-keep`, etc.) are still used. Senior framing: like ProGuard, R8 is defence-in-depth, not a confidentiality control', 'R8 disables Frida', 'R8 enables FLAG_SECURE', 'R8 is iOS-specific'],
    correctIndex: 0,
    explanation: 'Android Developers documents R8 as the modern shrinker; OWASP MASTG covers it under MASVS-RESILIENCE.',
    distractorRationale: { 1: 'No effect on Frida.', 2: 'FLAG_SECURE is a separate UI flag.', 3: 'Android-only.' },
    source: { name: 'Android Developers — Shrink, obfuscate, and optimize your app (R8)', url: 'https://developer.android.com/build/shrink-code' },
  },

  {
    id: 'mob-035', topic: 'mobile', subtopic: 'ios-encrypted-backup', difficulty: 'senior',
    question: 'iOS encrypted backups via Finder/iTunes change forensic accessibility how?',
    choices: ['Encrypted backups (with a user-set password) include data NOT in unencrypted backups (Health, Activity, Wi-Fi passwords, Saved Safari data). The encryption is AES with a key derived from the user-set backup password — recoverable via password attacks. Senior framing: encrypted backups can leak more sensitive data IF the password is weak, but also protect against trivial extraction', 'They are quantum-encrypted', 'They are stored only on iCloud', 'They use Touch ID only'],
    correctIndex: 0,
    explanation: 'Apple Support documents the difference between encrypted and unencrypted backups. Tools like Elcomsoft / iLeapp / Cellebrite leverage password recovery against weak passwords. OWASP MASTG covers the testing implications.',
    distractorRationale: { 1: 'Standard AES.', 2: 'Local backups exist alongside iCloud.', 3: 'Touch ID is for device unlock.' },
    source: { name: 'Apple Support — About encrypted backups in iTunes', url: 'https://support.apple.com/en-us/HT205220' },
  },

  {
    id: 'mob-036', topic: 'mobile', subtopic: 'shared-user-id', difficulty: 'senior',
    question: 'Why is `android:sharedUserId` deprecated, and what is the senior security framing?',
    choices: ['sharedUserId let multiple apps signed by the same key share a Linux UID and thus filesystem permissions, but it produced upgrade/rollback hazards and is deprecated since API 29. Senior testers flag any new app using it as a finding because it expands attack surface across apps', 'It is the only way to share data', 'It is required for Bluetooth', 'It is unique to Wear OS'],
    correctIndex: 0,
    explanation: 'Android Developers documents the deprecation. Modern alternatives use ContentProviders or BroadcastReceivers with signature permissions.',
    distractorRationale: { 1: 'Other mechanisms exist.', 2: 'Bluetooth is unrelated.', 3: 'Not Wear-only.' },
    source: { name: 'Android Developers — Manifest sharedUserId (deprecated)', url: 'https://developer.android.com/guide/topics/manifest/manifest-element#uid' },
  },

  {
    id: 'mob-037', topic: 'mobile', subtopic: 'android-encrypted-shared-prefs', difficulty: 'senior',
    question: 'What does `EncryptedSharedPreferences` from `androidx.security.crypto` provide?',
    choices: ['SharedPreferences-compatible API that transparently encrypts keys (AES-256 SIV) and values (AES-256 GCM) using master keys held in the Android Keystore. A reasonable choice for sensitive data when you need a SharedPreferences-shaped API but want at-rest protection', 'Plain unencrypted storage', 'Storage on Google\'s servers', 'A SQL database'],
    correctIndex: 0,
    explanation: 'Jetpack Security / androidx.security.crypto provides EncryptedSharedPreferences and EncryptedFile. Android Developers documents the key schemes.',
    distractorRationale: { 1: 'It is encrypted.', 2: 'Stored locally.', 3: 'Not SQLite.' },
    source: { name: 'Android Developers — EncryptedSharedPreferences', url: 'https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences' },
  },

  {
    id: 'mob-038', topic: 'mobile', subtopic: 'frida-gadget', difficulty: 'senior',
    question: 'Frida Gadget enables what use case?',
    choices: ['Inject Frida\'s instrumentation library into an app at build/repackage time so it can be controlled without root/jailbreak (because the app loads the gadget itself as a "regular" library). Useful for testing on stock devices when the app can be re-signed/installed via developer profile', 'It encrypts the app', 'It signs APKs', 'It blocks Frida'],
    correctIndex: 0,
    explanation: 'Frida\'s docs describe Gadget as the embedded counterpart of the daemon-based `frida-server`. It lets testers operate on non-rooted/non-jailbroken devices when re-signing is possible.',
    distractorRationale: { 1: 'No encryption.', 2: 'Not a signer.', 3: 'It is the opposite — Frida itself.' },
    source: { name: 'Frida — Gadget documentation', url: 'https://frida.re/docs/gadget/' },
  },

  {
    id: 'mob-039', topic: 'mobile', subtopic: 'mobile-rate-limit', difficulty: 'senior',
    question: 'OWASP API Security Top 10 (2023) places "Unrestricted Resource Consumption" at #4. Which mobile-API testing observation maps directly to it?',
    choices: ['No rate limit / no anti-automation on sensitive endpoints (login, OTP send, pricing) called from the mobile client. Mobile clients trust the API to enforce limits — testers should send bursts and concurrent requests to surface missing controls', 'Mobile apps should rate-limit themselves', 'iOS handles rate limiting via FaceID', 'Android disables retry after 3 attempts globally'],
    correctIndex: 0,
    explanation: 'API4:2023 covers resource consumption / rate limiting. Mobile testing pairs naturally with API testing for this. OWASP MASTG\'s API testing chapter ties them together.',
    distractorRationale: { 1: 'Client-side rate-limiting can be bypassed.', 2: 'FaceID is biometric, not rate-limiting.', 3: 'No global retry limit.' },
    source: { name: 'OWASP API Security Top 10 — API4:2023 Unrestricted Resource Consumption', url: 'https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/' },
  },

  {
    id: 'mob-040', topic: 'mobile', subtopic: 'ios-uipasteboard', difficulty: 'senior',
    question: 'Apps that copy sensitive data (e.g., one-time passwords, recovery seeds) to `UIPasteboard.general` create which risk?',
    choices: ['Other apps can read the system pasteboard; iOS shows a banner since iOS 14 indicating which app accessed it. Senior recommendation: avoid system pasteboard for sensitive data, or use named pasteboards with limited lifetime, or set the `expirationDate` on UIPasteboard items (iOS 10+)', 'Pasteboard is sandbox-isolated', 'Pasteboard requires Face ID', 'Pasteboard is end-to-end encrypted'],
    correctIndex: 0,
    explanation: 'iOS\'s general pasteboard is shared. Apple\'s documentation discusses pasteboard scoping (named pasteboards, expirationDate). OWASP MASTG covers pasteboard data leakage tests.',
    distractorRationale: { 1: 'It is shared by design.', 2: 'No biometric required.', 3: 'Not e2e encrypted.' },
    source: { name: 'Apple Developer — UIPasteboard', url: 'https://developer.apple.com/documentation/uikit/uipasteboard' },
  },

  {
    id: 'mob-041', topic: 'mobile', subtopic: 'ios-mach-o', difficulty: 'senior',
    question: 'iOS app binaries are in Mach-O format. Why might an attacker run `class-dump` or `otool` against a Mach-O?',
    choices: ['To extract Objective-C class metadata (selectors, properties, ivars) and inspect imports/strings. Reveals API endpoints, hardcoded keys, anti-debugging routines, and class structures useful for hooking with Frida. Caveat: Swift-only apps expose less metadata than Objective-C ones', 'To compile to Java', 'To convert to ELF', 'To verify Apple\'s signature'],
    correctIndex: 0,
    explanation: 'Mach-O is documented in Apple\'s ABI references; tools like class-dump and otool expose metadata. OWASP MASTG iOS reverse-engineering chapter covers them.',
    distractorRationale: { 1: 'Not a Java compiler.', 2: 'No format conversion.', 3: 'Apple signature verification is `codesign`.' },
    source: { name: 'Apple Developer — Mach-O File Format Reference', url: 'https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/0-Introduction/introduction.html' },
  },

  {
    id: 'mob-042', topic: 'mobile', subtopic: 'ios-debugger-detection', difficulty: 'senior',
    question: 'A common iOS anti-debug technique calls `ptrace(PT_DENY_ATTACH)`. What does this do, and what is the senior framing?',
    choices: ['Asks the kernel to deny future debugger attaches to the process. It is bypassable (LLDB workarounds, Frida, runtime patching) and falls under MASVS-RESILIENCE — defence in depth, not a primary control. Senior reports treat it as a tampering signal, not a confidentiality control', 'It encrypts the binary', 'It is unbreakable', 'It enables Touch ID'],
    correctIndex: 0,
    explanation: 'PT_DENY_ATTACH is a long-standing iOS anti-debug primitive. The OWASP MASTG documents many bypasses and clarifies its role as resilience.',
    distractorRationale: { 1: 'No encryption.', 2: 'Bypassable.', 3: 'No biometric tie-in.' },
    source: { name: 'OWASP MASTG — iOS Anti-Reversing (PT_DENY_ATTACH)', url: 'https://mas.owasp.org/MASTG/0x06j-Testing-Resiliency-Against-Reverse-Engineering/' },
  },

  {
    id: 'mob-043', topic: 'mobile', subtopic: 'cert-transparency', difficulty: 'senior',
    question: 'How does Certificate Transparency (CT) protect mobile apps using public-CA certificates?',
    choices: ['Browsers and recent OSes require certificates to be logged in CT logs (RFC 6962); misissued certs become publicly visible and revocable quickly. For mobile apps using TLS pinning, CT plus pinning combines two layers — but apps that pin to the leaf must rotate carefully when CAs reissue', 'CT is a backup mechanism', 'CT replaces TLS', 'CT is ICS-only'],
    correctIndex: 0,
    explanation: 'RFC 6962 / CT framework provides public auditability for issued certs. Apple and Google require CT-logged certs for many use cases. OWASP MASTG covers the relationship with TLS pinning.',
    distractorRationale: { 1: 'Active control, not backup.', 2: 'Complements TLS.', 3: 'IT and mobile context.' },
    source: { name: 'IETF RFC 6962 — Certificate Transparency', url: 'https://datatracker.ietf.org/doc/html/rfc6962' },
  },

  {
    id: 'mob-044', topic: 'mobile', subtopic: 'webview-savePassword', difficulty: 'senior',
    question: '`WebView.setSavePassword(true)` (deprecated since API 18) historically did what?',
    choices: ['Persisted form passwords in plaintext in the WebView database — readable by any app on a rooted device or via `adb backup`. Modern Android removed the API; senior testers ensure no legacy code paths still call it and that any custom autofill stores credentials securely (e.g., Keystore-backed)', 'Encrypted passwords with Touch ID', 'Sent passwords to Google', 'Encrypted using TPM'],
    correctIndex: 0,
    explanation: 'Android docs marked savePassword deprecated and removed it; OWASP MASTG references it under storage findings.',
    distractorRationale: { 1: 'No biometric tie.', 2: 'No upload.', 3: 'No TPM tie.' },
    source: { name: 'Android Developers — WebSettings.setSavePassword (deprecated)', url: 'https://developer.android.com/reference/android/webkit/WebSettings#setSavePassword(boolean)' },
  },

  {
    id: 'mob-045', topic: 'mobile', subtopic: 'android-app-links', difficulty: 'senior',
    question: 'Android App Links (since API 23) verify ownership of a domain to claim deep links. How is verification performed?',
    choices: ['The site hosts a `/.well-known/assetlinks.json` file declaring the package name and signing certificate fingerprints; Android verifies this at install time and at periodic intervals. Verified App Links open without disambiguation dialogs and resist link-hijacking by other apps', 'Via DNS TXT only', 'Via Google manual approval', 'Via SMTP DKIM'],
    correctIndex: 0,
    explanation: 'Android Developers documents App Links and the assetlinks.json mechanism. OWASP MASTG covers them when reviewing mobile-API integration.',
    distractorRationale: { 1: 'DNS TXT alone is insufficient.', 2: 'Automated.', 3: 'Email auth, unrelated.' },
    source: { name: 'Android Developers — Verify Android App Links', url: 'https://developer.android.com/training/app-links/verify-site-associations' },
  },

  {
    id: 'mob-046', topic: 'mobile', subtopic: 'ios-universal-links', difficulty: 'senior',
    question: 'iOS Universal Links work by:',
    choices: ['Hosting an `apple-app-site-association` (AASA) file at `/.well-known/apple-app-site-association` on the domain, declaring which paths the app handles. iOS fetches the AASA at install time. If verification succeeds, opening matching URLs goes directly to the app — bypassing custom URL scheme hijacks', 'A DNS CAA record', 'Apple manual review', 'TXT records'],
    correctIndex: 0,
    explanation: 'Apple\'s Universal Links documentation describes AASA and the verification flow. OWASP MASTG iOS chapter reviews testing implications.',
    distractorRationale: { 1: 'CAA is for cert issuance.', 2: 'Automated.', 3: 'TXT is for various uses.' },
    source: { name: 'Apple Developer — Allowing apps and websites to link to your content (Universal Links)', url: 'https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content' },
  },

  {
    id: 'mob-047', topic: 'mobile', subtopic: 'android-selinux', difficulty: 'senior',
    question: 'Android implements SELinux in enforcing mode since 5.0. What does this mean for app security?',
    choices: ['Mandatory Access Control on top of the Linux DAC (UIDs/GIDs); each process runs in a defined SELinux domain that constrains which kernel objects it can access (file labels, sockets, properties). Sandbox escapes that bypass DAC still hit SELinux. Senior context: many post-exploitation primitives chain DAC bypass with SELinux policy weaknesses', 'It is GUI-only', 'It is iOS-only', 'It is opt-in for apps'],
    correctIndex: 0,
    explanation: 'AOSP / Android Open Source Project documents SELinux extensively. Modern Android security relies on layered DAC + MAC + the SE for Android policy.',
    distractorRationale: { 1: 'Kernel feature, not GUI.', 2: 'Android.', 3: 'System-wide, not per-app.' },
    source: { name: 'AOSP — Security-Enhanced Linux (SELinux) in Android', url: 'https://source.android.com/docs/security/features/selinux' },
  },

  {
    id: 'mob-048', topic: 'mobile', subtopic: 'mobile-anti-tamper', difficulty: 'senior',
    question: 'OWASP MASVS-RESILIENCE includes integrity checks. What is the senior reading on their value?',
    choices: ['Anti-tamper integrity checks (file hashes, signature verification, anti-Frida hooks) raise the cost of attack but are bypassable with sufficient effort; they are appropriate for high-value targets but should NEVER substitute for server-side trust decisions. Apps must assume the client can lie', 'They are unbreakable', 'They eliminate need for server-side authentication', 'They are required by law for all apps'],
    correctIndex: 0,
    explanation: 'MASVS-RESILIENCE explicitly frames these as defence in depth. OWASP MASTG documents many bypasses. The maxim "never trust the client" still holds.',
    distractorRationale: { 1: 'Bypassable.', 2: 'Server-side trust still required.', 3: 'No universal legal mandate.' },
    source: { name: 'OWASP MASVS — Resilience requirements', url: 'https://mas.owasp.org/MASVS/12-MASVS-RESILIENCE/' },
  },

  {
    id: 'mob-049', topic: 'mobile', subtopic: 'mobile-jb-detect', difficulty: 'senior',
    question: 'Common iOS jailbreak detection checks include:',
    choices: ['File existence (`/Applications/Cydia.app`, `/private/var/lib/apt/`), URL scheme `cydia://`, fork() success, write outside the sandbox, and dyld inspection for jailbreak tweaks. Each is independently bypassable (Frida hooks, custom Objection scripts, Liberty Lite) — combine multiple checks for a slowdown effect, but accept they are resilience, not security', 'TPM attestation', 'Apple Pay status', 'iCloud sync state'],
    correctIndex: 0,
    explanation: 'OWASP MASTG iOS resiliency chapter and Frida\'s ios anti-jailbreak bypass scripts catalog the common checks and their bypasses.',
    distractorRationale: { 1: 'iOS uses Secure Enclave; TPM is not the term.', 2: 'Apple Pay is independent.', 3: 'iCloud is unrelated.' },
    source: { name: 'OWASP MASTG — iOS Anti-Reversing Defenses', url: 'https://mas.owasp.org/MASTG/0x06j-Testing-Resiliency-Against-Reverse-Engineering/' },
  },

  {
    id: 'mob-050', topic: 'mobile', subtopic: 'ios-app-extensions', difficulty: 'senior',
    question: 'iOS App Extensions (share, action, today widget, custom keyboard) introduce attack surface because:',
    choices: ['Extensions run in their own process with their own entitlements but share the App Group container. A malicious or hijacked extension can read shared keychain items / files in the App Group. Senior reports check what each extension touches and whether its risk profile matches the host app', 'Extensions cannot be debugged', 'Extensions run with root', 'Extensions are required for App Store submission'],
    correctIndex: 0,
    explanation: 'Apple\'s App Extensions guide and OWASP MASTG iOS chapter cover extension security. The shared App Group container is the typical leakage vector.',
    distractorRationale: { 1: 'Debuggable.', 2: 'No root on iOS.', 3: 'Optional.' },
    source: { name: 'Apple Developer — App Extension Programming Guide', url: 'https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/' },
  },

  {
    id: 'mob-051', topic: 'mobile', subtopic: 'webview-mixed-content', difficulty: 'senior',
    question: 'On Android, `WebView.setMixedContentMode(MIXED_CONTENT_ALWAYS_ALLOW)` enables what risk?',
    choices: ['HTTPS pages loaded in the WebView can include subresources over HTTP, which bypasses the protection HTTPS provides for the page. Recommendation: always use `MIXED_CONTENT_NEVER_ALLOW`. Modern Android defaults to never-allow on API 21+', 'It enables push notifications', 'It enforces HSTS', 'It is required for video playback'],
    correctIndex: 0,
    explanation: 'Android Developers documents the mixed-content modes. OWASP MASTG\'s network testing chapter flags any app that downgrades to ALWAYS_ALLOW.',
    distractorRationale: { 1: 'Not push-related.', 2: 'Opposite — it weakens HTTPS.', 3: 'Video playback is unrelated.' },
    source: { name: 'Android Developers — WebSettings.setMixedContentMode', url: 'https://developer.android.com/reference/android/webkit/WebSettings#setMixedContentMode(int)' },
  },

  {
    id: 'mob-052', topic: 'mobile', subtopic: 'mobile-screen-record', difficulty: 'senior',
    question: 'On iOS, what mechanism does an app use to detect that screen recording or AirPlay mirroring is active, and why is this useful?',
    choices: ['`UIScreen.main.isCaptured` (and `.captureDidChangeNotification`) tells the app when the screen is being captured. Apps holding sensitive data may obscure content during capture. Senior framing: this is a UI/UX-level mitigation, not a guarantee — screenshots can still be taken via OS controls or jailbroken hooks', 'It uses Touch ID', 'It calls a kernel API directly', 'It is impossible to detect'],
    correctIndex: 0,
    explanation: 'Apple\'s UIScreen documentation describes captured state. OWASP MASTG iOS storage chapter recommends obscuring sensitive content during capture for high-risk apps.',
    distractorRationale: { 1: 'No biometric tie.', 2: 'High-level UIKit API.', 3: 'It is detectable in many cases.' },
    source: { name: 'Apple Developer — UIScreen.isCaptured', url: 'https://developer.apple.com/documentation/uikit/uiscreen/2921651-iscaptured' },
  },

  {
    id: 'mob-053', topic: 'mobile', subtopic: 'mobile-asvs-mapping', difficulty: 'senior',
    question: 'When an enterprise asks for a "comprehensive mobile security baseline" beyond top-10 awareness, the senior recommendation is to map findings to:',
    choices: ['OWASP MASVS — verifiable security requirements with L1 / L2 maturity levels for mobile apps; complemented by MASTG (testing guide). Together they give a verifiable, testable baseline (analogous to ASVS for web)', 'OWASP Mobile Top 10 only', 'PCI DSS only', 'CIS only'],
    correctIndex: 0,
    explanation: 'MASVS is the verification standard; Mobile Top 10 is awareness/risk. Senior reports cite MASVS controls when scoping a baseline.',
    distractorRationale: { 1: 'Top 10 is awareness.', 2: 'PCI is payments.', 3: 'CIS is general infra.' },
    source: { name: 'OWASP MASVS — Mobile Application Security Verification Standard', url: 'https://mas.owasp.org/MASVS/' },
  },

  {
    id: 'mob-054', topic: 'mobile', subtopic: 'mobile-magisk', difficulty: 'senior',
    question: 'Magisk is a popular "systemless" rooting solution on Android. Why is it relevant to senior mobile testing?',
    choices: ['Systemless root + Magisk Hide / DenyList lets an attacker (or tester) gain root while presenting an unrooted appearance to apps that perform integrity checks via Play Integrity / SafetyNet. Senior reports note that Play Integrity checks alone are not sufficient as anti-tamper because Magisk-style bypass is tractable', 'Magisk encrypts the kernel', 'Magisk replaces SELinux', 'Magisk is iOS-only'],
    correctIndex: 0,
    explanation: 'Magisk\'s GitHub and the long-running cat-and-mouse with SafetyNet/Play Integrity is well documented. Senior testers know root-detection alone (without server-side anomaly correlation) is brittle.',
    distractorRationale: { 1: 'No kernel encryption.', 2: 'SELinux still present.', 3: 'Android.' },
    source: { name: 'Magisk — official GitHub repository', url: 'https://github.com/topjohnwu/Magisk' },
  },

  {
    id: 'mob-055', topic: 'mobile', subtopic: 'play-integrity', difficulty: 'senior',
    question: 'Google\'s Play Integrity API (successor to SafetyNet Attestation) provides:',
    choices: ['Server-side verifiable verdicts about device, app, and account integrity (e.g., MEETS_DEVICE_INTEGRITY, MEETS_BASIC_INTEGRITY, MEETS_STRONG_INTEGRITY), signed by Google. Senior framing: it raises the bar for cheaters / tamperers but is not unbreakable; treat verdicts as one signal in a layered defence', 'Encryption for the entire APK', 'Free unlimited backups', 'A device-firewall API'],
    correctIndex: 0,
    explanation: 'Play Integrity is documented in Android Developers. SafetyNet Attestation is being deprecated. OWASP MASTG covers integrity attestation as part of MASVS-RESILIENCE.',
    distractorRationale: { 1: 'It is a verdict service.', 2: 'No backup feature.', 3: 'Not a firewall.' },
    source: { name: 'Android Developers — Play Integrity API', url: 'https://developer.android.com/google/play/integrity' },
  },
];
