// Mobile App pen-testing — senior-level PT questions.
// Authority sources: OWASP MASVS, OWASP MASTG, OWASP Mobile Top 10, Android/iOS official developer docs.

window.QUESTION_BANK.mobile = [
  {
    id: 'mob-001',
    topic: 'mobile',
    subtopic: 'ssl-pinning',
    difficulty: 'senior',
    question: 'You install your Burp CA into the Android device but the app still rejects HTTPS connections. The app uses certificate pinning. Which of the following is the most direct, scriptable bypass on a rooted device?',
    choices: [
      'Re-package the APK without HTTPS support',
      'Use Frida or Objection to hook the pinning verification function in OkHttp / TrustManager and force it to return success at runtime',
      'Disable IPv6 on the device',
      'Switch the device into airplane mode',
    ],
    correctIndex: 1,
    explanation: 'On a rooted device, runtime instrumentation with Frida (or its Objection wrapper) can replace the pinning check in common libraries (OkHttp CertificatePinner, X509TrustManager, network_security_config) so pinning fails open. OWASP MASTG\'s Android testing chapter walks through this exact technique.',
    distractorRationale: {
      0: 'Re-packaging without HTTPS would just break the app and prove nothing about the pinning protection.',
      2: 'IPv6 has nothing to do with TLS certificate validation.',
      3: 'Airplane mode prevents traffic entirely, which is the opposite of what is needed for testing.',
    },
    source: { name: 'OWASP MASTG — Android Network APIs (Testing Network Communication)', url: 'https://mas.owasp.org/MASTG/0x05g-Testing-Network-Communication/' },
  },

  {
    id: 'mob-002',
    topic: 'mobile',
    subtopic: 'storage',
    difficulty: 'senior',
    question: 'On Android, where is the OWASP-recommended location for sensitive secrets (e.g., refresh tokens) so they are protected by hardware-backed keys when available?',
    choices: [
      'In SharedPreferences with `MODE_PRIVATE`',
      'In the Android Keystore (using KeyStore-generated keys with `setUserAuthenticationRequired` and StrongBox where supported), encrypting the secret before persisting it',
      'In a file under /sdcard with chmod 600',
      'In the app\'s SQLite database with Base64 encoding',
    ],
    correctIndex: 1,
    explanation: 'The Android Keystore stores keys in a hardware-backed Trusted Execution Environment / StrongBox where available, so the key material itself never leaves secure storage. OWASP MASVS-STORAGE controls and the Android developer documentation both direct sensitive data through Keystore-backed encryption, not application-level storage.',
    distractorRationale: {
      0: 'MODE_PRIVATE only restricts file permissions; on a rooted device or with backup misconfig the data is still readable in plaintext.',
      2: 'External storage (/sdcard) is world-readable on older Android and chmod metadata is unreliable across vendors.',
      3: 'Base64 is encoding, not encryption — a trivial reversible transformation.',
    },
    source: { name: 'Android Developers — Android Keystore system', url: 'https://developer.android.com/privacy-and-security/keystore' },
  },

  {
    id: 'mob-003',
    topic: 'mobile',
    subtopic: 'ios-keychain',
    difficulty: 'senior',
    question: 'You find an iOS app storing a session token in `UserDefaults`. Why is the senior-level finding to recommend moving it to the iOS Keychain instead?',
    choices: [
      'Keychain values are exposed by default in iTunes backups while UserDefaults are not',
      'UserDefaults is stored in a plist that is included in unencrypted iTunes/Finder backups by default and is readable from a jailbroken device, while the Keychain offers per-item access-control flags (e.g., `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`) and is not in unencrypted backups',
      'UserDefaults requires more memory than the Keychain',
      'Keychain values are stored on Apple\'s servers',
    ],
    correctIndex: 1,
    explanation: 'UserDefaults persists to a plist inside the app sandbox. That plist is included in unencrypted iCloud/iTunes backups and readable on jailbroken devices. The Keychain provides Secure Enclave-backed per-item access-control attributes that bind unlock to passcode/biometrics and exclude items from unencrypted backups. OWASP MASTG iOS chapter is explicit about this.',
    distractorRationale: {
      0: 'This reverses the truth — UserDefaults are exposed in backups, Keychain items are not (when configured correctly).',
      2: 'Memory usage is irrelevant to either choice.',
      3: 'Keychain stores items locally (with optional iCloud Keychain sync if explicitly enabled), not on Apple\'s servers by default.',
    },
    source: { name: 'OWASP MASTG — iOS Data Storage', url: 'https://mas.owasp.org/MASTG/0x06d-Testing-Data-Storage/' },
  },

  {
    id: 'mob-004',
    topic: 'mobile',
    subtopic: 'deeplinks',
    difficulty: 'senior',
    question: 'An Android app declares an intent-filter with `android:exported="true"` and accepts arbitrary URI parameters that are passed straight into a WebView\'s `loadUrl()`. Which class of vulnerability does this most directly enable?',
    choices: [
      'Local file inclusion via SharedPreferences',
      'Universal cross-site scripting / arbitrary URL loading via deep-link redirection (open redirect inside the app), potentially leading to credential theft if the WebView shares cookies with the user session',
      'Buffer overflow in the Java runtime',
      'SQL injection in the Play Store',
    ],
    correctIndex: 1,
    explanation: 'An exported activity that loads attacker-controlled URLs into a WebView is the canonical "deep-link / intent redirection" issue: any other app or browser can launch the activity with an attacker URL, leading to phishing, token theft (because the WebView shares cookies and may have JavaScript bridges) and CSRF-like flows. OWASP Mobile Top 10 (M8 Security Misconfiguration) and MASTG cover this.',
    distractorRationale: {
      0: 'SharedPreferences is unrelated to intent handling.',
      2: 'Buffer overflows are not the relevant class for managed-runtime WebView misuse.',
      3: 'There is no Play Store SQLi at play here; the issue is in-app intent handling.',
    },
    source: { name: 'OWASP MASTG — Android Platform APIs (Intent / Deep Link Handling)', url: 'https://mas.owasp.org/MASTG/0x05h-Testing-Platform-Interaction/' },
  },

  {
    id: 'mob-005',
    topic: 'mobile',
    subtopic: 'root-detection',
    difficulty: 'senior',
    question: 'A banking app refuses to start on a rooted device. From a senior pentester perspective, which framing is most accurate?',
    choices: [
      'Root detection is a robust, primary security control and should always be relied on',
      'Root detection is a defense-in-depth resilience control — it raises the bar but is bypassable with Frida/Magisk Hide/Zygisk and must NOT be the primary defence for sensitive data; the underlying secrets must still be protected by Keystore/Secure Enclave and TLS pinning',
      'Root detection prevents reverse engineering of the APK',
      'Root detection is enforced by Google Play Protect, not the app',
    ],
    correctIndex: 1,
    explanation: 'OWASP MASVS-RESILIENCE classifies anti-tampering, anti-debug and root/jailbreak detection as defence-in-depth — they slow attackers but are not primary controls because runtime instrumentation can defeat them. The senior-level point is that secrets must be protected at the storage and transport layers regardless of runtime resilience.',
    distractorRationale: {
      0: 'Calling root detection a "primary control" is a junior-level misconception; MASVS explicitly places it under resilience.',
      2: 'Reverse engineering of a static APK is unrelated to whether the device is rooted.',
      3: 'Play Protect is a different mechanism (app-store and on-device scanning); it does not implement the in-app root check.',
    },
    source: { name: 'OWASP MASVS — Resilience requirements (MASVS-RESILIENCE)', url: 'https://mas.owasp.org/MASVS/12-MASVS-RESILIENCE/' },
  },

  {
    id: 'mob-006',
    topic: 'mobile',
    subtopic: 'masvs',
    difficulty: 'senior',
    question: 'Which OWASP MASVS control category covers requirements such as "the app does not store sensitive data outside the app container" and "the keyboard cache is not used for sensitive input"?',
    choices: [
      'MASVS-NETWORK',
      'MASVS-STORAGE',
      'MASVS-CRYPTO',
      'MASVS-RESILIENCE',
    ],
    correctIndex: 1,
    explanation: 'MASVS-STORAGE collects controls about how, where, and whether sensitive data is persisted on the device — including keyboard cache, screenshots, app container scope, and clipboard exposure. The official MASVS site lists each category and its controls.',
    distractorRationale: {
      0: 'MASVS-NETWORK covers TLS configuration, pinning and traffic confidentiality.',
      2: 'MASVS-CRYPTO covers correct use of cryptographic primitives, key generation and key management.',
      3: 'MASVS-RESILIENCE covers anti-tampering and anti-instrumentation.',
    },
    source: { name: 'OWASP MASVS — Storage requirements (MASVS-STORAGE)', url: 'https://mas.owasp.org/MASVS/08-MASVS-STORAGE/' },
  },

  {
    id: 'mob-007',
    topic: 'mobile',
    subtopic: 'frida-objection',
    difficulty: 'senior',
    question: 'How does Objection relate to Frida, and which is the right tool when?',
    choices: [
      'Objection is a runtime mobile-exploration toolkit built ON TOP OF Frida — it provides a CLI with pre-canned scripts (SSL pinning bypass, root-detection bypass, dump keychain). Use Frida directly when you need to write custom hooks; use Objection when a common task already has a built-in command',
      'They are competing products with no relation',
      'Frida is for Android only; Objection for iOS only',
      'Objection replaces Frida entirely',
    ],
    correctIndex: 0,
    explanation: 'Objection wraps Frida\'s instrumentation API into a workflow-friendly CLI for common pentest tasks. The Frida and Objection docs say so explicitly. Senior testers know when to drop into Frida\'s JS API for a custom hook vs leveraging an Objection one-liner.',
    distractorRationale: {
      1: 'They are explicitly related; Objection requires Frida.',
      2: 'Both work on Android and iOS.',
      3: 'Objection does not replace Frida — it depends on it.',
    },
    source: { name: 'OWASP MASTG — Tools (Frida, Objection)', url: 'https://mas.owasp.org/MASTG/0x08a-Testing-Tools/' },
  },

  {
    id: 'mob-008',
    topic: 'mobile',
    subtopic: 'apk-rev',
    difficulty: 'senior',
    question: 'You want to inspect an Android APK\'s code and resources statically. Which tool combination is canonical for senior mobile reversing?',
    choices: [
      'apktool (decode resources / smali) and jadx (decompile DEX to readable Java), plus baksmali/smali if you need to patch and rebuild',
      'Wireshark + Burp',
      'Mimikatz + BloodHound',
      'Nessus + Nikto',
    ],
    correctIndex: 0,
    explanation: 'apktool unpacks the APK into smali and resources you can inspect/patch and rebuild. jadx decompiles DEX bytecode into readable Java with a useful UI for navigation. Together they cover most of static APK reverse engineering. OWASP MASTG recommends both as primary tools.',
    distractorRationale: {
      1: 'Network capture/proxy tools are for traffic, not APK analysis.',
      2: 'AD-attack tools are unrelated.',
      3: 'Network vulnerability scanners are unrelated.',
    },
    source: { name: 'OWASP MASTG — Android Static Analysis (Tools)', url: 'https://mas.owasp.org/MASTG/0x05a-Tampering-and-Reverse-Engineering-Android/' },
  },

  {
    id: 'mob-009',
    topic: 'mobile',
    subtopic: 'webview-bridge',
    difficulty: 'senior',
    question: 'An Android app exposes a Java method to JavaScript via `WebView.addJavascriptInterface`. The WebView loads partially attacker-influenced URLs. Why is this a critical finding pre-API-17 and still a senior-level review item afterwards?',
    choices: [
      'Pre-API-17 (Android 4.2), addJavascriptInterface exposed Reflection so JS could load any class and execute arbitrary code on the device. From API-17 onward, only @JavascriptInterface-annotated methods are exposed; the senior risk is that those methods themselves can leak sensitive functionality (exfiltrate tokens, trigger payments) to compromised content.',
      'It blocks all JavaScript in the WebView',
      'It enforces Content Security Policy',
      'It encrypts the WebView traffic with TPM',
    ],
    correctIndex: 0,
    explanation: 'The pre-Android-4.2 reflection bug enabled trivial RCE. After the fix, the API still exposes only annotated methods, but the senior risk is that those methods are often "trusted bridges" that perform sensitive actions and can be abused if the WebView is fed attacker content. OWASP MASTG covers both eras.',
    distractorRationale: {
      1: 'It enables JS-to-Java interop, not blocks it.',
      2: 'CSP is HTTP-header enforced; this API does not enforce it.',
      3: 'There is no TPM-level encryption tied to this API.',
    },
    source: { name: 'OWASP MASTG — Android WebViews', url: 'https://mas.owasp.org/MASTG/0x05h-Testing-Platform-Interaction/' },
  },

  {
    id: 'mob-010',
    topic: 'mobile',
    subtopic: 'logcat',
    difficulty: 'senior',
    question: 'On Android API < 24, why was sensitive data logged via `Log.d` a serious finding, and what changed in modern Android?',
    choices: [
      'Pre-API-24, any app with `READ_LOGS` could read every other app\'s log output. Since API-24, logcat is restricted per-app, but the finding remains relevant on rooted devices or when the app exposes logs via debug builds — sensitive data should never be logged regardless',
      'logcat encrypts data with the device passcode',
      'logcat is unique to iOS',
      'logcat only stores network packets',
    ],
    correctIndex: 0,
    explanation: 'Older Android exposed logcat globally to apps holding READ_LOGS, leaking tokens that developers logged for debugging. Modern Android isolates logs per app, but rooted devices and accidentally enabled debug builds re-expose them. OWASP MASTG\'s storage chapter calls this out.',
    distractorRationale: {
      1: 'logcat output is not encrypted.',
      2: 'logcat is Android-specific.',
      3: 'It logs all messages, not just packets.',
    },
    source: { name: 'OWASP MASTG — Android Data Storage (logging)', url: 'https://mas.owasp.org/MASTG/0x05d-Testing-Data-Storage/' },
  },

  {
    id: 'mob-011',
    topic: 'mobile',
    subtopic: 'exported-components',
    difficulty: 'senior',
    question: 'In an Android Manifest you find an Activity with `android:exported="true"` and no `permission`. What is the senior-level finding rationale?',
    choices: [
      'Any other app on the device can launch this Activity and pass arbitrary intents/extras to it. If the Activity performs privileged actions (financial, IPC bridges), this is exploitable cross-app. Recommendation: set `exported="false"` unless the component is intentionally part of the app\'s public surface, and protect anything intentional with a signature-level permission',
      'It is required for all activities to function',
      'It enables Doze mode',
      'It improves battery life',
    ],
    correctIndex: 0,
    explanation: 'Exported activities, services, providers, and receivers form the cross-app attack surface. Misconfigured exports are a top OWASP MASTG finding — the relevant Android docs explain that exported defaults changed in API-31, but legacy apps still ship loose exports.',
    distractorRationale: {
      1: 'Most activities can be `exported="false"` and still work in-app.',
      2: 'Doze is a power-management feature, unrelated.',
      3: 'Battery is unrelated.',
    },
    source: { name: 'Android Developers — Activity element (android:exported)', url: 'https://developer.android.com/guide/topics/manifest/activity-element' },
  },

  {
    id: 'mob-012',
    topic: 'mobile',
    subtopic: 'obfuscation',
    difficulty: 'senior',
    question: 'How should a senior pentester treat findings about ProGuard / R8 obfuscation in Android apps?',
    choices: [
      'Obfuscation is a defence-in-depth control under MASVS-RESILIENCE — it slows reverse engineering but does not provide confidentiality. Critical findings (hardcoded keys, business-logic flaws) are not "fixed" by adding obfuscation; the underlying issues must be addressed independently',
      'Obfuscation should always be the primary defence',
      'Obfuscation is identical to AES encryption',
      'Obfuscation is mandated by the iOS App Store',
    ],
    correctIndex: 0,
    explanation: 'OWASP MASVS-RESILIENCE classifies obfuscation as defence in depth. Senior reports are explicit about the distinction: a hardcoded API key is still a hardcoded API key after R8 — obfuscation just slows the attacker. Treating it as primary security is a junior framing.',
    distractorRationale: {
      1: 'Obfuscation is supplementary, not primary.',
      2: 'It is not encryption.',
      3: 'iOS App Store does not mandate ProGuard (which is Android-only).',
    },
    source: { name: 'OWASP MASVS — Resilience (V8 / MASVS-RESILIENCE)', url: 'https://mas.owasp.org/MASVS/12-MASVS-RESILIENCE/' },
  },

  {
    id: 'mob-013',
    topic: 'mobile',
    subtopic: 'ios-ats',
    difficulty: 'senior',
    question: 'You find an iOS app with `NSAllowsArbitraryLoads = true` in its Info.plist. What does this disable, and why is it a finding?',
    choices: [
      'It disables Apple\'s App Transport Security (ATS), which by default enforces TLS 1.2+, forward secrecy, and certificate validation for outbound HTTPS connections. Disabling it sitewide allows plaintext HTTP and weak TLS — a regression from a platform-enforced control',
      'It disables Bluetooth',
      'It disables push notifications',
      'It disables the camera',
    ],
    correctIndex: 0,
    explanation: 'ATS is iOS\'s outbound HTTP hardening. NSAllowsArbitraryLoads bypasses it globally; per-domain exceptions (NSExceptionDomains) are the correct narrow-scope alternative when justified. Apple\'s ATS docs and OWASP MASTG iOS network testing chapter describe this.',
    distractorRationale: {
      1: 'ATS does not control Bluetooth.',
      2: 'It is unrelated to push notifications.',
      3: 'It does not disable the camera.',
    },
    source: { name: 'Apple Developer — App Transport Security (NSAppTransportSecurity)', url: 'https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity' },
  },

  {
    id: 'mob-014',
    topic: 'mobile',
    subtopic: 'biometrics',
    difficulty: 'senior',
    question: 'On Android, why is `BiometricPrompt` (with CryptoObject) preferred over implementing your own biometric check on top of a stored boolean "isUnlocked"?',
    choices: [
      'BiometricPrompt + CryptoObject ties biometric authentication to a Keystore key that requires user authentication for unlock. The cryptographic key is unlocked only by a successful biometric — so an attacker cannot bypass the check by toggling a boolean in the app\'s state. It also delegates the comparison to the OS / hardware, not the app',
      'It animates the prompt nicely',
      'It is required by Google for adverts',
      'It speeds up the app',
    ],
    correctIndex: 0,
    explanation: 'A boolean "isUnlocked" can be flipped at runtime via Frida. BiometricPrompt with a CryptoObject binds the user\'s biometric to a Keystore key whose use is gated by `setUserAuthenticationRequired`, so bypassing the boolean does not unlock the key. Android\'s biometric docs and OWASP MASTG describe this binding.',
    distractorRationale: {
      1: 'UI polish is not the security argument.',
      2: 'Biometric prompts are not advert-related.',
      3: 'Performance is not the rationale.',
    },
    source: { name: 'Android Developers — Biometric authentication with CryptoObject', url: 'https://developer.android.com/training/sign-in/biometric-auth' },
  },

  {
    id: 'mob-015',
    topic: 'mobile',
    subtopic: 'burp-android-ca',
    difficulty: 'senior',
    question: 'You install Burp\'s CA on an Android 7+ device as a USER certificate. The app still does not trust your CA. Why, and what is the senior-level workaround?',
    choices: [
      'Since Android 7 (API-24), apps by default only trust SYSTEM CAs, not user CAs. To intercept, install Burp\'s CA into the system trust store on a rooted device (or via Magisk module / `mv` to /system/etc/security/cacerts), or modify the app\'s `network_security_config.xml` if you have repackaging rights',
      'Android always trusts user CAs',
      'You must use Wireshark instead of Burp',
      'You must downgrade Burp to a 1.x version',
    ],
    correctIndex: 0,
    explanation: 'Android 7 changed the default trust store: apps only trust system CAs unless they opt in via network_security_config to user CAs. Senior testers move the CA into /system/etc/security/cacerts (root required) or repackage with a custom config. Android\'s network security configuration docs describe the change.',
    distractorRationale: {
      1: 'It does not — that is the change introduced in API-24.',
      2: 'Wireshark passively sniffs but does not break TLS.',
      3: 'Burp version is not the issue.',
    },
    source: { name: 'Android Developers — Network security configuration', url: 'https://developer.android.com/privacy-and-security/security-config' },
  },

  {
    id: 'mob-016',
    topic: 'mobile',
    subtopic: 'apk-signing',
    difficulty: 'senior',
    question: 'Why does APK Signature Scheme v2/v3 supersede v1, and what is the security implication of an APK signed only with v1?',
    choices: [
      'v1 (JAR signing) signs files individually, leaving room for tampering attacks like Janus (CVE-2017-13156) on certain Android versions; v2/v3 sign the whole APK\'s integrity block atomically. Apps signed only with v1 may be tamperable on legacy targets and are a finding to flag',
      'v1 is faster than v2',
      'v2 is mandatory for the iOS App Store',
      'v3 disables Google Play Services',
    ],
    correctIndex: 0,
    explanation: 'JAR signing (v1) signed individual entries with manifests, leaving signature-validation gaps that Janus exploited. APK Signature Scheme v2/v3 covers the entire APK with stronger integrity. Android Developers documents the timeline; OWASP MASTG flags v1-only signing as a tamper-resistance gap.',
    distractorRationale: {
      1: 'Speed is not the security argument.',
      2: 'iOS does not use APK signing.',
      3: 'v3 does not disable Google Play.',
    },
    source: { name: 'Android Developers — APK Signature Scheme v2 / v3', url: 'https://source.android.com/docs/security/features/apksigning/v2' },
  },

  {
    id: 'mob-017',
    topic: 'mobile',
    subtopic: 'mobile-top10',
    difficulty: 'senior',
    question: 'Which OWASP Mobile Top 10 (2024) category covers "the app stores authentication tokens insecurely or transmits them poorly"?',
    choices: [
      'M1 — Improper Credential Usage',
      'M3 — Insecure Authentication / Authorization',
      'M9 — Insecure Data Storage',
      'M10 — Insufficient Cryptography',
    ],
    correctIndex: 0,
    explanation: 'OWASP Mobile Top 10 2024 names M1 "Improper Credential Usage" specifically about credentials/tokens — handling, storage, transmission, hardcoded credentials. The OWASP project page lists all ten categories and their definitions.',
    distractorRationale: {
      1: 'M3 in 2024 is broader auth/authorization, not specifically credential mishandling.',
      2: 'Insecure Data Storage is M9 in 2024 and is broader (PII, files, etc.).',
      3: 'M10 covers cryptography weaknesses, not credential storage per se.',
    },
    source: { name: 'OWASP Mobile Top 10 (2024)', url: 'https://owasp.org/www-project-mobile-top-10/' },
  },

  {
    id: 'mob-018',
    topic: 'mobile',
    subtopic: 'reverse-ios',
    difficulty: 'senior',
    question: 'For dynamic instrumentation of an iOS app on a non-jailbroken device, which approach is most viable for a senior tester?',
    choices: [
      'Use a test build with Frida Gadget injected via re-signing (e.g., with Sideloadly or fastlane), or test on a jailbroken device. Apple\'s code-signing model prevents arbitrary instrumentation on stock devices',
      'Run Mimikatz on the iPhone',
      'Decompile the IPA to .NET',
      'Modify the kernel via TFTP',
    ],
    correctIndex: 0,
    explanation: 'iOS\'s code-signing model means runtime instrumentation generally requires either a developer-signed build with Frida Gadget bundled, or a jailbroken device. OWASP MASTG\'s iOS chapter and Frida\'s docs cover both paths and the trade-offs.',
    distractorRationale: {
      1: 'Mimikatz is a Windows credential tool.',
      2: 'iOS apps are not .NET binaries.',
      3: 'TFTP-kernel-mod is not how iOS jailbreaks work.',
    },
    source: { name: 'OWASP MASTG — iOS Tampering and Reverse Engineering', url: 'https://mas.owasp.org/MASTG/0x06b-Tampering-and-Reverse-Engineering-iOS/' },
  },

  {
    id: 'mob-019',
    topic: 'mobile',
    subtopic: 'mobsf',
    difficulty: 'senior',
    question: 'MobSF (Mobile Security Framework) is best described as which kind of tool, and what is the senior caveat about using it?',
    choices: [
      'An open-source automated mobile static + dynamic analysis platform that produces a baseline report. Caveat: automated tools miss business-logic flaws and have false positives — senior reports treat MobSF output as a starting point that must be triaged manually, not as the engagement deliverable',
      'A network packet sniffer',
      'A jailbreak tool for iOS',
      'A firmware extractor for routers',
    ],
    correctIndex: 0,
    explanation: 'MobSF automates many static and basic dynamic checks (manifest, permissions, hardcoded patterns, basic Frida hooks). It accelerates baseline coverage, but every senior pentester knows to triage findings and add manual analysis (auth flows, API logic, key handling). OWASP MASTG references it as one of several tools.',
    distractorRationale: {
      1: 'Wireshark/tcpdump are sniffers; not MobSF.',
      2: 'MobSF does not jailbreak.',
      3: 'It is not a router-firmware tool.',
    },
    source: { name: 'OWASP MASTG — Tools (MobSF)', url: 'https://mas.owasp.org/MASTG/0x08a-Testing-Tools/' },
  },

  {
    id: 'mob-020',
    topic: 'mobile',
    subtopic: 'mobile-api',
    difficulty: 'senior',
    question: 'Why do experienced mobile pentesters say "most mobile findings are actually API findings"?',
    choices: [
      'The mobile client typically delegates auth, business logic, and data access to a back-end API. The phone itself is just a UI; the bulk of impactful findings — IDOR, broken object-level auth, missing rate limit, mass assignment — live on the API. Senior methodology pivots quickly from on-device tests to proxy-the-API, OWASP API Security Top 10',
      'Phones never have local logic',
      'Mobile apps cannot store data locally',
      'iOS apps run on the server',
    ],
    correctIndex: 0,
    explanation: 'OWASP MASTG and the OWASP API Security Top 10 are explicit that mobile-client testing includes thorough API testing. The client is one attack surface, but the high-impact findings (data exposure, BOLA, mass assignment) almost always sit on the API. Senior reports typically have an API section that dwarfs the on-device section.',
    distractorRationale: {
      1: 'They do; but the most impactful logic is server-side.',
      2: 'They can; the point is server-side logic dominates impact.',
      3: 'iOS apps run on the device.',
    },
    source: { name: 'OWASP API Security Top 10', url: 'https://owasp.org/API-Security/editions/2023/en/0x00-header/' },
  },
];
