// Network pen-testing — senior-level PT questions.
// Authority sources: Nmap official docs, Microsoft Learn, MITRE ATT&CK, NIST SP 800-115, vendor docs.

window.QUESTION_BANK.network = [
  {
    id: 'net-001',
    topic: 'network',
    subtopic: 'nmap',
    difficulty: 'senior',
    question: 'What is the precise difference between `nmap -sS` (SYN scan) and `nmap -sT` (TCP connect scan), and why does it matter operationally?',
    choices: [
      '`-sS` requires raw-socket privileges (root/Administrator) but never completes the TCP handshake, making it stealthier and faster; `-sT` uses the OS connect() syscall, completes the handshake, and is logged by application-layer services',
      '`-sS` scans only HTTPS ports while `-sT` scans only HTTP ports',
      '`-sS` is UDP-based; `-sT` is TCP-based',
      '`-sS` is for IPv6; `-sT` is for IPv4',
    ],
    correctIndex: 0,
    explanation: 'SYN scan crafts raw packets and never sends the final ACK, so the connection never appears to userspace and many app-layer logs miss it; it requires raw-socket privileges. TCP connect scan uses the OS connect() syscall, completes the 3-way handshake, and is therefore visible to application logs. Nmap\'s official scan-types reference is explicit on this difference.',
    distractorRationale: {
      1: 'Both scans are protocol-agnostic at the port level — `-p` controls which ports are checked, not the scan type.',
      2: 'Both are TCP scans by definition; UDP scanning is `-sU`.',
      3: 'IP version is controlled by `-6`, not by the scan type.',
    },
    source: { name: 'Nmap Reference Guide — Port Scanning Techniques', url: 'https://nmap.org/book/man-port-scanning-techniques.html' },
  },

  {
    id: 'net-002',
    topic: 'network',
    subtopic: 'llmnr-poisoning',
    difficulty: 'senior',
    question: 'You run Responder on an internal segment and start collecting NetNTLMv2 hashes. Which Microsoft-recommended setting most directly disables the underlying name-resolution channel Responder abuses?',
    choices: [
      'Disabling SMBv1',
      'Disabling LLMNR (via "Turn off multicast name resolution" Group Policy) AND disabling NetBIOS over TCP/IP',
      'Enforcing NTLMv2 over NTLMv1',
      'Enabling Windows Defender Credential Guard',
    ],
    correctIndex: 1,
    explanation: 'Responder abuses LLMNR and NBT-NS broadcast/multicast name-resolution to answer failed lookups and coerce victims to authenticate to it. The mitigation is to disable both name-resolution channels by Group Policy. Microsoft\'s NTLM relay / coercion guidance covers this. MITRE catalogues the abuse as T1557.001.',
    distractorRationale: {
      0: 'Disabling SMBv1 is good hygiene but unrelated to broadcast name resolution.',
      2: 'NTLMv2 vs NTLMv1 is about cryptographic strength, not about whether Responder receives the hash in the first place.',
      3: 'Credential Guard protects in-memory credentials; it does not stop a victim sending NTLM auth to Responder.',
    },
    source: { name: 'MITRE ATT&CK T1557.001 — Adversary-in-the-Middle: LLMNR/NBT-NS Poisoning and SMB Relay', url: 'https://attack.mitre.org/techniques/T1557/001/' },
  },

  {
    id: 'net-003',
    topic: 'network',
    subtopic: 'pivoting',
    difficulty: 'senior',
    question: 'You have RCE on a perimeter host with no direct internet egress on internal subnets. Which technique gives you the most flexible way to reach internal hosts from your attacker box without dropping additional binaries?',
    choices: [
      'Run an ARP scan from the perimeter host',
      'Use SSH dynamic port forwarding (`ssh -D 1080`) and proxychains, or set up an SSH reverse SOCKS tunnel and route tools through it',
      'Switch the perimeter host\'s NIC into promiscuous mode',
      'Reboot the perimeter host into safe mode',
    ],
    correctIndex: 1,
    explanation: 'A SOCKS proxy via SSH (-D for forward, -R + sshuttle/Chisel for reverse) lets your local Nmap, browser, etc. tunnel through the compromised host with minimal artefacts and no special tooling on the target beyond the SSH client. NIST SP 800-115 and OffSec materials describe pivoting via SOCKS as the standard pattern.',
    distractorRationale: {
      0: 'ARP scans only enumerate the local L2 segment from that host; they do not let you reach internal subnets from your laptop.',
      2: 'Promiscuous mode helps with passive sniffing on the same segment, not with reaching arbitrary internal hosts.',
      3: 'Safe mode would drop services and detection alerts and accomplishes nothing for pivoting.',
    },
    source: { name: 'NIST SP 800-115 — Technical Guide to Information Security Testing and Assessment', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-004',
    topic: 'network',
    subtopic: 'rdp',
    difficulty: 'senior',
    question: 'Network Level Authentication (NLA) is enabled on an RDP service. What is the security impact compared to RDP without NLA?',
    choices: [
      'NLA encrypts the post-logon RDP session more strongly',
      'NLA requires the client to authenticate before a session is established, mitigating pre-auth RCE classes (e.g., BlueKeep CVE-2019-0708) and reducing exposed attack surface',
      'NLA disables clipboard sharing',
      'NLA forces the use of smartcards',
    ],
    correctIndex: 1,
    explanation: 'NLA uses CredSSP to require credentials before the server creates a session. This drastically reduces pre-auth attack surface — vulnerabilities like BlueKeep and many DoS vectors require interaction before authentication, which NLA prevents. Microsoft\'s RDP security guidance is explicit on this.',
    distractorRationale: {
      0: 'NLA is about pre-session authentication, not the bulk encryption strength of the data channel.',
      2: 'Clipboard redirection is a separate device-redirection setting.',
      3: 'NLA does not require smartcards; CredSSP can use NTLM, Kerberos, or smartcards.',
    },
    source: { name: 'Microsoft Learn — Configure Network Level Authentication for RDP', url: 'https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access' },
  },

  {
    id: 'net-005',
    topic: 'network',
    subtopic: 'ot-ics',
    difficulty: 'senior',
    question: 'You are scoping an internal pentest at a dairy/food factory. The client confirms there are PLCs and SCADA workstations on a separate VLAN. What is the most senior-appropriate approach to that VLAN?',
    choices: [
      'Run an aggressive Nmap scan (`-T4 -A -p-`) to maximise coverage',
      'Treat the OT segment as out-of-scope unless explicitly authorised; if authorised, use passive techniques and avoid full-port / OS-detection scans because legacy ICS protocols can crash on probes',
      'Send Modbus function-code 8 (Diagnostics: restart communication) to verify availability',
      'Replay captured EtherNet/IP packets at line rate',
    ],
    correctIndex: 1,
    explanation: 'CISA, ISA/IEC 62443 and NIST SP 800-82 all stress that legacy ICS devices were not designed to handle modern scan traffic; even a benign Nmap can crash a PLC and halt production. The senior-appropriate posture is explicit scope confirmation, passive observation, and only authorised, conservative active testing.',
    distractorRationale: {
      0: 'A `-T4 -A -p-` aggressive scan against ICS gear is exactly the action that has historically caused outages — never the right move.',
      2: 'Function code 8 sub-codes can stop the device or clear counters; running it without explicit authorisation is irresponsible.',
      3: 'Replaying capture traffic on an OT network is uncontrolled and can put workers in physical danger.',
    },
    source: { name: 'NIST SP 800-82 Rev. 3 — Guide to Operational Technology Security', url: 'https://csrc.nist.gov/publications/detail/sp/800-82/rev-3/final' },
  },

  {
    id: 'net-006',
    topic: 'network',
    subtopic: 'mitm6',
    difficulty: 'senior',
    question: 'mitm6 abuses default Windows behaviour to perform an attack. Which protocol does it primarily target, and why is it effective by default?',
    choices: [
      'IPv4 DHCP — Windows requests addresses on every boot',
      'IPv6 DHCPv6 — Windows is configured to prefer IPv6 even on networks that have not formally deployed it, so a rogue DHCPv6 server can set itself as the DNS server and intercept name resolution',
      'ARP — Windows broadcasts MAC requests',
      'NetBIOS over TCP/IP only',
    ],
    correctIndex: 1,
    explanation: 'Modern Windows enables IPv6 by default and prefers it over IPv4. mitm6 listens for DHCPv6 solicits and replies with a rogue configuration pointing DNS at the attacker, enabling NTLM coercion against WPAD/SMB. Fox-IT\'s mitm6 release post and Microsoft\'s IPv6 hardening guidance both describe the mechanism and the mitigation (disable IPv6 if unused, or apply the registry/policy controls).',
    distractorRationale: {
      0: 'mitm6 is specifically an IPv6 attack; IPv4 DHCP rogue servers are a separate class.',
      2: 'ARP poisoning is L2 and unrelated to mitm6.',
      3: 'NBT-NS poisoning (Responder) is a different protocol and a different tool.',
    },
    source: { name: 'Fox-IT / Dirk-jan Mollema — mitm6 release post', url: 'https://blog.fox-it.com/2018/01/11/mitm6-compromising-ipv4-networks-via-ipv6/' },
  },

  {
    id: 'net-007',
    topic: 'network',
    subtopic: 'snmp',
    difficulty: 'senior',
    question: 'Why is SNMP v1 / v2c with the community string `public` a high-value finding in an internal pentest?',
    choices: [
      'SNMP v1/v2c uses cleartext community strings as the only authentication. With `public` (read-only) you can enumerate device config, ARP tables, routing, running processes; with `private` (read-write) you can modify config, exfiltrate the running-config (Cisco), or reroute traffic',
      'SNMP encrypts traffic with AES-256 by default',
      'SNMP requires Kerberos authentication',
      'SNMP is only available over IPv6',
    ],
    correctIndex: 0,
    explanation: 'SNMP v1/v2c sends the community string in the clear and provides no real authentication. snmpwalk with `public` enumerates a wealth of OIDs; with `private` an attacker can grab Cisco running-configs over TFTP. SNMP v3 adds authentication and privacy. NIST and vendor docs describe the exposure.',
    distractorRationale: {
      1: 'Only SNMPv3 supports privacy (encryption); v1/v2c do not.',
      2: 'SNMP does not use Kerberos.',
      3: 'SNMP works on both IPv4 and IPv6.',
    },
    source: { name: 'NIST SP 800-115 — Information security testing (services like SNMP)', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-008',
    topic: 'network',
    subtopic: 'smb-null-session',
    difficulty: 'senior',
    question: 'Against a legacy Windows server you are able to connect to `\\\\target\\IPC$` with a NULL session. What does this typically let you enumerate and which Microsoft control disables it?',
    choices: [
      'Domain users, groups, password policy, SMB shares, etc., via MS-RPC over IPC$. The control is the `RestrictAnonymous`/`RestrictAnonymousSAM` registry settings (and modern policies that disable anonymous SAM/SAM-named-pipes lookups).',
      'Internet routing tables — disabled by changing TTL',
      'Active Directory DNS records — disabled by disabling DNS dynamic updates',
      'RDP sessions — disabled by setting NLA',
    ],
    correctIndex: 0,
    explanation: 'Anonymous (NULL) SMB connections to IPC$ historically allowed RPC enumeration of users, groups, domain policy, shares, etc. (LSARPC, SAMR). Microsoft\'s `RestrictAnonymous` and `RestrictAnonymousSAM` settings (and Network Access policies in modern Windows) prevent this. NetExec / rpcclient / enum4linux remain the go-to tools.',
    distractorRationale: {
      1: 'Routing tables are not exposed via IPC$.',
      2: 'DNS records are not exposed via IPC$.',
      3: 'RDP sessions are not enumerated via IPC$.',
    },
    source: { name: 'Microsoft Learn — Network access: Do not allow anonymous enumeration of SAM accounts', url: 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-anonymous-enumeration-of-sam-accounts' },
  },

  {
    id: 'net-009',
    topic: 'network',
    subtopic: 'nfs',
    difficulty: 'senior',
    question: 'An NFSv3 export is configured with `no_root_squash`. Why is this dangerous?',
    choices: [
      'A client mounting the share can write files as UID 0 (root) of the server. Combined with mounting an OS partition, the attacker can write into authorized_keys, /etc/passwd, or set SUID binaries to gain root on the server',
      'It encrypts traffic too strongly',
      'It blocks all writes',
      'It enables IPv6 only',
    ],
    correctIndex: 0,
    explanation: 'By default NFS "squashes" the remote root to the unprivileged `nobody` user. `no_root_squash` disables that, so a client root writes as server root. Trivial to escalate via SSH key drop, /etc/passwd edit, or a SUID binary. Linux man-exports and CIS benchmarks both flag this.',
    distractorRationale: {
      1: 'NFS does not encrypt by default — that is a separate concern (Kerberos NFS).',
      2: 'It does not block writes; the opposite.',
      3: 'IPv6 is unrelated.',
    },
    source: { name: 'Linux exports(5) man page — no_root_squash', url: 'https://man7.org/linux/man-pages/man5/exports.5.html' },
  },

  {
    id: 'net-010',
    topic: 'network',
    subtopic: 'ssh',
    difficulty: 'senior',
    question: 'An SSH server allows password authentication AND has no fail2ban / rate limit. From a senior pentester perspective, beyond running a brute-force, what configuration finding is the more pointed report item?',
    choices: [
      'The server should disable password authentication entirely (`PasswordAuthentication no`), enforce key-based auth, restrict via Match groups, and disable root login (`PermitRootLogin no`); rate-limiting alone treats the symptom not the root cause',
      'The server should run on port 23',
      'The server should disable AES-256',
      'The server should expose Telnet as a fallback',
    ],
    correctIndex: 0,
    explanation: 'Hardening SSH means moving away from credentials that can be brute-forced at all: keys + 2FA, no root login, restrict source networks, and disable weak algorithms. CIS benchmarks for Ubuntu/RHEL document the exact set. Senior reports phrase the finding as a hardening gap, not just "missing rate limit".',
    distractorRationale: {
      1: 'Port 23 is Telnet — significantly worse.',
      2: 'AES-256 is fine; weak ciphers/algos should be disabled, not strong ones.',
      3: 'Telnet fallback is the opposite of secure.',
    },
    source: { name: 'CIS Benchmarks (Ubuntu/RHEL) — SSH hardening', url: 'https://www.cisecurity.org/cis-benchmarks' },
  },

  {
    id: 'net-011',
    topic: 'network',
    subtopic: 'dns-zone-transfer',
    difficulty: 'senior',
    question: 'You run `dig AXFR @ns1.target.tld target.tld` and the server returns the full zone. Why is this a finding even though no exploitation is needed?',
    choices: [
      'Unrestricted zone transfers leak internal hostnames, IP layout, mail and service records — high-value reconnaissance for further attack. The fix is to restrict AXFR to authorised secondaries via `allow-transfer` (BIND) or equivalent',
      'AXFR enables RCE on the resolver',
      'AXFR is encrypted by default',
      'AXFR transfers the kernel image',
    ],
    correctIndex: 0,
    explanation: 'AXFR is the legitimate zone-transfer mechanism for replicating zones to secondaries. Misconfigured servers replying to anyone leak the entire DNS namespace — a recon goldmine. BIND and similar servers allow per-source ACLs. NIST SP 800-81 documents secure DNS deployment.',
    distractorRationale: {
      1: 'AXFR does not provide RCE.',
      2: 'AXFR is plaintext over TCP/53; not encrypted unless transport is layered.',
      3: 'AXFR is a DNS protocol exchange, nothing to do with kernels.',
    },
    source: { name: 'NIST SP 800-81-2 — Secure Domain Name System (DNS) Deployment Guide', url: 'https://csrc.nist.gov/publications/detail/sp/800-81/2/final' },
  },

  {
    id: 'net-012',
    topic: 'network',
    subtopic: 'arp-spoofing',
    difficulty: 'senior',
    question: 'You are on the same VLAN as a victim. Which technique places you in-path between victim and gateway at L2, and what makes it succeed by default?',
    choices: [
      'ARP spoofing: send unsolicited ARP replies mapping the gateway IP to your MAC; switches forward L2 frames based on MAC, hosts cache ARP without authentication, so traffic is rerouted. Mitigations: Dynamic ARP Inspection (DAI) on managed switches, plus DHCP snooping',
      'BGP hijacking',
      'TCP RST injection',
      'TLS downgrade',
    ],
    correctIndex: 0,
    explanation: 'ARP has no authentication. Tools like arpspoof, bettercap, and Ettercap implement the standard mitm. Cisco DAI / DHCP snooping detects mismatches between L2/L3. Vendor docs and OWASP guidance describe the technique and defences.',
    distractorRationale: {
      1: 'BGP is at the routing layer, not L2.',
      2: 'TCP RST injection is a transport-layer attack against an existing flow.',
      3: 'TLS downgrade attacks the application layer.',
    },
    source: { name: 'Cisco — Configuring Dynamic ARP Inspection', url: 'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3850/software/release/16-1/configuration_guide/sec/b_161_sec_3850_cg/configuring_dynamic_arp_inspection.html' },
  },

  {
    id: 'net-013',
    topic: 'network',
    subtopic: 'vlan-hopping',
    difficulty: 'senior',
    question: 'VLAN hopping via "double tagging" requires which switch misconfiguration to be effective?',
    choices: [
      'The attacker\'s port being on the SAME VLAN as the trunk\'s native VLAN. The attacker sends a frame with two 802.1Q tags; the first switch strips the outer (matching the native VLAN) and forwards the frame to the trunk, where the second switch reads the inner tag and delivers to the target VLAN. The fix is to never use the native VLAN for user traffic and to pin a dedicated unused VLAN as native',
      'IPv6 enabled on the trunk',
      'BGP enabled in the LAN',
      'Spanning Tree Protocol disabled',
    ],
    correctIndex: 0,
    explanation: 'Double-tagging exploits the native-VLAN behaviour of 802.1Q trunks. The defence is to set the native VLAN of every trunk to a dedicated, unused VLAN and to never put user ports on the native VLAN. Cisco\'s "Securing Layer 2" guidance is the canonical reference.',
    distractorRationale: {
      1: 'IPv6 is not part of the technique.',
      2: 'BGP is L3 routing.',
      3: 'STP is loop prevention; not the hopping mechanism.',
    },
    source: { name: 'Cisco — VLAN Security White Paper / Layer 2 attacks', url: 'https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-6500-series-switches/white_paper_c11_605972.html' },
  },

  {
    id: 'net-014',
    topic: 'network',
    subtopic: 'wpad',
    difficulty: 'senior',
    question: 'WPAD (Web Proxy Auto-Discovery) is famously abused for credential theft. What is the canonical chain?',
    choices: [
      'A client searches for `wpad.<domain>` via DHCP, DNS, then LLMNR/NBT-NS. Responder answers the broadcast lookup, the client fetches a wpad.dat from the attacker, sets a proxy, and then sends Web traffic with NTLM auth to the attacker — yielding NetNTLMv2 hashes for offline cracking or SMB-relay',
      'WPAD launches malware via WSUS',
      'WPAD requires IPv6 multicast',
      'WPAD is only used by Linux clients',
    ],
    correctIndex: 0,
    explanation: 'WPAD\'s discovery process falls back to broadcast name resolution, which Responder can answer authoritatively on segments where LLMNR/NBT-NS is permitted. The compromised proxy then captures NTLM auth on subsequent web traffic. Microsoft documents WPAD risks; mitigations include disabling WPAD discovery and the LLMNR/NBT-NS controls.',
    distractorRationale: {
      1: 'WSUS is a separate Windows-update service.',
      2: 'WPAD does not require IPv6.',
      3: 'WPAD is a Windows-default behaviour.',
    },
    source: { name: 'Microsoft Learn — How the Web Proxy Auto-Discovery Protocol Works', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/automatic-detection-settings-internet-explorer' },
  },

  {
    id: 'net-015',
    topic: 'network',
    subtopic: 'tls',
    difficulty: 'senior',
    question: 'A server supports TLS 1.0 and offers `TLS_RSA_WITH_AES_128_CBC_SHA`. Beyond "deprecated", what specific risks does the senior pentester cite?',
    choices: [
      'TLS 1.0 is vulnerable to BEAST (CBC IV reuse) and lacks modern cipher AEAD support; RSA-key-exchange ciphers (no PFS) mean a future leak of the server\'s private key allows decryption of all past sessions captured by a passive observer. Recommend TLS 1.2/1.3 only, with PFS (ECDHE) and AEAD (AES-GCM, ChaCha20-Poly1305)',
      'TLS 1.0 only works on UDP',
      'TLS 1.0 disables HTTP/2',
      'TLS 1.0 enables zero-trust by default',
    ],
    correctIndex: 0,
    explanation: 'TLS 1.0/1.1 are formally deprecated (RFC 8996). The senior framing addresses why: BEAST/POODLE-class CBC issues, no AEAD, RSA key-exchange ciphers without PFS expose past traffic to retroactive decryption. NIST SP 800-52r2 and Mozilla\'s TLS guidelines codify the recommended config.',
    distractorRationale: {
      1: 'TLS is over TCP (or QUIC); UDP-only is wrong.',
      2: 'HTTP/2 ALPN normally requires TLS 1.2+, but TLS 1.0 does not "disable" HTTP/2 as such.',
      3: 'Zero-trust is an architectural posture, not a TLS feature.',
    },
    source: { name: 'NIST SP 800-52 Rev. 2 — Guidelines for the Selection, Configuration, and Use of TLS Implementations', url: 'https://csrc.nist.gov/publications/detail/sp/800-52/rev-2/final' },
  },

  {
    id: 'net-016',
    topic: 'network',
    subtopic: 'wifi',
    difficulty: 'senior',
    question: 'WPA2-PSK 4-way handshake capture allows offline brute-force of the PSK. What additional WPA2/3 control most directly mitigates offline cracking, and why?',
    choices: [
      'WPA3-Personal uses SAE (Simultaneous Authentication of Equals / "Dragonfly") which is a PAKE — offline brute-force of captured handshakes is no longer effective because the captured exchange does not yield a usable verifier',
      'WPA2-PSK with longer SSIDs',
      'Hidden SSID broadcast',
      'MAC address filtering',
    ],
    correctIndex: 0,
    explanation: 'WPA3-Personal\'s SAE replaces the WPA2 4-way handshake with a PAKE that resists offline dictionary attacks. SSID-related controls (length, hiding) and MAC filtering provide negligible security. NIST SP 800-97 and the Wi-Fi Alliance WPA3 spec describe the upgrade.',
    distractorRationale: {
      1: 'SSID length does not change cryptographic strength.',
      2: 'Hidden SSID is broadcast in probe requests; trivially defeated.',
      3: 'MAC addresses are spoofable.',
    },
    source: { name: 'Wi-Fi Alliance — WPA3 specification overview', url: 'https://www.wi-fi.org/discover-wi-fi/security' },
  },

  {
    id: 'net-017',
    topic: 'network',
    subtopic: 'vpn',
    difficulty: 'senior',
    question: 'IPsec IKEv1 with Aggressive Mode and PSK has a well-known weakness. What is it?',
    choices: [
      'In Aggressive Mode the PSK-derived hash is sent in the first round, allowing offline brute-force of the PSK. Recommendation: disable Aggressive Mode (or move to IKEv2 with certificates)',
      'IKEv1 only works on Linux',
      'IKEv1 always uses TCP',
      'IKEv1 does not encrypt',
    ],
    correctIndex: 0,
    explanation: 'IKEv1 Aggressive Mode reduces the round trips at the cost of leaking the hashed PSK to a passive observer, which can be brute-forced offline (ike-scan + psk-crack). Cisco and most vendors recommend disabling Aggressive Mode and migrating to IKEv2 with certificates. RFC and vendor advisories document this.',
    distractorRationale: {
      1: 'IKEv1 runs on many platforms.',
      2: 'IKE uses UDP/500 (and 4500 for NAT-T).',
      3: 'IKE encrypts; the issue is the PSK exposure mechanism.',
    },
    source: { name: 'Cisco — Configuring IKEv1 / IKEv2 (best practices)', url: 'https://www.cisco.com/c/en/us/td/docs/security/asa/asa-cli-reference/I-R/asa-command-ref-I-R/ikev2-ikev1-commands.html' },
  },

  {
    id: 'net-018',
    topic: 'network',
    subtopic: 'rdp-bluekeep',
    difficulty: 'senior',
    question: 'BlueKeep (CVE-2019-0708) targets which RDP component, and what configuration prevents pre-auth exploitation?',
    choices: [
      'A use-after-free in the RDP MS_T120 channel handling within `termdd.sys` — pre-authentication. Network Level Authentication (NLA) prevents the unauthenticated path required for exploitation',
      'A buffer overflow in the Windows Print Spooler',
      'A privilege escalation in MSI installer',
      'A flaw in the Windows kernel scheduler',
    ],
    correctIndex: 0,
    explanation: 'BlueKeep is a wormable pre-auth RDP RCE in legacy stacks. NLA forces the client to authenticate before any session is created, which means the vulnerable code path is not reachable unauth. Microsoft\'s advisory and CISA bulletin document both the bug and the NLA mitigation.',
    distractorRationale: {
      1: 'PrintNightmare is the spooler vulnerability, not BlueKeep.',
      2: 'MSI installer is unrelated.',
      3: 'Scheduler bugs are a different class.',
    },
    source: { name: 'Microsoft MSRC — CVE-2019-0708 (BlueKeep)', url: 'https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-0708' },
  },

  {
    id: 'net-019',
    topic: 'network',
    subtopic: 'kerberos-port',
    difficulty: 'senior',
    question: 'Which port(s) and transport does Kerberos use, and why does the answer matter for firewall/segmentation reviews?',
    choices: [
      'TCP/UDP 88 for KDC operations and TCP/UDP 464 for kpasswd. Both UDP and TCP must be reachable; TCP becomes mandatory for large PAC payloads (groups). Blocking only UDP and assuming TCP also blocked is a common scoping error',
      'TCP 21 only',
      'UDP 53 only',
      'TCP 22 only',
    ],
    correctIndex: 0,
    explanation: 'Kerberos uses UDP/88 by default but falls back to TCP/88 when responses exceed UDP MTU (e.g., users in many groups). kpasswd is on 464. Misconfigured ACLs that only allow UDP/88 break authentication and are a common operational issue, while overly permissive rules expose ticket requests cross-segment.',
    distractorRationale: {
      1: 'FTP is on 21.',
      2: 'DNS is on 53.',
      3: 'SSH is on 22.',
    },
    source: { name: 'Microsoft Learn — Service overview and network port requirements for Windows', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements' },
  },

  {
    id: 'net-020',
    topic: 'network',
    subtopic: 'winrm',
    difficulty: 'senior',
    question: 'WinRM (PowerShell remoting) listens on which ports by default, and what is the senior-level security note?',
    choices: [
      'TCP 5985 (HTTP) and 5986 (HTTPS). Default uses Kerberos/NTLM authentication; pentest tools (Evil-WinRM, NetExec winrm) use it for code execution. The hardening recommendation is to enforce HTTPS, restrict remoting to a defined administrative subnet, and use JEA for least-privilege command sets.',
      'TCP 23 / 25',
      'UDP 137 / 138',
      'TCP 80 / 443 only',
    ],
    correctIndex: 0,
    explanation: 'WinRM defaults to HTTP/5985 and HTTPS/5986. It is widely abused once credentials are obtained because it is enabled by default in many domain environments. Microsoft\'s WinRM hardening and Just Enough Administration (JEA) docs cover the recommended controls.',
    distractorRationale: {
      1: 'Telnet/SMTP — different services.',
      2: 'NetBIOS/Datagram — different services.',
      3: 'Web ports are not WinRM defaults.',
    },
    source: { name: 'Microsoft Learn — Installation and Configuration for Windows Remote Management', url: 'https://learn.microsoft.com/en-us/windows/win32/winrm/installation-and-configuration-for-windows-remote-management' },
  },

  {
    id: 'net-021',
    topic: 'network',
    subtopic: 'smtp',
    difficulty: 'senior',
    question: 'You find an internet-facing SMTP server that accepts mail for arbitrary recipient domains and forwards them. What is the finding, and which configuration directive in Postfix (or equivalent) typically disables it?',
    choices: [
      'Open relay. In Postfix the `mynetworks` list and `smtpd_relay_restrictions` should restrict who can send mail through the server; an open relay is abused for spam, blocklists the IP, and can be a phishing-staging asset for an attacker',
      'TLS misconfiguration; fix with `smtpd_tls_security_level=encrypt`',
      'POP3 misconfiguration',
      'Maildir corruption',
    ],
    correctIndex: 0,
    explanation: 'Open relays accept mail for any external domain from any source. This is abused for spam and phishing, often resulting in IP blocklisting. Postfix\'s `smtpd_relay_restrictions` (with `permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination`) is the canonical fix.',
    distractorRationale: {
      1: 'TLS controls confidentiality, not relay scope.',
      2: 'POP3 is a separate retrieval protocol.',
      3: 'Maildir is on-disk format, unrelated.',
    },
    source: { name: 'Postfix documentation — Relaying and smtpd_relay_restrictions', url: 'https://www.postfix.org/postconf.5.html' },
  },

  {
    id: 'net-022',
    topic: 'network',
    subtopic: 'ftp',
    difficulty: 'senior',
    question: 'You find an FTP server that accepts username `anonymous` and any password. What is the senior framing of this finding for the report?',
    choices: [
      '"Sensitive information disclosure / unauthenticated access via FTP" — examine what the anonymous user can read AND write (anonymous-writable directories are a common pivot to RCE on FTP servers that expose them to a webroot, and to phishing payload hosting)',
      'A clean configuration with no risk',
      'A safe legacy protocol',
      'Encrypted by default',
    ],
    correctIndex: 0,
    explanation: 'Anonymous FTP is not inherently bad if exposure is limited and read-only with curated content, but in practice it often reveals internal docs, credentials in scripts, or — worse — anonymous-writable directories that can be combined with web roots for RCE. The senior writeup quantifies the actual data disclosed and any write capabilities.',
    distractorRationale: {
      1: 'Anonymous read of arbitrary internal content is rarely "no risk".',
      2: 'FTP is plaintext by default; far from "safe".',
      3: 'FTP is plaintext (FTPS/SFTP are different protocols/configurations).',
    },
    source: { name: 'NIST SP 800-115 — service-level testing guidance', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-023',
    topic: 'network',
    subtopic: 'ot-modbus',
    difficulty: 'senior',
    question: 'In an OT/ICS environment, Modbus TCP (port 502) has which security characteristic that drives the senior pentester to extreme caution?',
    choices: [
      'Modbus has no built-in authentication or encryption; any host that can reach port 502 can read register values and (where the device permits) write to coils/registers — i.e., issue commands to the PLC. Because the PLC controls physical processes, even unauthenticated read scans can be unsafe and writes can be dangerous',
      'Modbus uses TLS 1.3 by default',
      'Modbus is encrypted with AES-256',
      'Modbus requires Kerberos',
    ],
    correctIndex: 0,
    explanation: 'Standard Modbus/TCP has no authentication or encryption. CISA\'s ICS advisories repeatedly flag exposed Modbus on flat IT networks as a critical exposure. Senior testing methodology mandates explicit ROE around OT, passive observation first, and only authorised, conservative active probes — never aggressive scanning or writes.',
    distractorRationale: {
      1: 'Modbus does not use TLS by default.',
      2: 'Encryption is not part of the standard.',
      3: 'No Kerberos.',
    },
    source: { name: 'CISA — Recommended Practices for ICS Cybersecurity', url: 'https://www.cisa.gov/topics/industrial-control-systems' },
  },

  {
    id: 'net-024',
    topic: 'network',
    subtopic: 'ipv6',
    difficulty: 'senior',
    question: 'When scoping internal pentests on networks where "IPv6 is not deployed," which fact should a senior pentester remember?',
    choices: [
      'Windows hosts have IPv6 enabled by default and prefer it. Adversaries can use rogue Router Advertisements (RA) or DHCPv6 to lateral-move and intercept traffic on networks that operationally ignore IPv6 — so "we don\'t use IPv6" is exactly the unmonitored attack path',
      'IPv6 is impossible without an ISP allocation',
      'IPv6 cannot carry SMB',
      'IPv6 disables Active Directory',
    ],
    correctIndex: 0,
    explanation: 'Modern Windows defaults to IPv6 with link-local addresses always present. Networks that "do not use IPv6" usually do not monitor it either, leaving rogue RA/DHCPv6 attacks (mitm6, RA flooding) effective by default. Microsoft\'s IPv6 hardening guidance and Fox-IT\'s mitm6 research describe the exposure.',
    distractorRationale: {
      1: 'Link-local IPv6 works without ISP allocation.',
      2: 'SMB works fine over IPv6.',
      3: 'AD works over IPv6 too.',
    },
    source: { name: 'Microsoft Learn — IPv6 Guidance for Windows networks', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows' },
  },

  {
    id: 'net-025',
    topic: 'network',
    subtopic: 'segmentation',
    difficulty: 'senior',
    question: 'In a factory environment, the IT/OT segmentation reference model that guides scoping discussions with the client is most commonly which?',
    choices: [
      'The Purdue Model (Levels 0–5) and ISA/IEC 62443 zones-and-conduits — used to define what is monitored, what is testable, and what handoffs (jump hosts, data diodes) exist between IT and OT',
      'The OWASP API Top 10',
      'The CIS-20 Controls only',
      'The PCI DSS standard',
    ],
    correctIndex: 0,
    explanation: 'Purdue Model and ISA/IEC 62443 are the de-facto frameworks for OT/ICS segmentation. Senior pentesters scope OT engagements in terms of which Purdue level is in scope, which conduits cross zones, and how IT-side compromise can pivot toward L2/L1. NIST SP 800-82 references them. IT-only frameworks (PCI, OWASP) do not capture this.',
    distractorRationale: {
      1: 'API Top 10 is web/API specific.',
      2: 'CIS Controls cover IT broadly, not OT zones.',
      3: 'PCI DSS is about payment-card environments.',
    },
    source: { name: 'NIST SP 800-82 Rev. 3 — Guide to OT Security (references the Purdue/IEC 62443 models)', url: 'https://csrc.nist.gov/publications/detail/sp/800-82/rev-3/final' },
  },

  {
    id: 'net-026', topic: 'network', subtopic: 'nmap-nse', difficulty: 'senior',
    question: 'Nmap NSE (Nmap Scripting Engine) lets you run scripts against discovered services. Which categories should a senior pentester invoke selectively versus by default?',
    choices: ['Default categories include `default`, `safe`, `discovery`. Categories like `intrusive`, `exploit`, `vuln`, `dos`, `brute` should be invoked only with explicit authorisation because they may probe vulnerable code paths or send brute-force traffic', '`default` is the only category', 'All categories are safe by default', '`exploit` is enabled when you use `-sV`'],
    correctIndex: 0,
    explanation: 'Nmap NSE\'s categories let you scope script behaviour. The official Nmap docs enumerate them. RoE for assessments typically restricts intrusive/exploit/dos/brute scripts unless agreed.',
    distractorRationale: { 1: 'There are many categories.', 2: 'Intrusive ones can break services.', 3: '-sV is service-version detection, not exploit.' },
    source: { name: 'Nmap NSE Categories — official documentation', url: 'https://nmap.org/book/nse-usage.html#nse-categories' },
  },

  {
    id: 'net-027', topic: 'network', subtopic: 'nmap-version-detection', difficulty: 'senior',
    question: '`nmap -sV` enables service version detection. What does this do under the hood, and what is its operational caveat?',
    choices: ['It probes responding ports with a sequence of crafted application-layer payloads (HTTP GET, FTP banner, SMB negotiate, etc.) and matches responses against `nmap-service-probes`. Caveat: it generates more noise/logs than a straight port scan and may interact unsafely with fragile services (e.g., legacy ICS)', 'It downgrades TLS', 'It encrypts the scan', 'It is identical to OS detection'],
    correctIndex: 0,
    explanation: 'Service version detection sends application-layer probes to fingerprint software. Useful for triage, but louder than SYN-only scans. The Nmap book documents probe behaviour and intensity (`--version-intensity`).',
    distractorRationale: { 1: 'TLS handling is independent.', 2: 'Scans are not encrypted.', 3: 'OS detection is `-O`, separate.' },
    source: { name: 'Nmap — Service and Version Detection', url: 'https://nmap.org/book/man-version-detection.html' },
  },

  {
    id: 'net-028', topic: 'network', subtopic: 'masscan', difficulty: 'senior',
    question: 'Masscan claims to scan the entire IPv4 internet quickly. What is its key architectural difference from Nmap, and why does that matter operationally?',
    choices: ['Masscan implements its own asynchronous TCP/IP stack and bypasses the kernel network stack — it can sustain millions of packets per second. Operational caveat: easy to overwhelm targets/upstream networks; high false-positive rates if probes are dropped; and it uses random scan order so targets receive intermittent SYNs', 'It is just a wrapper around Nmap', 'It only does ICMP', 'It runs only over TLS'],
    correctIndex: 0,
    explanation: 'Robert Graham\'s Masscan is purpose-built for internet-scale scanning, with its own TCP stack. The README documents tuning (--rate, randomisation) and operational considerations.',
    distractorRationale: { 1: 'It is independent of Nmap.', 2: 'Multi-protocol.', 3: 'It is not TLS-bound.' },
    source: { name: 'Masscan — official GitHub README', url: 'https://github.com/robertdavidgraham/masscan' },
  },

  {
    id: 'net-029', topic: 'network', subtopic: 'tcpdump-bpf', difficulty: 'senior',
    question: '`tcpdump host 10.0.0.5 and port 80` works because tcpdump compiles the expression to which low-level filter mechanism?',
    choices: ['BPF (Berkeley Packet Filter) bytecode applied at the kernel level so only matching packets are copied to userspace — efficient at high traffic. The same compiler is used by libpcap-based tools (Wireshark, etc.)', 'A regex run in userspace on every packet', 'A SQL query', 'A JavaScript engine'],
    correctIndex: 0,
    explanation: 'tcpdump compiles its filter expressions to BPF bytecode, executed in-kernel. The tcpdump and libpcap manuals describe the syntax and the underlying mechanism.',
    distractorRationale: { 1: 'Userspace regex per packet would be far too slow.', 2: 'No SQL involved.', 3: 'No JS.' },
    source: { name: 'tcpdump(8) man page — BPF syntax', url: 'https://www.tcpdump.org/manpages/tcpdump.1.html' },
  },

  {
    id: 'net-030', topic: 'network', subtopic: 'wireshark-display-filters', difficulty: 'senior',
    question: 'In Wireshark, the difference between capture filters and display filters is:',
    choices: ['Capture filters use BPF syntax and apply at capture time (cannot be undone), reducing what is recorded. Display filters use Wireshark\'s own expression language and apply on already-captured data, more powerful but slower. Senior testers usually capture broadly and filter at display time to retain analytical flexibility', 'They are identical', 'Capture filters are BSD-only', 'Display filters require root'],
    correctIndex: 0,
    explanation: 'Wireshark\'s docs explain both filter types and their tradeoffs. Senior practice is to capture wide, filter narrow — unless throughput requires otherwise.',
    distractorRationale: { 1: 'Different syntaxes and timings.', 2: 'BPF works on Linux, BSD, macOS.', 3: 'Display filters do not require root.' },
    source: { name: 'Wireshark User Guide — Display Filter vs Capture Filter', url: 'https://www.wireshark.org/docs/wsug_html_chunked/ChWorkBuildDisplayFilterSection.html' },
  },

  {
    id: 'net-031', topic: 'network', subtopic: 'inveigh', difficulty: 'senior',
    question: 'Inveigh is a tool from the AD attack ecosystem. What does it do?',
    choices: ['Inveigh is a Windows-native alternative to Responder, listening for LLMNR/NBT-NS/mDNS/DHCPv6 broadcasts and answering them to coerce NTLM authentication for relay or hash capture. Useful when running from a Windows beachhead host', 'It is a port scanner', 'It is a wireless cracker', 'It is a SQL injection tool'],
    correctIndex: 0,
    explanation: 'Inveigh complements Responder when the testing environment is Windows-only. Its GitHub describes feature parity and Windows-specific advantages.',
    distractorRationale: { 1: 'Not a port scanner.', 2: 'Not wireless.', 3: 'Not SQLi.' },
    source: { name: 'Inveigh — official GitHub repository', url: 'https://github.com/Kevin-Robertson/Inveigh' },
  },

  {
    id: 'net-032', topic: 'network', subtopic: 'evil-winrm', difficulty: 'senior',
    question: 'Evil-WinRM is a tester favourite for what?',
    choices: ['An interactive WinRM shell with built-in features for file upload/download, in-memory `Invoke-Binary` execution of .NET assemblies, AMSI bypass helpers, and Pass-the-Hash support — purpose-built for offensive WinRM workflows', 'A vulnerability scanner', 'A wireless cracker', 'A web crawler'],
    correctIndex: 0,
    explanation: 'Evil-WinRM (Hackplayers) wraps PowerShell\'s WinRM client with offensive ergonomics. The README documents flags and the in-memory execution helpers.',
    distractorRationale: { 1: 'Not a vuln scanner.', 2: 'Not wireless.', 3: 'Not a crawler.' },
    source: { name: 'Hackplayers — Evil-WinRM GitHub repository', url: 'https://github.com/Hackplayers/evil-winrm' },
  },

  {
    id: 'net-033', topic: 'network', subtopic: 'ntlmrelayx', difficulty: 'senior',
    question: 'Impacket\'s `ntlmrelayx.py` is the canonical NTLM relay tool. Which target protocols does it support?',
    choices: ['SMB, LDAP/LDAPS, HTTP/HTTPS (including AD CS Web Enrollment for ESC8), MSSQL, IMAP, SMTP, RPC and others — paired with coercion primitives (PetitPotam, PrinterBug, DFSCoerce) for end-to-end relay chains', 'SMB only', 'HTTP only', 'Telnet only'],
    correctIndex: 0,
    explanation: 'ntlmrelayx is multi-protocol and integrates many target-specific abuse paths (LDAP modifications for RBCD, ADCS issuance, etc.). Impacket\'s docs and examples enumerate options.',
    distractorRationale: { 1: 'Multi-protocol.', 2: 'Multi-protocol.', 3: 'Telnet is not supported.' },
    source: { name: 'Fortra Impacket — ntlmrelayx.py examples', url: 'https://github.com/fortra/impacket/blob/master/examples/ntlmrelayx.py' },
  },

  {
    id: 'net-034', topic: 'network', subtopic: 'firewall-evasion', difficulty: 'senior',
    question: 'Nmap\'s `--source-port`, `-f`, and `--data-length` options are documented as which kind of evasions, and when do they actually help?',
    choices: ['Firewall/IDS evasion — useful against simple stateless filters that allow traffic from common ports (53, 80) or that drop very short fragmented packets. Modern stateful firewalls and IDS/IPS render most of these obsolete; their value is mostly in legacy networks', 'They speed up scans', 'They encrypt traffic', 'They bypass TLS only'],
    correctIndex: 0,
    explanation: 'Nmap\'s firewall evasion docs are honest that these techniques are largely historical. Senior testers know when to deploy them (legacy ACLs) vs spend time elsewhere.',
    distractorRationale: { 1: 'Speed is via timing templates.', 2: 'No encryption added.', 3: 'TLS is unrelated.' },
    source: { name: 'Nmap — Firewall/IDS Evasion and Spoofing', url: 'https://nmap.org/book/man-bypass-firewalls-ids.html' },
  },

  {
    id: 'net-035', topic: 'network', subtopic: 'chisel', difficulty: 'senior',
    question: 'Chisel is widely used during pentests to:',
    choices: ['Tunnel TCP/UDP through HTTP(S) — useful when only outbound HTTPS is allowed from a compromised host. Implements client/server modes with authenticated WebSocket transport, supports SOCKS proxies, and is a single static Go binary that drops easily on many platforms', 'Crack passwords', 'Decompile binaries', 'Run AV bypass'],
    correctIndex: 0,
    explanation: 'jpillora/chisel is a Go-based HTTP-tunneling proxy. Its single-binary deployment and SOCKS support make it a senior pentest workhorse for egress-restricted networks.',
    distractorRationale: { 1: 'Not a cracker.', 2: 'Not a decompiler.', 3: 'Not AV-focused.' },
    source: { name: 'jpillora — Chisel GitHub repository', url: 'https://github.com/jpillora/chisel' },
  },

  {
    id: 'net-036', topic: 'network', subtopic: 'shodan', difficulty: 'senior',
    question: 'Shodan is best described as:',
    choices: ['An internet-wide search engine of banner-grabbed services. Senior pentesters use it during pre-engagement OSINT to enumerate exposed services in scope (with explicit authorisation), check for shadow IT or accidental exposures, and validate scope claims', 'A vulnerability scanner', 'A C2 framework', 'A WAF'],
    correctIndex: 0,
    explanation: 'Shodan continually scans the public internet and indexes service banners, certificates and vendor identifiers. The Shodan Help Center documents query syntax and the API.',
    distractorRationale: { 1: 'It catalogs exposures, does not exploit.', 2: 'Not a C2.', 3: 'Not a WAF.' },
    source: { name: 'Shodan — Help Center / Documentation', url: 'https://help.shodan.io/' },
  },

  {
    id: 'net-037', topic: 'network', subtopic: 'amass', difficulty: 'senior',
    question: 'OWASP Amass is purpose-built for:',
    choices: ['Subdomain enumeration combining passive sources (CT logs, public DNS data, search APIs) and active techniques (DNS brute force, zone walking, NSEC). Output feeds attack-surface mapping and subsequent recon', 'Web application scanning', 'Wireless analysis', 'Reverse engineering'],
    correctIndex: 0,
    explanation: 'OWASP Amass is the canonical open-source asset-discovery framework. Its docs cover passive and active modes, integrations and graph storage.',
    distractorRationale: { 1: 'Not a web scanner.', 2: 'Not wireless.', 3: 'Not RE.' },
    source: { name: 'OWASP Amass — official project page', url: 'https://owasp.org/www-project-amass/' },
  },

  {
    id: 'net-038', topic: 'network', subtopic: 'wireshark-tls-keylog', difficulty: 'senior',
    question: 'You need to decrypt a TLS-encrypted PCAP. The standard Wireshark approach is:',
    choices: ['Configure the client/browser to write TLS session keys to a file via the `SSLKEYLOGFILE` environment variable, then load the file in Wireshark\'s TLS preferences (Premaster-Secret log). This works for forward-secret ciphers (ECDHE) — RSA key import only works for non-PFS ciphers', 'Brute-force the TLS session', 'Patch Wireshark with the server private key', 'Disable TLS in Wireshark'],
    correctIndex: 0,
    explanation: 'NSS-style key logging is supported by browsers (Chrome, Firefox) and many libraries. Wireshark documents loading the keylog file via the TLS protocol preferences. With ECDHE, server key alone is insufficient.',
    distractorRationale: { 1: 'Brute force is infeasible.', 2: 'Server private key works only for RSA-keyex sessions.', 3: 'Disabling does not decrypt.' },
    source: { name: 'Wireshark Wiki — TLS decryption (key log)', url: 'https://wiki.wireshark.org/TLS' },
  },

  {
    id: 'net-039', topic: 'network', subtopic: 'sslstrip', difficulty: 'senior',
    question: 'Moxie Marlinspike\'s sslstrip technique is largely defeated today because of which control?',
    choices: ['HSTS (HTTP Strict Transport Security) — once a browser has cached an HSTS policy for a domain, it refuses to make HTTP requests; preload lists ship with major browsers so even first-visit requests use HTTPS. SSLStrip relied on initial HTTP redirects to begin a session', 'HSTS is irrelevant', 'WPA3', 'TLS 1.3 alone'],
    correctIndex: 0,
    explanation: 'HSTS (RFC 6797) and the HSTS preload list neuter sslstrip\'s "downgrade-on-first-request" trick. TLS 1.3 protects sessions but does not prevent users from initially making HTTP requests; HSTS does.',
    distractorRationale: { 1: 'It is the relevant control.', 2: 'Wireless cipher.', 3: 'TLS 1.3 alone does not prevent sslstrip.' },
    source: { name: 'IETF RFC 6797 — HSTS', url: 'https://datatracker.ietf.org/doc/html/rfc6797' },
  },

  {
    id: 'net-040', topic: 'network', subtopic: 'rustscan', difficulty: 'senior',
    question: 'RustScan is sometimes positioned as "faster than Nmap". Senior framing of when to use it:',
    choices: ['RustScan parallelises port discovery aggressively then hands off to Nmap for service detection — useful as a quick first-pass enumerator on large IP ranges. It is not a replacement for Nmap, just a faster front-end. Caveat: aggressive defaults can overwhelm fragile networks (especially OT) and trigger IDS', 'It replaces Nmap entirely', 'It can crack TLS', 'It is a wireless tool'],
    correctIndex: 0,
    explanation: 'RustScan\'s README describes its design: fast async port discovery with Nmap delegation. Useful in moderation; defaults need tuning per RoE.',
    distractorRationale: { 1: 'It calls Nmap for fingerprinting.', 2: 'No TLS attack.', 3: 'Not wireless.' },
    source: { name: 'RustScan — official GitHub repository', url: 'https://github.com/RustScan/RustScan' },
  },

  {
    id: 'net-041', topic: 'network', subtopic: 'nmap-udp', difficulty: 'senior',
    question: 'UDP scanning (`-sU`) is much slower than SYN scanning. Why?',
    choices: ['UDP is connectionless: open ports often do not respond, closed ports return ICMP Port Unreachable but ICMP rate limiting (RFC 1812) caps the response rate. Distinguishing open from filtered requires waiting for timeouts. Nmap also probes with protocol-specific payloads (`--version-intensity`) which are slow', 'Because UDP is encrypted', 'Because UDP requires Kerberos', 'Because UDP runs at L7 only'],
    correctIndex: 0,
    explanation: 'Nmap\'s UDP scan documentation explains the rate-limit problem and recommends combining `-sU` with payload probes and `--max-retries` tuning. Senior testers know UDP scans need careful pacing.',
    distractorRationale: { 1: 'UDP is unencrypted.', 2: 'No Kerberos requirement.', 3: 'UDP is a transport.' },
    source: { name: 'Nmap — UDP Scan (-sU)', url: 'https://nmap.org/book/scan-methods-udp-scan.html' },
  },

  {
    id: 'net-042', topic: 'network', subtopic: 'smtp-vrfy-expn', difficulty: 'senior',
    question: 'Why are SMTP `VRFY` and `EXPN` commands a common reportable finding when enabled?',
    choices: ['They allow user/mailing-list enumeration without authentication. Senior recommendation: disable both (Postfix `disable_vrfy_command=yes`, sendmail / Exchange equivalents). Modern servers default to disabled but legacy installs often leave them on', 'They encrypt traffic', 'They enforce SPF', 'They require TLS'],
    correctIndex: 0,
    explanation: 'RFC 5321 defines VRFY (verify a recipient) and EXPN (expand a list). They leak account/group existence. NIST SP 800-115 and OWASP testing guides recommend disabling them.',
    distractorRationale: { 1: 'They are unencrypted commands.', 2: 'Unrelated to SPF.', 3: 'TLS is independent.' },
    source: { name: 'IETF RFC 5321 — Simple Mail Transfer Protocol', url: 'https://datatracker.ietf.org/doc/html/rfc5321' },
  },

  {
    id: 'net-043', topic: 'network', subtopic: 'snmpv3-usm', difficulty: 'senior',
    question: 'SNMPv3 introduces USM (User-based Security Model). What does it provide that SNMPv2c does not?',
    choices: ['Authenticated and encrypted SNMP messages: per-user credentials with HMAC-MD5/SHA authentication and DES/AES privacy. Replaces shared community strings with cryptographically protected sessions. Caveat: SNMPv3 is more complex to configure and many environments leave v2c enabled in parallel', 'It uses TLS', 'It runs on TCP', 'It authenticates by IP address'],
    correctIndex: 0,
    explanation: 'RFC 3414 defines USM. Senior pentesters check for SNMPv3 misconfigurations (auth-only without priv, weak HMAC) and parallel v2c exposure.',
    distractorRationale: { 1: 'It is not TLS-based.', 2: 'SNMP is on UDP/161.', 3: 'IP-based auth is no auth.' },
    source: { name: 'IETF RFC 3414 — User-based Security Model (USM) for SNMPv3', url: 'https://datatracker.ietf.org/doc/html/rfc3414' },
  },

  {
    id: 'net-044', topic: 'network', subtopic: 'ntp-monlist', difficulty: 'senior',
    question: 'NTP `monlist` queries became a notorious DDoS amplification vector because:',
    choices: ['A small request returned a large list of recent peers (amplification factor up to ~556x). Attackers spoofed source IPs to direct massive responses at victims. Mitigations: disable monlist (`disable monitor` in ntp.conf), and ISPs implement BCP38 anti-spoofing', 'NTP is TCP', 'NTP requires TLS', 'NTP uses Kerberos'],
    correctIndex: 0,
    explanation: 'CVE-2013-5211 popularised the issue. US-CERT/CISA published advisories and patches; modern NTP defaults disable monlist. BCP38 (anti-spoofing) at the network edge prevents amplification more broadly.',
    distractorRationale: { 1: 'NTP is on UDP/123.', 2: 'No TLS by default.', 3: 'No Kerberos involvement.' },
    source: { name: 'CISA — NTP Amplification Attacks Using the monlist Command', url: 'https://www.cisa.gov/news-events/alerts/2014/01/13/ntp-amplification-attacks-using-monlist-command' },
  },

  {
    id: 'net-045', topic: 'network', subtopic: 'dns-amplification', difficulty: 'senior',
    question: 'DNS amplification works because:',
    choices: ['A small query (~60 bytes) for a large response type (e.g., ANY, DNSKEY) returns a much larger response (often >4kB), and DNS uses UDP which permits source-IP spoofing. Mitigations: rate-limit responses per source (RRL), restrict open recursion, BCP38 at the network edge', 'DNS uses TCP exclusively', 'DNS encrypts queries by default', 'DNS uses Kerberos'],
    correctIndex: 0,
    explanation: 'DNS amplification is a long-standing UDP-based DDoS technique. ISC and CISA recommend Response Rate Limiting (RRL) on authoritative servers and disabling open recursion. BCP38 at the network edge addresses spoofing globally.',
    distractorRationale: { 1: 'DNS is primarily UDP/53.', 2: 'Cleartext by default unless DoT/DoH.', 3: 'No Kerberos.' },
    source: { name: 'CISA — DNS Amplification Attacks', url: 'https://www.cisa.gov/news-events/alerts/2013/03/29/dns-amplification-attacks' },
  },

  {
    id: 'net-046', topic: 'network', subtopic: 'ipv6-slaac', difficulty: 'senior',
    question: 'IPv6 SLAAC (Stateless Address Autoconfiguration) creates host addresses based on:',
    choices: ['A Router Advertisement (RA) supplying a /64 prefix combined with an Interface ID derived from the host (originally MAC-based via EUI-64; modern OSes randomise per RFC 7217). Rogue RA attacks exploit hosts that auto-configure from any RA on the link', 'DHCPv4', 'A central PKI', 'BGP'],
    correctIndex: 0,
    explanation: 'RFC 4862 defines SLAAC; rogue-RA and RA-flooding are well-known attack vectors. RA Guard at the switch is the standard mitigation. Senior pentesters consider both stateless and DHCPv6-based attack paths.',
    distractorRationale: { 1: 'DHCPv4 is for IPv4.', 2: 'No PKI involvement.', 3: 'BGP is inter-AS routing.' },
    source: { name: 'IETF RFC 4862 — IPv6 Stateless Address Autoconfiguration', url: 'https://datatracker.ietf.org/doc/html/rfc4862' },
  },

  {
    id: 'net-047', topic: 'network', subtopic: 'nmap-idle-scan', difficulty: 'senior',
    question: 'Nmap\'s idle scan (`-sI <zombie>`) achieves what?',
    choices: ['Source-spoofed scanning: probes appear to come from a "zombie" host with predictable IP-ID sequences. The attacker observes the zombie\'s IP-ID changes to infer port states on the target. Useful (in legitimate testing) for confirming firewall asymmetry; rarely used today because most modern OSes randomise IP-IDs', 'It speeds up scans', 'It encrypts scans', 'It enables UDP scans'],
    correctIndex: 0,
    explanation: 'Idle scan exploits predictable IP-ID counters on the zombie. The Nmap book documents the technique in detail. It is more academic on modern OSes but still occasionally useful.',
    distractorRationale: { 1: 'It is slower than direct scans.', 2: 'No encryption.', 3: 'Unrelated to UDP.' },
    source: { name: 'Nmap — Idle Scan (-sI)', url: 'https://nmap.org/book/idlescan.html' },
  },

  {
    id: 'net-048', topic: 'network', subtopic: 'nmap-decoy', difficulty: 'senior',
    question: 'Nmap\'s `-D RND:5,ME` decoy scan does what, and what is its operational reality?',
    choices: ['Sends scans alongside spoofed packets from random decoy IPs (with ME = your real IP) so the target log sees multiple sources. Operational reality: modern IDS / threat intel correlation often unmasks the real source quickly; decoys are mostly useful for blending, not for evading attribution', 'It encrypts the scan', 'It is required for Nmap to work', 'It bypasses authentication'],
    correctIndex: 0,
    explanation: 'Decoy scan is a long-standing Nmap feature. The Nmap book is clear about its limited operational value against well-instrumented defenders.',
    distractorRationale: { 1: 'No encryption.', 2: 'Optional flag.', 3: 'No auth bypass.' },
    source: { name: 'Nmap — Cloak a Scan with Decoys', url: 'https://nmap.org/book/man-bypass-firewalls-ids.html#idm46168700019792' },
  },

  {
    id: 'net-049', topic: 'network', subtopic: 'redis-unauth', difficulty: 'senior',
    question: 'An unauthenticated Redis instance bound to 0.0.0.0 enables which classic post-discovery attack on a Linux host?',
    choices: ['Writing the attacker\'s SSH public key into ~/.ssh/authorized_keys via `CONFIG SET dir /home/redis/.ssh` + `CONFIG SET dbfilename authorized_keys` + `SAVE` — gaining SSH as the redis user. Mitigation: bind to localhost, set requirepass, or enable ACLs (Redis 6+)', 'Mining Bitcoin', 'A CSRF', 'A clickjacking'],
    correctIndex: 0,
    explanation: 'The "Redis SSH key drop" technique is widely exploited in opportunistic attacks. Redis docs and many CVE writeups document the prerequisites and the SAVE-to-file primitive.',
    distractorRationale: { 1: 'Bitcoin mining is post-RCE; the attack is the file write.', 2: 'CSRF is browser-issued.', 3: 'Clickjacking is iframe-based.' },
    source: { name: 'Redis Security — official documentation', url: 'https://redis.io/docs/management/security/' },
  },

  {
    id: 'net-050', topic: 'network', subtopic: 'memcached-amplification', difficulty: 'senior',
    question: 'Memcached UDP amplification is notable because:',
    choices: ['Pre-1.5.6 Memcached listened on UDP by default with no auth, allowing spoofed source-IP queries that returned multi-kilobyte responses (amplification factor 50,000x+). Mitigations: upgrade and disable UDP entirely (`-U 0`), and never expose Memcached to untrusted networks', 'It is encrypted by default', 'It uses Kerberos', 'It runs on TCP only'],
    correctIndex: 0,
    explanation: 'CVE-2018 (the GitHub.com 1.35 Tbps DDoS) leveraged Memcached UDP. The Memcached project disabled UDP by default in 1.5.6+. CISA and US-CERT published advisories.',
    distractorRationale: { 1: 'No TLS by default.', 2: 'No Kerberos.', 3: 'It supports both TCP and UDP historically.' },
    source: { name: 'CISA — Cisco Memcached Reflection / Amplification Attacks Advisory', url: 'https://www.cisa.gov/news-events/alerts/2018/02/27/memcached-distributed-denial-service-attacks' },
  },

  {
    id: 'net-051', topic: 'network', subtopic: 'docker-exposed-daemon', difficulty: 'senior',
    question: 'A Docker daemon exposed on TCP 2375 (no TLS) yields what?',
    choices: ['Full RCE as root on the host: any client can `docker run -v /:/mnt --privileged ubuntu chroot /mnt sh` to escape into the host filesystem. Mitigations: bind to localhost only, require client certificates (TLS on 2376), and treat exposed daemons as critical findings', 'A safe management API', 'A read-only metrics interface', 'A Kubernetes endpoint'],
    correctIndex: 0,
    explanation: 'Docker\'s docs explicitly warn that exposing the daemon over network without TLS+client auth is equivalent to root access. Senior reports treat this as critical.',
    distractorRationale: { 1: 'Far from safe.', 2: 'Read-write API.', 3: 'Distinct from k8s API.' },
    source: { name: 'Docker — Protect the Docker daemon socket (TLS)', url: 'https://docs.docker.com/engine/security/protect-access/' },
  },

  {
    id: 'net-052', topic: 'network', subtopic: 'kubernetes-api', difficulty: 'senior',
    question: 'A Kubernetes API server reachable with anonymous access enables what for an attacker?',
    choices: ['Querying cluster state, listing pods/secrets/serviceaccounts, and (if RBAC permits) creating workloads — leading to full cluster takeover. Mitigation: disable anonymous-auth, enforce RBAC with least privilege, audit `kubectl auth can-i --list --as=system:anonymous`', 'Nothing useful', 'Only metrics access', 'Only DNS queries'],
    correctIndex: 0,
    explanation: 'Anonymous-auth on the Kubernetes API server is a well-known misconfiguration. CIS Kubernetes benchmark recommends disabling it. Senior reports phrase impact in terms of RBAC mappings.',
    distractorRationale: { 1: 'It is highly impactful.', 2: 'Beyond metrics.', 3: 'API supports many resources.' },
    source: { name: 'Kubernetes — Authenticating (anonymous-auth)', url: 'https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-requests' },
  },

  {
    id: 'net-053', topic: 'network', subtopic: 'elasticsearch-unauth', difficulty: 'senior',
    question: 'Pre-7.x Elasticsearch defaulted to no authentication. Why is that a critical finding when found in 2026?',
    choices: ['Anyone reachable can read every index, search/dump data, and (with default config) execute scripted queries that run in the JVM. Mitigations: enable Elastic Security (X-Pack auth), bind to localhost, run behind a reverse proxy with auth. Senior reports note that "Elastic exposed" usually means PII at scale', 'It is encrypted by default', 'It requires Kerberos', 'It uses TLS only'],
    correctIndex: 0,
    explanation: 'Elasticsearch authentication has been free since v7+ but legacy deployments still run unauth. CISA and many breach reports cite exposed Elastic clusters as the proximate cause of leaked data sets.',
    distractorRationale: { 1: 'Default was unencrypted.', 2: 'No Kerberos requirement.', 3: 'Optional.' },
    source: { name: 'Elastic — Set up minimal security for Elasticsearch (basic auth)', url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/security-minimal-setup.html' },
  },

  {
    id: 'net-054', topic: 'network', subtopic: 'mongodb-unauth', difficulty: 'senior',
    question: 'Unauthenticated MongoDB instances bound to 0.0.0.0 have driven mass-data leaks for years because:',
    choices: ['Default MongoDB <2.6 had no authentication enabled; the bindIp was 0.0.0.0. Modern defaults bind to localhost (3.6+) and require auth, but many cloud images and ports remain exposed. Senior reports include a count of records / databases enumerable', 'MongoDB encrypts disk by default', 'MongoDB is over UDP', 'MongoDB requires Kerberos'],
    correctIndex: 0,
    explanation: 'MongoDB security defaults have hardened over time, but legacy / mis-deployed instances persist. MongoDB\'s security checklist documents required steps. Public scans (Shodan) consistently list thousands of exposed instances.',
    distractorRationale: { 1: 'Disk encryption is feature-gated.', 2: 'TCP-based.', 3: 'No Kerberos requirement.' },
    source: { name: 'MongoDB — Security Checklist', url: 'https://www.mongodb.com/docs/manual/administration/security-checklist/' },
  },

  {
    id: 'net-055', topic: 'network', subtopic: 'tftp-exposure', difficulty: 'senior',
    question: 'TFTP servers exposed in internal networks are a classic finding because:',
    choices: ['TFTP has no authentication and is often used by network gear to fetch configs/firmware; an attacker can read existing files (router configs, often containing secrets) or upload malicious firmware. UDP-only, lossy, and trivially abused — modern best practice is to use SCP/SFTP and disable TFTP if not strictly required', 'TFTP encrypts by default', 'TFTP requires SAML', 'TFTP runs over TCP'],
    correctIndex: 0,
    explanation: 'TFTP\'s lack of authentication has been documented since RFC 1350. CISA, NIST and vendor docs all recommend retiring TFTP for sensitive transfers.',
    distractorRationale: { 1: 'Cleartext.', 2: 'No SAML.', 3: 'UDP/69.' },
    source: { name: 'IETF RFC 1350 — Trivial File Transfer Protocol', url: 'https://datatracker.ietf.org/doc/html/rfc1350' },
  },

  {
    id: 'net-056', topic: 'network', subtopic: 'ipmi', difficulty: 'senior',
    question: 'IPMI (Intelligent Platform Management Interface, BMC management) on UDP/623 has well-known weaknesses. The senior framing:',
    choices: ['Multiple inherent weaknesses (CVE-2013-4786 cipher zero auth bypass, hash retrieval pre-auth, default vendor credentials) make exposed BMC management planes effectively bypassable. Recommendation: never expose BMC interfaces beyond a dedicated management VLAN, change default creds, disable cipher suite zero', 'IPMI is safely encrypted', 'IPMI requires TLS', 'IPMI uses Kerberos'],
    correctIndex: 0,
    explanation: 'CERT/CC and SANS have long flagged IPMI as a critical exposure. Vendor BMCs (Supermicro, HP iLO, Dell iDRAC) sit at firmware level — compromise is below the OS. Network segmentation is the only durable defence.',
    distractorRationale: { 1: 'Encryption is broken or disabled in many configs.', 2: 'No TLS.', 3: 'No Kerberos.' },
    source: { name: 'CERT/CC — IPMI Cipher Zero Authentication Bypass (VU#491239)', url: 'https://www.kb.cert.org/vuls/id/491239' },
  },

  {
    id: 'net-057', topic: 'network', subtopic: 'cisa-kev', difficulty: 'senior',
    question: 'When prioritising network-side findings during reporting, which authoritative list of "actively-exploited-in-the-wild" CVEs should a senior pentester reference?',
    choices: ['CISA KEV (Known Exploited Vulnerabilities) catalog — vulnerabilities with documented in-the-wild exploitation. Senior reports cite KEV alongside CVSS to prioritise truly urgent items separately from theoretically high-severity ones', 'OWASP Top 10 only', 'NIST CSF maturity tiers', 'PCI DSS compliance map'],
    correctIndex: 0,
    explanation: 'CISA\'s KEV catalog is the de-facto reference for "this is being exploited right now". Many federal mandates require remediation within set windows for KEV entries. Senior reporting treats KEV as urgency context.',
    distractorRationale: { 1: 'OWASP Top 10 is awareness, not exploitation telemetry.', 2: 'NIST CSF is maturity framework.', 3: 'PCI is compliance.' },
    source: { name: 'CISA — Known Exploited Vulnerabilities Catalog', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog' },
  },

  {
    id: 'net-058', topic: 'network', subtopic: 'nessus-credentialed', difficulty: 'senior',
    question: 'Why is a credentialed Nessus scan dramatically more useful than an uncredentialed one?',
    choices: ['Credentialed scans authenticate to hosts via SSH/WMI/SMB and read installed-package versions, registry entries and config files directly, producing accurate vulnerability assessment with low false positives. Uncredentialed scans only see network responses, missing most patch-state information', 'They are slower and less accurate', 'They only work on Linux', 'They require IPv6'],
    correctIndex: 0,
    explanation: 'Tenable\'s docs and almost every senior assessment methodology recommend credentialed scans where possible. The CIS benchmarks and SANS materials concur.',
    distractorRationale: { 1: 'They are more accurate.', 2: 'Cross-platform.', 3: 'IP version is unrelated.' },
    source: { name: 'Tenable — Credentialed Checks vs Network-Based Assessments', url: 'https://docs.tenable.com/nessus/Content/CredentialedChecks.htm' },
  },

  {
    id: 'net-059', topic: 'network', subtopic: 'ssl-labs', difficulty: 'senior',
    question: 'When evaluating TLS configurations for a report, which authoritative scoring service is widely used as a baseline?',
    choices: ['Qualys SSL Labs (and the open-source `testssl.sh` — for offline / segregated environments). Both produce graded reports referencing protocol, cipher, certificate and HSTS posture against modern best practices', 'Wireshark', 'Nmap only', 'Hashcat'],
    correctIndex: 0,
    explanation: 'SSL Labs\' grading is widely understood by stakeholders. testssl.sh covers the same ground locally. Senior reports often include SSL Labs grades as a quick summary.',
    distractorRationale: { 1: 'Wireshark is a sniffer.', 2: 'Nmap has TLS NSE but no graded posture.', 3: 'Hashcat is for cracking.' },
    source: { name: 'Qualys SSL Labs — Server Test', url: 'https://www.ssllabs.com/ssltest/' },
  },

  {
    id: 'net-060', topic: 'network', subtopic: 'mitre-d3fend', difficulty: 'senior',
    question: 'Beyond MITRE ATT&CK (which catalogs adversary techniques), what is MITRE D3FEND, and why does it matter for senior pentest reporting?',
    choices: ['D3FEND is a knowledge graph of defensive countermeasures mapped to ATT&CK techniques. Senior reports that recommend mitigations alongside findings can cite D3FEND to show the corresponding defence and how it is supposed to disrupt the attacker action', 'A vulnerability scanner', 'A SIEM platform', 'A penetration testing distribution'],
    correctIndex: 0,
    explanation: 'D3FEND complements ATT&CK by catalog ing defences. Senior reports that pair a finding with both the ATT&CK technique it enables and the D3FEND mitigation it lacks demonstrate maturity beyond raw findings.',
    distractorRationale: { 1: 'Not a scanner.', 2: 'Not a SIEM.', 3: 'Not a Linux distro.' },
    source: { name: 'MITRE D3FEND — Knowledge Graph', url: 'https://d3fend.mitre.org/' },
  },
];
