// Network pen-testing — senior interview questions.
// Authority sources: Nmap official docs, Microsoft Learn, MITRE ATT&CK, NIST SP 800-115, vendor docs.

window.QUESTION_BANK.network = [
  {
    id: 'net-001',
    topic: 'network',
    subtopic: 'nmap',
    difficulty: 'senior',
    question: 'What is the precise difference between `nmap -sS` (SYN scan) and `nmap -sT` (TCP connect scan), and why does it matter operationally?',
    choices: [
      '`-sS` requires raw-socket privileges (root/Administrator) but never completes the TCP handshake, making it stealthier and faster; `-sT` uses the OS connect() syscall, completes the handshake, and is logged by application-layer services',
      '`-sS` scans only HTTPS ports while `-sT` scans only HTTP ports',
      '`-sS` is UDP-based; `-sT` is TCP-based',
      '`-sS` is for IPv6; `-sT` is for IPv4',
    ],
    correctIndex: 0,
    explanation: 'SYN scan crafts raw packets and never sends the final ACK, so the connection never appears to userspace and many app-layer logs miss it; it requires raw-socket privileges. TCP connect scan uses the OS connect() syscall, completes the 3-way handshake, and is therefore visible to application logs. Nmap\'s official scan-types reference is explicit on this difference.',
    distractorRationale: {
      1: 'Both scans are protocol-agnostic at the port level — `-p` controls which ports are checked, not the scan type.',
      2: 'Both are TCP scans by definition; UDP scanning is `-sU`.',
      3: 'IP version is controlled by `-6`, not by the scan type.',
    },
    source: { name: 'Nmap Reference Guide — Port Scanning Techniques', url: 'https://nmap.org/book/man-port-scanning-techniques.html' },
  },

  {
    id: 'net-002',
    topic: 'network',
    subtopic: 'llmnr-poisoning',
    difficulty: 'senior',
    question: 'You run Responder on an internal segment and start collecting NetNTLMv2 hashes. Which Microsoft-recommended setting most directly disables the underlying name-resolution channel Responder abuses?',
    choices: [
      'Disabling SMBv1',
      'Disabling LLMNR (via "Turn off multicast name resolution" Group Policy) AND disabling NetBIOS over TCP/IP',
      'Enforcing NTLMv2 over NTLMv1',
      'Enabling Windows Defender Credential Guard',
    ],
    correctIndex: 1,
    explanation: 'Responder abuses LLMNR and NBT-NS broadcast/multicast name-resolution to answer failed lookups and coerce victims to authenticate to it. The mitigation is to disable both name-resolution channels by Group Policy. Microsoft\'s NTLM relay / coercion guidance covers this. MITRE catalogues the abuse as T1557.001.',
    distractorRationale: {
      0: 'Disabling SMBv1 is good hygiene but unrelated to broadcast name resolution.',
      2: 'NTLMv2 vs NTLMv1 is about cryptographic strength, not about whether Responder receives the hash in the first place.',
      3: 'Credential Guard protects in-memory credentials; it does not stop a victim sending NTLM auth to Responder.',
    },
    source: { name: 'MITRE ATT&CK T1557.001 — Adversary-in-the-Middle: LLMNR/NBT-NS Poisoning and SMB Relay', url: 'https://attack.mitre.org/techniques/T1557/001/' },
  },

  {
    id: 'net-003',
    topic: 'network',
    subtopic: 'pivoting',
    difficulty: 'senior',
    question: 'You have RCE on a perimeter host with no direct internet egress on internal subnets. Which technique gives you the most flexible way to reach internal hosts from your attacker box without dropping additional binaries?',
    choices: [
      'Run an ARP scan from the perimeter host',
      'Use SSH dynamic port forwarding (`ssh -D 1080`) and proxychains, or set up an SSH reverse SOCKS tunnel and route tools through it',
      'Switch the perimeter host\'s NIC into promiscuous mode',
      'Reboot the perimeter host into safe mode',
    ],
    correctIndex: 1,
    explanation: 'A SOCKS proxy via SSH (-D for forward, -R + sshuttle/Chisel for reverse) lets your local Nmap, browser, etc. tunnel through the compromised host with minimal artefacts and no special tooling on the target beyond the SSH client. NIST SP 800-115 and OffSec materials describe pivoting via SOCKS as the standard pattern.',
    distractorRationale: {
      0: 'ARP scans only enumerate the local L2 segment from that host; they do not let you reach internal subnets from your laptop.',
      2: 'Promiscuous mode helps with passive sniffing on the same segment, not with reaching arbitrary internal hosts.',
      3: 'Safe mode would drop services and detection alerts and accomplishes nothing for pivoting.',
    },
    source: { name: 'NIST SP 800-115 — Technical Guide to Information Security Testing and Assessment', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-004',
    topic: 'network',
    subtopic: 'rdp',
    difficulty: 'senior',
    question: 'Network Level Authentication (NLA) is enabled on an RDP service. What is the security impact compared to RDP without NLA?',
    choices: [
      'NLA encrypts the post-logon RDP session more strongly',
      'NLA requires the client to authenticate before a session is established, mitigating pre-auth RCE classes (e.g., BlueKeep CVE-2019-0708) and reducing exposed attack surface',
      'NLA disables clipboard sharing',
      'NLA forces the use of smartcards',
    ],
    correctIndex: 1,
    explanation: 'NLA uses CredSSP to require credentials before the server creates a session. This drastically reduces pre-auth attack surface — vulnerabilities like BlueKeep and many DoS vectors require interaction before authentication, which NLA prevents. Microsoft\'s RDP security guidance is explicit on this.',
    distractorRationale: {
      0: 'NLA is about pre-session authentication, not the bulk encryption strength of the data channel.',
      2: 'Clipboard redirection is a separate device-redirection setting.',
      3: 'NLA does not require smartcards; CredSSP can use NTLM, Kerberos, or smartcards.',
    },
    source: { name: 'Microsoft Learn — Configure Network Level Authentication for RDP', url: 'https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access' },
  },

  {
    id: 'net-005',
    topic: 'network',
    subtopic: 'ot-ics',
    difficulty: 'senior',
    question: 'You are scoping an internal pentest at a dairy/food factory. The client confirms there are PLCs and SCADA workstations on a separate VLAN. What is the most senior-appropriate approach to that VLAN?',
    choices: [
      'Run an aggressive Nmap scan (`-T4 -A -p-`) to maximise coverage',
      'Treat the OT segment as out-of-scope unless explicitly authorised; if authorised, use passive techniques and avoid full-port / OS-detection scans because legacy ICS protocols can crash on probes',
      'Send Modbus function-code 8 (Diagnostics: restart communication) to verify availability',
      'Replay captured EtherNet/IP packets at line rate',
    ],
    correctIndex: 1,
    explanation: 'CISA, ISA/IEC 62443 and NIST SP 800-82 all stress that legacy ICS devices were not designed to handle modern scan traffic; even a benign Nmap can crash a PLC and halt production. The senior-appropriate posture is explicit scope confirmation, passive observation, and only authorised, conservative active testing. This is also a common interview probe for senior pentesters.',
    distractorRationale: {
      0: 'A `-T4 -A -p-` aggressive scan against ICS gear is exactly the action that has historically caused outages — never the right move.',
      2: 'Function code 8 sub-codes can stop the device or clear counters; running it without explicit authorisation is irresponsible.',
      3: 'Replaying capture traffic on an OT network is uncontrolled and can put workers in physical danger.',
    },
    source: { name: 'NIST SP 800-82 Rev. 3 — Guide to Operational Technology Security', url: 'https://csrc.nist.gov/publications/detail/sp/800-82/rev-3/final' },
  },

  {
    id: 'net-006',
    topic: 'network',
    subtopic: 'mitm6',
    difficulty: 'senior',
    question: 'mitm6 abuses default Windows behaviour to perform an attack. Which protocol does it primarily target, and why is it effective by default?',
    choices: [
      'IPv4 DHCP — Windows requests addresses on every boot',
      'IPv6 DHCPv6 — Windows is configured to prefer IPv6 even on networks that have not formally deployed it, so a rogue DHCPv6 server can set itself as the DNS server and intercept name resolution',
      'ARP — Windows broadcasts MAC requests',
      'NetBIOS over TCP/IP only',
    ],
    correctIndex: 1,
    explanation: 'Modern Windows enables IPv6 by default and prefers it over IPv4. mitm6 listens for DHCPv6 solicits and replies with a rogue configuration pointing DNS at the attacker, enabling NTLM coercion against WPAD/SMB. Fox-IT\'s mitm6 release post and Microsoft\'s IPv6 hardening guidance both describe the mechanism and the mitigation (disable IPv6 if unused, or apply the registry/policy controls).',
    distractorRationale: {
      0: 'mitm6 is specifically an IPv6 attack; IPv4 DHCP rogue servers are a separate class.',
      2: 'ARP poisoning is L2 and unrelated to mitm6.',
      3: 'NBT-NS poisoning (Responder) is a different protocol and a different tool.',
    },
    source: { name: 'Fox-IT / Dirk-jan Mollema — mitm6 release post', url: 'https://blog.fox-it.com/2018/01/11/mitm6-compromising-ipv4-networks-via-ipv6/' },
  },

  {
    id: 'net-007',
    topic: 'network',
    subtopic: 'snmp',
    difficulty: 'senior',
    question: 'Why is SNMP v1 / v2c with the community string `public` a high-value finding in an internal pentest?',
    choices: [
      'SNMP v1/v2c uses cleartext community strings as the only authentication. With `public` (read-only) you can enumerate device config, ARP tables, routing, running processes; with `private` (read-write) you can modify config, exfiltrate the running-config (Cisco), or reroute traffic',
      'SNMP encrypts traffic with AES-256 by default',
      'SNMP requires Kerberos authentication',
      'SNMP is only available over IPv6',
    ],
    correctIndex: 0,
    explanation: 'SNMP v1/v2c sends the community string in the clear and provides no real authentication. snmpwalk with `public` enumerates a wealth of OIDs; with `private` an attacker can grab Cisco running-configs over TFTP. SNMP v3 adds authentication and privacy. NIST and vendor docs describe the exposure.',
    distractorRationale: {
      1: 'Only SNMPv3 supports privacy (encryption); v1/v2c do not.',
      2: 'SNMP does not use Kerberos.',
      3: 'SNMP works on both IPv4 and IPv6.',
    },
    source: { name: 'NIST SP 800-115 — Information security testing (services like SNMP)', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-008',
    topic: 'network',
    subtopic: 'smb-null-session',
    difficulty: 'senior',
    question: 'Against a legacy Windows server you are able to connect to `\\\\target\\IPC$` with a NULL session. What does this typically let you enumerate and which Microsoft control disables it?',
    choices: [
      'Domain users, groups, password policy, SMB shares, etc., via MS-RPC over IPC$. The control is the `RestrictAnonymous`/`RestrictAnonymousSAM` registry settings (and modern policies that disable anonymous SAM/SAM-named-pipes lookups).',
      'Internet routing tables — disabled by changing TTL',
      'Active Directory DNS records — disabled by disabling DNS dynamic updates',
      'RDP sessions — disabled by setting NLA',
    ],
    correctIndex: 0,
    explanation: 'Anonymous (NULL) SMB connections to IPC$ historically allowed RPC enumeration of users, groups, domain policy, shares, etc. (LSARPC, SAMR). Microsoft\'s `RestrictAnonymous` and `RestrictAnonymousSAM` settings (and Network Access policies in modern Windows) prevent this. NetExec / rpcclient / enum4linux remain the go-to tools.',
    distractorRationale: {
      1: 'Routing tables are not exposed via IPC$.',
      2: 'DNS records are not exposed via IPC$.',
      3: 'RDP sessions are not enumerated via IPC$.',
    },
    source: { name: 'Microsoft Learn — Network access: Do not allow anonymous enumeration of SAM accounts', url: 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-anonymous-enumeration-of-sam-accounts' },
  },

  {
    id: 'net-009',
    topic: 'network',
    subtopic: 'nfs',
    difficulty: 'senior',
    question: 'An NFSv3 export is configured with `no_root_squash`. Why is this dangerous?',
    choices: [
      'A client mounting the share can write files as UID 0 (root) of the server. Combined with mounting an OS partition, the attacker can write into authorized_keys, /etc/passwd, or set SUID binaries to gain root on the server',
      'It encrypts traffic too strongly',
      'It blocks all writes',
      'It enables IPv6 only',
    ],
    correctIndex: 0,
    explanation: 'By default NFS "squashes" the remote root to the unprivileged `nobody` user. `no_root_squash` disables that, so a client root writes as server root. Trivial to escalate via SSH key drop, /etc/passwd edit, or a SUID binary. Linux man-exports and CIS benchmarks both flag this.',
    distractorRationale: {
      1: 'NFS does not encrypt by default — that is a separate concern (Kerberos NFS).',
      2: 'It does not block writes; the opposite.',
      3: 'IPv6 is unrelated.',
    },
    source: { name: 'Linux exports(5) man page — no_root_squash', url: 'https://man7.org/linux/man-pages/man5/exports.5.html' },
  },

  {
    id: 'net-010',
    topic: 'network',
    subtopic: 'ssh',
    difficulty: 'senior',
    question: 'An SSH server allows password authentication AND has no fail2ban / rate limit. From a senior pentester perspective, beyond running a brute-force, what configuration finding is the more pointed report item?',
    choices: [
      'The server should disable password authentication entirely (`PasswordAuthentication no`), enforce key-based auth, restrict via Match groups, and disable root login (`PermitRootLogin no`); rate-limiting alone treats the symptom not the root cause',
      'The server should run on port 23',
      'The server should disable AES-256',
      'The server should expose Telnet as a fallback',
    ],
    correctIndex: 0,
    explanation: 'Hardening SSH means moving away from credentials that can be brute-forced at all: keys + 2FA, no root login, restrict source networks, and disable weak algorithms. CIS benchmarks for Ubuntu/RHEL document the exact set. Senior reports phrase the finding as a hardening gap, not just "missing rate limit".',
    distractorRationale: {
      1: 'Port 23 is Telnet — significantly worse.',
      2: 'AES-256 is fine; weak ciphers/algos should be disabled, not strong ones.',
      3: 'Telnet fallback is the opposite of secure.',
    },
    source: { name: 'CIS Benchmarks (Ubuntu/RHEL) — SSH hardening', url: 'https://www.cisecurity.org/cis-benchmarks' },
  },

  {
    id: 'net-011',
    topic: 'network',
    subtopic: 'dns-zone-transfer',
    difficulty: 'senior',
    question: 'You run `dig AXFR @ns1.target.tld target.tld` and the server returns the full zone. Why is this a finding even though no exploitation is needed?',
    choices: [
      'Unrestricted zone transfers leak internal hostnames, IP layout, mail and service records — high-value reconnaissance for further attack. The fix is to restrict AXFR to authorised secondaries via `allow-transfer` (BIND) or equivalent',
      'AXFR enables RCE on the resolver',
      'AXFR is encrypted by default',
      'AXFR transfers the kernel image',
    ],
    correctIndex: 0,
    explanation: 'AXFR is the legitimate zone-transfer mechanism for replicating zones to secondaries. Misconfigured servers replying to anyone leak the entire DNS namespace — a recon goldmine. BIND and similar servers allow per-source ACLs. NIST SP 800-81 documents secure DNS deployment.',
    distractorRationale: {
      1: 'AXFR does not provide RCE.',
      2: 'AXFR is plaintext over TCP/53; not encrypted unless transport is layered.',
      3: 'AXFR is a DNS protocol exchange, nothing to do with kernels.',
    },
    source: { name: 'NIST SP 800-81-2 — Secure Domain Name System (DNS) Deployment Guide', url: 'https://csrc.nist.gov/publications/detail/sp/800-81/2/final' },
  },

  {
    id: 'net-012',
    topic: 'network',
    subtopic: 'arp-spoofing',
    difficulty: 'senior',
    question: 'You are on the same VLAN as a victim. Which technique places you in-path between victim and gateway at L2, and what makes it succeed by default?',
    choices: [
      'ARP spoofing: send unsolicited ARP replies mapping the gateway IP to your MAC; switches forward L2 frames based on MAC, hosts cache ARP without authentication, so traffic is rerouted. Mitigations: Dynamic ARP Inspection (DAI) on managed switches, plus DHCP snooping',
      'BGP hijacking',
      'TCP RST injection',
      'TLS downgrade',
    ],
    correctIndex: 0,
    explanation: 'ARP has no authentication. Tools like arpspoof, bettercap, and Ettercap implement the standard mitm. Cisco DAI / DHCP snooping detects mismatches between L2/L3. Vendor docs and OWASP guidance describe the technique and defences.',
    distractorRationale: {
      1: 'BGP is at the routing layer, not L2.',
      2: 'TCP RST injection is a transport-layer attack against an existing flow.',
      3: 'TLS downgrade attacks the application layer.',
    },
    source: { name: 'Cisco — Configuring Dynamic ARP Inspection', url: 'https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3850/software/release/16-1/configuration_guide/sec/b_161_sec_3850_cg/configuring_dynamic_arp_inspection.html' },
  },

  {
    id: 'net-013',
    topic: 'network',
    subtopic: 'vlan-hopping',
    difficulty: 'senior',
    question: 'VLAN hopping via "double tagging" requires which switch misconfiguration to be effective?',
    choices: [
      'The attacker\'s port being on the SAME VLAN as the trunk\'s native VLAN. The attacker sends a frame with two 802.1Q tags; the first switch strips the outer (matching the native VLAN) and forwards the frame to the trunk, where the second switch reads the inner tag and delivers to the target VLAN. The fix is to never use the native VLAN for user traffic and to pin a dedicated unused VLAN as native',
      'IPv6 enabled on the trunk',
      'BGP enabled in the LAN',
      'Spanning Tree Protocol disabled',
    ],
    correctIndex: 0,
    explanation: 'Double-tagging exploits the native-VLAN behaviour of 802.1Q trunks. The defence is to set the native VLAN of every trunk to a dedicated, unused VLAN and to never put user ports on the native VLAN. Cisco\'s "Securing Layer 2" guidance is the canonical reference.',
    distractorRationale: {
      1: 'IPv6 is not part of the technique.',
      2: 'BGP is L3 routing.',
      3: 'STP is loop prevention; not the hopping mechanism.',
    },
    source: { name: 'Cisco — VLAN Security White Paper / Layer 2 attacks', url: 'https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-6500-series-switches/white_paper_c11_605972.html' },
  },

  {
    id: 'net-014',
    topic: 'network',
    subtopic: 'wpad',
    difficulty: 'senior',
    question: 'WPAD (Web Proxy Auto-Discovery) is famously abused for credential theft. What is the canonical chain?',
    choices: [
      'A client searches for `wpad.<domain>` via DHCP, DNS, then LLMNR/NBT-NS. Responder answers the broadcast lookup, the client fetches a wpad.dat from the attacker, sets a proxy, and then sends Web traffic with NTLM auth to the attacker — yielding NetNTLMv2 hashes for offline cracking or SMB-relay',
      'WPAD launches malware via WSUS',
      'WPAD requires IPv6 multicast',
      'WPAD is only used by Linux clients',
    ],
    correctIndex: 0,
    explanation: 'WPAD\'s discovery process falls back to broadcast name resolution, which Responder can answer authoritatively on segments where LLMNR/NBT-NS is permitted. The compromised proxy then captures NTLM auth on subsequent web traffic. Microsoft documents WPAD risks; mitigations include disabling WPAD discovery and the LLMNR/NBT-NS controls.',
    distractorRationale: {
      1: 'WSUS is a separate Windows-update service.',
      2: 'WPAD does not require IPv6.',
      3: 'WPAD is a Windows-default behaviour.',
    },
    source: { name: 'Microsoft Learn — How the Web Proxy Auto-Discovery Protocol Works', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/automatic-detection-settings-internet-explorer' },
  },

  {
    id: 'net-015',
    topic: 'network',
    subtopic: 'tls',
    difficulty: 'senior',
    question: 'A server supports TLS 1.0 and offers `TLS_RSA_WITH_AES_128_CBC_SHA`. Beyond "deprecated", what specific risks does the senior pentester cite?',
    choices: [
      'TLS 1.0 is vulnerable to BEAST (CBC IV reuse) and lacks modern cipher AEAD support; RSA-key-exchange ciphers (no PFS) mean a future leak of the server\'s private key allows decryption of all past sessions captured by a passive observer. Recommend TLS 1.2/1.3 only, with PFS (ECDHE) and AEAD (AES-GCM, ChaCha20-Poly1305)',
      'TLS 1.0 only works on UDP',
      'TLS 1.0 disables HTTP/2',
      'TLS 1.0 enables zero-trust by default',
    ],
    correctIndex: 0,
    explanation: 'TLS 1.0/1.1 are formally deprecated (RFC 8996). The senior framing addresses why: BEAST/POODLE-class CBC issues, no AEAD, RSA key-exchange ciphers without PFS expose past traffic to retroactive decryption. NIST SP 800-52r2 and Mozilla\'s TLS guidelines codify the recommended config.',
    distractorRationale: {
      1: 'TLS is over TCP (or QUIC); UDP-only is wrong.',
      2: 'HTTP/2 ALPN normally requires TLS 1.2+, but TLS 1.0 does not "disable" HTTP/2 as such.',
      3: 'Zero-trust is an architectural posture, not a TLS feature.',
    },
    source: { name: 'NIST SP 800-52 Rev. 2 — Guidelines for the Selection, Configuration, and Use of TLS Implementations', url: 'https://csrc.nist.gov/publications/detail/sp/800-52/rev-2/final' },
  },

  {
    id: 'net-016',
    topic: 'network',
    subtopic: 'wifi',
    difficulty: 'senior',
    question: 'WPA2-PSK 4-way handshake capture allows offline brute-force of the PSK. What additional WPA2/3 control most directly mitigates offline cracking, and why?',
    choices: [
      'WPA3-Personal uses SAE (Simultaneous Authentication of Equals / "Dragonfly") which is a PAKE — offline brute-force of captured handshakes is no longer effective because the captured exchange does not yield a usable verifier',
      'WPA2-PSK with longer SSIDs',
      'Hidden SSID broadcast',
      'MAC address filtering',
    ],
    correctIndex: 0,
    explanation: 'WPA3-Personal\'s SAE replaces the WPA2 4-way handshake with a PAKE that resists offline dictionary attacks. SSID-related controls (length, hiding) and MAC filtering provide negligible security. NIST SP 800-97 and the Wi-Fi Alliance WPA3 spec describe the upgrade.',
    distractorRationale: {
      1: 'SSID length does not change cryptographic strength.',
      2: 'Hidden SSID is broadcast in probe requests; trivially defeated.',
      3: 'MAC addresses are spoofable.',
    },
    source: { name: 'Wi-Fi Alliance — WPA3 specification overview', url: 'https://www.wi-fi.org/discover-wi-fi/security' },
  },

  {
    id: 'net-017',
    topic: 'network',
    subtopic: 'vpn',
    difficulty: 'senior',
    question: 'IPsec IKEv1 with Aggressive Mode and PSK has a well-known weakness. What is it?',
    choices: [
      'In Aggressive Mode the PSK-derived hash is sent in the first round, allowing offline brute-force of the PSK. Recommendation: disable Aggressive Mode (or move to IKEv2 with certificates)',
      'IKEv1 only works on Linux',
      'IKEv1 always uses TCP',
      'IKEv1 does not encrypt',
    ],
    correctIndex: 0,
    explanation: 'IKEv1 Aggressive Mode reduces the round trips at the cost of leaking the hashed PSK to a passive observer, which can be brute-forced offline (ike-scan + psk-crack). Cisco and most vendors recommend disabling Aggressive Mode and migrating to IKEv2 with certificates. RFC and vendor advisories document this.',
    distractorRationale: {
      1: 'IKEv1 runs on many platforms.',
      2: 'IKE uses UDP/500 (and 4500 for NAT-T).',
      3: 'IKE encrypts; the issue is the PSK exposure mechanism.',
    },
    source: { name: 'Cisco — Configuring IKEv1 / IKEv2 (best practices)', url: 'https://www.cisco.com/c/en/us/td/docs/security/asa/asa-cli-reference/I-R/asa-command-ref-I-R/ikev2-ikev1-commands.html' },
  },

  {
    id: 'net-018',
    topic: 'network',
    subtopic: 'rdp-bluekeep',
    difficulty: 'senior',
    question: 'BlueKeep (CVE-2019-0708) targets which RDP component, and what configuration prevents pre-auth exploitation?',
    choices: [
      'A use-after-free in the RDP MS_T120 channel handling within `termdd.sys` — pre-authentication. Network Level Authentication (NLA) prevents the unauthenticated path required for exploitation',
      'A buffer overflow in the Windows Print Spooler',
      'A privilege escalation in MSI installer',
      'A flaw in the Windows kernel scheduler',
    ],
    correctIndex: 0,
    explanation: 'BlueKeep is a wormable pre-auth RDP RCE in legacy stacks. NLA forces the client to authenticate before any session is created, which means the vulnerable code path is not reachable unauth. Microsoft\'s advisory and CISA bulletin document both the bug and the NLA mitigation.',
    distractorRationale: {
      1: 'PrintNightmare is the spooler vulnerability, not BlueKeep.',
      2: 'MSI installer is unrelated.',
      3: 'Scheduler bugs are a different class.',
    },
    source: { name: 'Microsoft MSRC — CVE-2019-0708 (BlueKeep)', url: 'https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-0708' },
  },

  {
    id: 'net-019',
    topic: 'network',
    subtopic: 'kerberos-port',
    difficulty: 'senior',
    question: 'A senior interviewer asks: which port(s) and transport does Kerberos use, and why does the answer matter for firewall/segmentation reviews?',
    choices: [
      'TCP/UDP 88 for KDC operations and TCP/UDP 464 for kpasswd. Both UDP and TCP must be reachable; TCP becomes mandatory for large PAC payloads (groups). Blocking only UDP and assuming TCP also blocked is a common scoping error',
      'TCP 21 only',
      'UDP 53 only',
      'TCP 22 only',
    ],
    correctIndex: 0,
    explanation: 'Kerberos uses UDP/88 by default but falls back to TCP/88 when responses exceed UDP MTU (e.g., users in many groups). kpasswd is on 464. Misconfigured ACLs that only allow UDP/88 break authentication and are a common operational issue, while overly permissive rules expose ticket requests cross-segment.',
    distractorRationale: {
      1: 'FTP is on 21.',
      2: 'DNS is on 53.',
      3: 'SSH is on 22.',
    },
    source: { name: 'Microsoft Learn — Service overview and network port requirements for Windows', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements' },
  },

  {
    id: 'net-020',
    topic: 'network',
    subtopic: 'winrm',
    difficulty: 'senior',
    question: 'WinRM (PowerShell remoting) listens on which ports by default, and what is the senior-level security note?',
    choices: [
      'TCP 5985 (HTTP) and 5986 (HTTPS). Default uses Kerberos/NTLM authentication; pentest tools (Evil-WinRM, NetExec winrm) use it for code execution. The hardening recommendation is to enforce HTTPS, restrict remoting to a defined administrative subnet, and use JEA for least-privilege command sets.',
      'TCP 23 / 25',
      'UDP 137 / 138',
      'TCP 80 / 443 only',
    ],
    correctIndex: 0,
    explanation: 'WinRM defaults to HTTP/5985 and HTTPS/5986. It is widely abused once credentials are obtained because it is enabled by default in many domain environments. Microsoft\'s WinRM hardening and Just Enough Administration (JEA) docs cover the recommended controls.',
    distractorRationale: {
      1: 'Telnet/SMTP — different services.',
      2: 'NetBIOS/Datagram — different services.',
      3: 'Web ports are not WinRM defaults.',
    },
    source: { name: 'Microsoft Learn — Installation and Configuration for Windows Remote Management', url: 'https://learn.microsoft.com/en-us/windows/win32/winrm/installation-and-configuration-for-windows-remote-management' },
  },

  {
    id: 'net-021',
    topic: 'network',
    subtopic: 'smtp',
    difficulty: 'senior',
    question: 'You find an internet-facing SMTP server that accepts mail for arbitrary recipient domains and forwards them. What is the finding, and which configuration directive in Postfix (or equivalent) typically disables it?',
    choices: [
      'Open relay. In Postfix the `mynetworks` list and `smtpd_relay_restrictions` should restrict who can send mail through the server; an open relay is abused for spam, blocklists the IP, and can be a phishing-staging asset for an attacker',
      'TLS misconfiguration; fix with `smtpd_tls_security_level=encrypt`',
      'POP3 misconfiguration',
      'Maildir corruption',
    ],
    correctIndex: 0,
    explanation: 'Open relays accept mail for any external domain from any source. This is abused for spam and phishing, often resulting in IP blocklisting. Postfix\'s `smtpd_relay_restrictions` (with `permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination`) is the canonical fix.',
    distractorRationale: {
      1: 'TLS controls confidentiality, not relay scope.',
      2: 'POP3 is a separate retrieval protocol.',
      3: 'Maildir is on-disk format, unrelated.',
    },
    source: { name: 'Postfix documentation — Relaying and smtpd_relay_restrictions', url: 'https://www.postfix.org/postconf.5.html' },
  },

  {
    id: 'net-022',
    topic: 'network',
    subtopic: 'ftp',
    difficulty: 'senior',
    question: 'You find an FTP server that accepts username `anonymous` and any password. What is the senior framing of this finding for the report?',
    choices: [
      '"Sensitive information disclosure / unauthenticated access via FTP" — examine what the anonymous user can read AND write (anonymous-writable directories are a common pivot to RCE on FTP servers that expose them to a webroot, and to phishing payload hosting)',
      'A clean configuration with no risk',
      'A safe legacy protocol',
      'Encrypted by default',
    ],
    correctIndex: 0,
    explanation: 'Anonymous FTP is not inherently bad if exposure is limited and read-only with curated content, but in practice it often reveals internal docs, credentials in scripts, or — worse — anonymous-writable directories that can be combined with web roots for RCE. The senior writeup quantifies the actual data disclosed and any write capabilities.',
    distractorRationale: {
      1: 'Anonymous read of arbitrary internal content is rarely "no risk".',
      2: 'FTP is plaintext by default; far from "safe".',
      3: 'FTP is plaintext (FTPS/SFTP are different protocols/configurations).',
    },
    source: { name: 'NIST SP 800-115 — service-level testing guidance', url: 'https://csrc.nist.gov/publications/detail/sp/800-115/final' },
  },

  {
    id: 'net-023',
    topic: 'network',
    subtopic: 'ot-modbus',
    difficulty: 'senior',
    question: 'In an OT/ICS environment, Modbus TCP (port 502) has which security characteristic that drives the senior pentester to extreme caution?',
    choices: [
      'Modbus has no built-in authentication or encryption; any host that can reach port 502 can read register values and (where the device permits) write to coils/registers — i.e., issue commands to the PLC. Because the PLC controls physical processes, even unauthenticated read scans can be unsafe and writes can be dangerous',
      'Modbus uses TLS 1.3 by default',
      'Modbus is encrypted with AES-256',
      'Modbus requires Kerberos',
    ],
    correctIndex: 0,
    explanation: 'Standard Modbus/TCP has no authentication or encryption. CISA\'s ICS advisories repeatedly flag exposed Modbus on flat IT networks as a critical exposure. Senior testing methodology mandates explicit ROE around OT, passive observation first, and only authorised, conservative active probes — never aggressive scanning or writes.',
    distractorRationale: {
      1: 'Modbus does not use TLS by default.',
      2: 'Encryption is not part of the standard.',
      3: 'No Kerberos.',
    },
    source: { name: 'CISA — Recommended Practices for ICS Cybersecurity', url: 'https://www.cisa.gov/topics/industrial-control-systems' },
  },

  {
    id: 'net-024',
    topic: 'network',
    subtopic: 'ipv6',
    difficulty: 'senior',
    question: 'When scoping internal pentests on networks where "IPv6 is not deployed," which fact should a senior pentester remember?',
    choices: [
      'Windows hosts have IPv6 enabled by default and prefer it. Adversaries can use rogue Router Advertisements (RA) or DHCPv6 to lateral-move and intercept traffic on networks that operationally ignore IPv6 — so "we don\'t use IPv6" is exactly the unmonitored attack path',
      'IPv6 is impossible without an ISP allocation',
      'IPv6 cannot carry SMB',
      'IPv6 disables Active Directory',
    ],
    correctIndex: 0,
    explanation: 'Modern Windows defaults to IPv6 with link-local addresses always present. Networks that "do not use IPv6" usually do not monitor it either, leaving rogue RA/DHCPv6 attacks (mitm6, RA flooding) effective by default. Microsoft\'s IPv6 hardening guidance and Fox-IT\'s mitm6 research describe the exposure.',
    distractorRationale: {
      1: 'Link-local IPv6 works without ISP allocation.',
      2: 'SMB works fine over IPv6.',
      3: 'AD works over IPv6 too.',
    },
    source: { name: 'Microsoft Learn — IPv6 Guidance for Windows networks', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows' },
  },

  {
    id: 'net-025',
    topic: 'network',
    subtopic: 'segmentation',
    difficulty: 'senior',
    question: 'In a factory environment, the IT/OT segmentation reference model that guides scoping discussions with the client is most commonly which?',
    choices: [
      'The Purdue Model (Levels 0–5) and ISA/IEC 62443 zones-and-conduits — used to define what is monitored, what is testable, and what handoffs (jump hosts, data diodes) exist between IT and OT',
      'The OWASP API Top 10',
      'The CIS-20 Controls only',
      'The PCI DSS standard',
    ],
    correctIndex: 0,
    explanation: 'Purdue Model and ISA/IEC 62443 are the de-facto frameworks for OT/ICS segmentation. Senior pentesters scope OT engagements in terms of which Purdue level is in scope, which conduits cross zones, and how IT-side compromise can pivot toward L2/L1. NIST SP 800-82 references them. IT-only frameworks (PCI, OWASP) do not capture this.',
    distractorRationale: {
      1: 'API Top 10 is web/API specific.',
      2: 'CIS Controls cover IT broadly, not OT zones.',
      3: 'PCI DSS is about payment-card environments.',
    },
    source: { name: 'NIST SP 800-82 Rev. 3 — Guide to OT Security (references the Purdue/IEC 62443 models)', url: 'https://csrc.nist.gov/publications/detail/sp/800-82/rev-3/final' },
  },
];
