// Web App Pen-Testing — senior-level PT questions.
// Authority sources: PortSwigger Web Security Academy, OWASP Top 10, OWASP Testing Guide v4, OWASP ASVS.
// Discovery sources are not used as citations.

window.QUESTION_BANK.web = [
  {
    id: 'web-001',
    topic: 'web',
    subtopic: 'ssrf',
    difficulty: 'senior',
    question: 'You suspect a blind SSRF on an internal endpoint that does not return any response body to the user. Which technique is the most reliable for confirming the vulnerability?',
    choices: [
      'Try injecting JavaScript and watch the rendered DOM for execution',
      'Use a Burp Collaborator (out-of-band) payload and watch for incoming HTTP/DNS interactions',
      'Time the response — anything over 2 seconds confirms the SSRF',
      'Submit a malformed URL and read the verbose error message returned to the user',
    ],
    correctIndex: 1,
    explanation: 'Blind SSRF returns no observable response, so confirmation requires an out-of-band channel. A Burp Collaborator (or similar canary like interact.sh) gives you a unique URL whose DNS/HTTP hits prove the back-end fetched it. PortSwigger calls this the standard approach for blind SSRF.',
    distractorRationale: {
      0: 'JavaScript execution tests XSS, not SSRF. SSRF is a server-side request, so client-side rendering is irrelevant.',
      2: 'Timing differences are unreliable for confirmation — they can be caused by load, caching, or rate-limiting, not by an SSRF.',
      3: 'A blind SSRF by definition does not surface error messages to the user; even when error messages exist they are not a reliable confirmation signal.',
    },
    source: { name: 'PortSwigger Web Security Academy — SSRF (blind)', url: 'https://portswigger.net/web-security/ssrf/blind' },
  },

  {
    id: 'web-002',
    topic: 'web',
    subtopic: 'sql-injection',
    difficulty: 'senior',
    question: 'A search field passes user input into a SELECT query but throws no error and returns no obvious data difference. Which class of SQL injection is most appropriate to attempt next?',
    choices: [
      'Union-based — read data through additional SELECT columns',
      'Error-based — coerce a verbose database error',
      'Blind boolean / time-based — infer data through truthy/falsy responses or timing',
      'Stored — write a payload that fires on a different page',
    ],
    correctIndex: 2,
    explanation: 'When the application returns no error and no visible data delta, blind SQLi is the appropriate path. You exfiltrate one bit at a time using boolean conditions (page differences) or time delays (e.g., SLEEP/WAITFOR). PortSwigger documents this exact decision flow.',
    distractorRationale: {
      0: 'Union-based requires the original query to be a SELECT and that you can see returned columns reflected somewhere. With no visible data difference there is no place to reflect a UNION result.',
      1: 'Error-based requires the application to surface DB error text, which the question explicitly says does not happen.',
      3: 'Stored SQLi is about persistence of payload, not detection technique. Its choice does not depend on whether the current response is observable.',
    },
    source: { name: 'PortSwigger Web Security Academy — Blind SQL Injection', url: 'https://portswigger.net/web-security/sql-injection/blind' },
  },

  {
    id: 'web-003',
    topic: 'web',
    subtopic: 'xss',
    difficulty: 'senior',
    question: 'A page reads a value from `location.hash` and writes it into the DOM via `innerHTML` with no server interaction. The payload never appears in HTTP requests. Which XSS class is this and why does it matter for testing methodology?',
    choices: [
      'Reflected XSS — server-side input filter must be tested',
      'Stored XSS — payload is persisted in a database',
      'DOM-based XSS — vulnerability is purely client-side, server logs will not show the payload',
      'Self-XSS — does not require any further testing',
    ],
    correctIndex: 2,
    explanation: 'DOM-based XSS sinks (e.g., innerHTML) consume sources (e.g., location.hash) entirely on the client, so the server never sees the payload. This is important because WAFs and server logs will not detect or block the attack — testing must be done in the browser. PortSwigger and the OWASP DOM-XSS guide both classify this case as DOM-based.',
    distractorRationale: {
      0: 'Reflected XSS requires the malicious string to round-trip through an HTTP request and response from the server, which is explicitly not happening here.',
      1: 'Stored XSS requires server-side persistence of the payload, but the payload never reaches the server.',
      3: 'Self-XSS is a social-engineering category where the user is tricked into pasting code into their own console; that is not what this scenario describes.',
    },
    source: { name: 'PortSwigger Web Security Academy — DOM-based vulnerabilities', url: 'https://portswigger.net/web-security/dom-based' },
  },

  {
    id: 'web-004',
    topic: 'web',
    subtopic: 'jwt',
    difficulty: 'senior',
    question: 'A web application validates JWTs using RS256. You change the `alg` header to `HS256` and sign the token with the public RSA key (which the app exposes at /jwks.json). Which class of vulnerability are you exploiting?',
    choices: [
      'JWT replay — reusing an old token after expiry',
      'Algorithm confusion — forcing a verifier expecting an asymmetric algorithm to use the public key as an HMAC secret',
      'Key disclosure — direct read of the private key from disk',
      'JWT injection into a SQL query',
    ],
    correctIndex: 1,
    explanation: 'JWT algorithm confusion happens when a verifier accepts whatever `alg` the token declares. Switching from RS256 to HS256 makes the verifier treat the public key as an HMAC secret, so an attacker who knows the public key can forge valid tokens. PortSwigger documents this as one of the headline JWT attacks.',
    distractorRationale: {
      0: 'Replay reuses the original token unchanged; here we are forging a new one with a different signing algorithm.',
      2: 'The private key is never disclosed in this attack — only the public key is needed, which is by design public.',
      3: 'The exploit does not involve injecting into SQL; it is purely an authentication-bypass against the token verifier.',
    },
    source: { name: 'PortSwigger Web Security Academy — JWT algorithm confusion', url: 'https://portswigger.net/web-security/jwt/algorithm-confusion' },
  },

  {
    id: 'web-005',
    topic: 'web',
    subtopic: 'access-control',
    difficulty: 'senior',
    question: 'An e-commerce app exposes /api/orders/123 where 123 is a numeric order ID. Changing it to /api/orders/124 returns another customer\'s order. What is the precise OWASP/PortSwigger name for this flaw?',
    choices: [
      'Cross-Site Request Forgery (CSRF)',
      'Insecure Direct Object Reference (IDOR) — a type of broken access control',
      'Server-Side Request Forgery (SSRF)',
      'Mass assignment',
    ],
    correctIndex: 1,
    explanation: 'IDOR is when an object identifier is exposed in a request and the server fails to verify the requester is authorized for that object. OWASP classifies it under Broken Access Control (A01 in the 2021 Top 10). PortSwigger\'s access-control material covers it explicitly.',
    distractorRationale: {
      0: 'CSRF tricks an authenticated user\'s browser into sending a state-changing request; this is just an unauthorized read by ID enumeration.',
      2: 'SSRF is the server fetching attacker-controlled URLs, not horizontal access bypass.',
      3: 'Mass assignment is when the framework binds extra fields from the request body into a model. Different vulnerability class.',
    },
    source: { name: 'PortSwigger Web Security Academy — Access control vulnerabilities (IDOR)', url: 'https://portswigger.net/web-security/access-control/idor' },
  },

  {
    id: 'web-006',
    topic: 'web',
    subtopic: 'request-smuggling',
    difficulty: 'senior',
    question: 'A front-end uses Content-Length to determine request boundaries, while the back-end uses Transfer-Encoding. Which HTTP Request Smuggling variant does this enable?',
    choices: [
      'CL.TE — front-end uses Content-Length, back-end uses Transfer-Encoding',
      'TE.CL — front-end uses Transfer-Encoding, back-end uses Content-Length',
      'TE.TE — both use Transfer-Encoding but parse it differently',
      'CL.0 — request has no body at all',
    ],
    correctIndex: 0,
    explanation: 'CL.TE is named after which header each hop respects: front-end honors Content-Length, back-end honors Transfer-Encoding. The desync lets an attacker hide a second request inside the first. PortSwigger\'s research and Web Security Academy define the naming.',
    distractorRationale: {
      1: 'TE.CL is the inverse — front-end uses TE, back-end uses CL — which is not what the question describes.',
      2: 'TE.TE refers to both ends honoring TE but disagreeing on parsing (e.g., obfuscated headers); the question says one side uses CL.',
      3: 'CL.0 is a more recent variant where the front-end uses Content-Length but the back-end treats certain requests as having no body; not what the prompt describes.',
    },
    source: { name: 'PortSwigger Web Security Academy — HTTP Request Smuggling', url: 'https://portswigger.net/web-security/request-smuggling' },
  },

  {
    id: 'web-007',
    topic: 'web',
    subtopic: 'ssti',
    difficulty: 'senior',
    question: 'You suspect Server-Side Template Injection in a Jinja2 (Python/Flask) app. Which payload is the canonical detection probe?',
    choices: [
      '`<script>alert(1)</script>`',
      "`{{7*7}}` — if the response contains 49, the input is being evaluated as a template",
      "`' OR 1=1 -- `",
      '`../../../../etc/passwd`',
    ],
    correctIndex: 1,
    explanation: '{{7*7}} is the standard SSTI probe: in a templated context the server evaluates the expression and returns 49, while a non-templated context echoes the literal string. This works for Jinja2, Twig, Mustache and most other engines that use {{...}} syntax. PortSwigger documents this exact methodology.',
    distractorRationale: {
      0: '<script>alert(1)</script> tests for XSS, which is client-side; SSTI executes server-side.',
      2: "`' OR 1=1 -- ` is a SQL injection probe — different sink and different evaluation context.",
      3: '../../../../etc/passwd tests for path traversal / LFI, not template evaluation.',
    },
    source: { name: 'PortSwigger Web Security Academy — Server-Side Template Injection', url: 'https://portswigger.net/web-security/server-side-template-injection' },
  },

  {
    id: 'web-008',
    topic: 'web',
    subtopic: 'cors',
    difficulty: 'senior',
    question: 'An API responds with `Access-Control-Allow-Origin: *` AND `Access-Control-Allow-Credentials: true`. Which statement is correct?',
    choices: [
      'This is a high-severity misconfiguration — any origin can read authenticated responses',
      'Modern browsers reject this combination, so the server config is effectively safe',
      'It is fine because CORS only governs writes, not reads',
      'It only matters if the API uses HTTP basic authentication',
    ],
    correctIndex: 1,
    explanation: 'The CORS specification forbids combining the wildcard origin with credentials — browsers will reject the response and refuse to expose it to JavaScript. The server config is sloppy and should be fixed, but it does not in itself create exploitable cross-origin reads of authenticated content. PortSwigger and the Fetch spec both describe this rule.',
    distractorRationale: {
      0: 'Browsers actively reject `*` with credentials, so the wildcard alone does not let third-party sites read authenticated responses.',
      2: 'CORS governs read access via JavaScript (XHR/fetch) — this is a misconception. The relevant point is the credentials/wildcard interaction, not reads vs writes.',
      3: 'CORS applies regardless of authentication scheme (cookies, bearer tokens, HTTP auth). The combination is forbidden in all credentialed cases.',
    },
    source: { name: 'PortSwigger Web Security Academy — CORS', url: 'https://portswigger.net/web-security/cors' },
  },

  {
    id: 'web-009',
    topic: 'web',
    subtopic: 'file-upload',
    difficulty: 'senior',
    question: 'An upload endpoint blocks files whose Content-Type header is not `image/png`. As a tester you change the header from `application/x-php` to `image/png` and the upload succeeds. What additional check is the strongest server-side defence against weaponising this?',
    choices: [
      'Reading the actual file magic bytes (server-side content sniffing) and rejecting executables',
      'Trusting the Content-Type header but logging mismatches',
      'Renaming the uploaded file to a random name only',
      'Storing the file under the web root with original extension',
    ],
    correctIndex: 0,
    explanation: 'The Content-Type header is attacker-controlled and proves nothing. The reliable defence is to inspect the file\'s actual magic bytes server-side and reject anything whose detected type does not match the allow-list, combined with not serving uploads from an executable path. OWASP\'s file upload guidance covers this layered approach.',
    distractorRationale: {
      1: 'Logging is observability, not enforcement — the malicious file still lands.',
      2: 'A random filename does not stop a webshell from executing if it is served from a path that interprets it.',
      3: 'Storing under the web root with original extension is the worst of both — it lets a uploaded .php execute.',
    },
    source: { name: 'OWASP Web Security Testing Guide — File Upload', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Unexpected_File_Types' },
  },

  {
    id: 'web-010',
    topic: 'web',
    subtopic: 'oauth',
    difficulty: 'senior',
    question: 'An OAuth 2.0 authorisation-code flow does NOT validate the `state` parameter. Which attack does this primarily enable?',
    choices: [
      'Token replay — old tokens can be reused after revocation',
      'Cross-Site Request Forgery (CSRF) on the OAuth callback, letting an attacker bind their account to a victim\'s session',
      'Open redirect to phishing pages',
      'Mass assignment of token scopes',
    ],
    correctIndex: 1,
    explanation: 'The state parameter is the OAuth client\'s CSRF token: it binds the auth code returned from the IdP to the same user-agent that started the flow. Without it, an attacker can paste their own auth code into a victim\'s callback and link the attacker\'s account to the victim\'s session. PortSwigger\'s OAuth labs cover this exact attack.',
    distractorRationale: {
      0: 'Token replay involves access tokens, not the state parameter.',
      2: 'Open redirect is a separate misconfiguration around the redirect_uri allow-list.',
      3: 'Mass assignment is a framework-level data-binding flaw, unrelated to OAuth state.',
    },
    source: { name: 'PortSwigger Web Security Academy — OAuth: missing state', url: 'https://portswigger.net/web-security/oauth' },
  },

  {
    id: 'web-011',
    topic: 'web',
    subtopic: 'xxe',
    difficulty: 'senior',
    question: 'You upload a SOAP/XML payload containing a DOCTYPE block referencing an external entity. The server returns the contents of /etc/passwd in the response. Which class of vulnerability is this?',
    choices: [
      'XML Schema Validation (XSD) bypass',
      'XML External Entity (XXE) injection',
      'XPath injection',
      'XML signature stripping',
    ],
    correctIndex: 1,
    explanation: 'XXE occurs when an XML parser processes external entity references defined in a DOCTYPE. The parser dereferences `SYSTEM` URLs (file://, http://) and substitutes the contents into the document, leading to file disclosure or SSRF. PortSwigger\'s XXE topic covers detection and exploitation in detail.',
    distractorRationale: {
      0: 'Schema validation issues prevent enforcement of structure, but they do not by themselves disclose files.',
      2: 'XPath injection manipulates XPath queries to bypass auth or extract data, not to read files via entity expansion.',
      3: 'Signature stripping is a SAML/XML-DSig attack, unrelated to entity processing.',
    },
    source: { name: 'PortSwigger Web Security Academy — XXE injection', url: 'https://portswigger.net/web-security/xxe' },
  },

  {
    id: 'web-012',
    topic: 'web',
    subtopic: 'deserialization',
    difficulty: 'senior',
    question: 'A Java app deserialises base64-encoded objects from a cookie using `ObjectInputStream.readObject()`. Which tooling is most appropriate to generate a payload that achieves RCE?',
    choices: [
      'sqlmap',
      'ysoserial — generates gadget chains for known vulnerable libraries on the classpath',
      'Burp Intruder with the default fuzzing list',
      'Hashcat',
    ],
    correctIndex: 1,
    explanation: 'ysoserial produces serialised Java payloads using gadget chains drawn from common libraries (Commons-Collections, Spring, Groovy, Hibernate). When the target deserialises one of these gadgets, it triggers code execution. PortSwigger and the OWASP deserialization cheat sheet both reference ysoserial as the canonical tool.',
    distractorRationale: {
      0: 'sqlmap targets SQL injection, not Java deserialization.',
      2: 'Generic fuzzing rarely produces a working gadget chain — you need a serialised object that triggers a specific gadget on the classpath.',
      3: 'Hashcat is a password cracker; it does not produce serialised payloads.',
    },
    source: { name: 'OWASP Deserialization Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html' },
  },

  {
    id: 'web-013',
    topic: 'web',
    subtopic: 'race-conditions',
    difficulty: 'senior',
    question: 'A "redeem coupon" endpoint accepts a one-time code. You discover that submitting the same code in many parallel requests credits the account multiple times. Which Burp feature is the standard tool for this attack?',
    choices: [
      'Burp Repeater\'s Send Group in parallel (single-packet attack via HTTP/2 or "last-byte sync")',
      'Burp Intruder pitchfork mode at default thread count',
      'Burp Comparer',
      'Burp Decoder',
    ],
    correctIndex: 0,
    explanation: 'PortSwigger\'s race-condition research and the Send Group feature in Repeater allow you to dispatch many requests to land at the server within a sub-millisecond window using the single-packet attack (HTTP/2) or last-byte synchronisation. This minimises network jitter and exposes TOCTOU windows that ordinary thread fuzzing misses.',
    distractorRationale: {
      1: 'Default Intruder threading does not synchronise the requests tightly enough; jitter typically washes out the race window.',
      2: 'Comparer is a diff tool — useful for analysis but not for sending parallel requests.',
      3: 'Decoder converts encodings; it does not send traffic.',
    },
    source: { name: 'PortSwigger Web Security Academy — Race Conditions', url: 'https://portswigger.net/web-security/race-conditions' },
  },

  {
    id: 'web-014',
    topic: 'web',
    subtopic: 'host-header',
    difficulty: 'senior',
    question: 'An app generates password-reset emails using the request\'s `Host` header to build the link. What is the senior-level attack and the recommended mitigation?',
    choices: [
      'Attacker sets `Host: evil.com`; victim clicks the reset link sent in the email and the token is exfiltrated to attacker. Mitigation: validate the Host header against an allow-list and use an absolute URL configured server-side.',
      'Attacker sets a long Host header to overflow the buffer. Mitigation: increase server header size limit.',
      'Attacker requests with no Host header. Mitigation: enforce HTTP/2 only.',
      'Attacker uses an IPv6 Host header. Mitigation: disable IPv6.',
    ],
    correctIndex: 0,
    explanation: 'Trusting the Host header for password-reset link construction is a long-standing vulnerability: the attacker submits a reset for the victim with `Host: evil.com`, and when the victim clicks the link, the token leaks to the attacker. The fix is to validate Host against a known allow-list or hard-code the public URL. PortSwigger documents this exact case.',
    distractorRationale: {
      1: 'Buffer overflows are not the issue with HTTP headers in modern stacks; the vulnerability is logical, not memory-corruption.',
      2: 'A missing Host header is malformed but not the attack.',
      3: 'IPv6 Host headers are valid; disabling IPv6 is unrelated.',
    },
    source: { name: 'PortSwigger Web Security Academy — HTTP Host header attacks', url: 'https://portswigger.net/web-security/host-header' },
  },

  {
    id: 'web-015',
    topic: 'web',
    subtopic: 'clickjacking',
    difficulty: 'senior',
    question: 'A page lacks `X-Frame-Options` and the modern `Content-Security-Policy: frame-ancestors`. Which header should you recommend, and which one is now considered the correct primary defence?',
    choices: [
      '`X-Frame-Options: DENY` only — frame-ancestors is deprecated',
      '`Content-Security-Policy: frame-ancestors \'self\'` (the spec-mandated successor); X-Frame-Options can be added for legacy browsers but CSP frame-ancestors is the modern primary defence',
      '`X-XSS-Protection: 1`',
      '`Strict-Transport-Security: max-age=31536000`',
    ],
    correctIndex: 1,
    explanation: 'The CSP-2 spec deprecates X-Frame-Options in favour of `frame-ancestors`, which is more flexible (supports multiple origins, schemes) and is honoured by all modern browsers. MDN, OWASP and the W3C spec all recommend frame-ancestors as the primary clickjacking control with X-Frame-Options as a legacy fallback.',
    distractorRationale: {
      0: 'X-Frame-Options is the legacy control; frame-ancestors is the spec-mandated successor.',
      2: 'X-XSS-Protection targeted browser XSS auditors and is itself deprecated; it has nothing to do with framing.',
      3: 'HSTS forces TLS, unrelated to clickjacking.',
    },
    source: { name: 'OWASP Clickjacking Defense Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html' },
  },

  {
    id: 'web-016',
    topic: 'web',
    subtopic: 'web-cache-poisoning',
    difficulty: 'senior',
    question: 'Which characteristic of an HTTP request is the most common foothold for web cache poisoning?',
    choices: [
      'The cookie header — it is always part of the cache key',
      'An "unkeyed input" — a request header (e.g., X-Forwarded-Host, X-Original-URL) that the back-end reflects into the response but the cache ignores when computing the cache key',
      'The query string — it is never part of the cache key',
      'The user-agent — it is always uppercase-normalised by caches',
    ],
    correctIndex: 1,
    explanation: 'Cache poisoning leverages "unkeyed inputs": headers that influence the response but are not included in the cache key. An attacker poisons the cached response by sending a malicious header value once; subsequent victims fetching from the cache get the malicious response. James Kettle / PortSwigger\'s cache poisoning research is the canonical reference.',
    distractorRationale: {
      0: 'Cookies are usually included in cache keys (or not cached at all). They are not the typical poisoning vector.',
      2: 'Query strings are usually keyed by caches.',
      3: 'User-agent normalisation is a sometimes-true detail but not the core poisoning mechanism.',
    },
    source: { name: 'PortSwigger Web Security Academy — Web cache poisoning', url: 'https://portswigger.net/web-security/web-cache-poisoning' },
  },

  {
    id: 'web-017',
    topic: 'web',
    subtopic: 'prototype-pollution',
    difficulty: 'senior',
    question: 'You merge user-supplied JSON into a config object using a vulnerable `merge()` function in Node.js. The user submits `{"__proto__": {"isAdmin": true}}`. Which class of vulnerability is this and why is it dangerous?',
    choices: [
      'JSON injection — the parser executes arbitrary code',
      'Prototype pollution — modifies `Object.prototype`, so subsequent property reads anywhere in the app see the polluted value (potential auth bypass / RCE depending on gadgets)',
      'JWT tampering',
      'NoSQL injection',
    ],
    correctIndex: 1,
    explanation: 'Prototype pollution mutates `Object.prototype`. After pollution, every newly created object inherits the polluted property unless explicitly overridden. In real apps, this can be chained into auth bypass or RCE through gadgets in popular libraries. PortSwigger and OWASP have detailed write-ups.',
    distractorRationale: {
      0: 'JSON.parse does not execute code; the JSON itself is data.',
      2: 'JWT tampering involves modifying token claims, not prototype chains.',
      3: 'NoSQL injection manipulates query operators ($gt, $ne) — different vulnerability class.',
    },
    source: { name: 'PortSwigger Web Security Academy — Prototype Pollution', url: 'https://portswigger.net/web-security/prototype-pollution' },
  },

  {
    id: 'web-018',
    topic: 'web',
    subtopic: 'open-redirect',
    difficulty: 'senior',
    question: 'A login flow redirects to `?next=/dashboard`. You change `next=//evil.com` and the browser is redirected to evil.com. In modern AppSec impact terms, why is open redirect rarely standalone-critical, and when does it become high-severity?',
    choices: [
      'It is never exploitable',
      'Open redirect alone is usually low/info; it becomes high-severity when chained with OAuth (state-less or redirect_uri matching loose) to leak auth codes, or used to bypass SSRF allow-lists',
      'It is always critical because it is on the OWASP Top 10',
      'It only matters on shared hosting',
    ],
    correctIndex: 1,
    explanation: 'Modern triagers treat plain open redirect as low-severity phishing. The senior-level point is the chain: when an OAuth provider does loose redirect_uri matching, a same-origin open redirect can be used to leak authorization codes; open redirects can also bypass SSRF or CSP allow-lists. CVSS context is what raises severity.',
    distractorRationale: {
      0: 'It is exploitable for phishing; the question is severity.',
      2: 'Open redirect is not its own item on the current OWASP Top 10 and is generally lower-severity.',
      3: 'Hosting topology is irrelevant.',
    },
    source: { name: 'OWASP — Unvalidated Redirects and Forwards Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html' },
  },

  {
    id: 'web-019',
    topic: 'web',
    subtopic: 'path-traversal',
    difficulty: 'senior',
    question: 'A download endpoint accepts `?file=report.pdf` and serves files from `/var/www/uploads/`. You try `?file=../../etc/passwd` and get blocked, but `?file=..%2f..%2fetc/passwd` works. What lesson does this teach about input validation?',
    choices: [
      'URL-encoding bypasses are obsolete in modern frameworks',
      'Sanitisation must happen AFTER URL/Unicode decoding (canonicalisation), and the cleanest defence is to resolve to an absolute path then verify the canonical path is still under the allowed directory',
      'Always use HTTPS to prevent traversal',
      'Path traversal only works on Windows',
    ],
    correctIndex: 1,
    explanation: 'Sanitisation done before canonicalisation can be bypassed by encoding (`%2f`, `%252f` for double-encoded), unicode (`..%c0%af`), or Windows-style backslashes. The robust defence is to decode and canonicalise the path first, then verify the resolved path stays within the allow-listed root. OWASP\'s testing guide is explicit on this.',
    distractorRationale: {
      0: 'Encoding bypasses are very much still relevant — they appear regularly in CVEs.',
      2: 'HTTPS protects in transit; it does nothing for path traversal.',
      3: 'Path traversal works on Linux too — /etc/passwd is the classic target.',
    },
    source: { name: 'OWASP Web Security Testing Guide — Testing for Path Traversal', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include' },
  },

  {
    id: 'web-020',
    topic: 'web',
    subtopic: 'csrf',
    difficulty: 'senior',
    question: 'An API uses `SameSite=Lax` on its session cookie and no CSRF token. Which scenario is most likely STILL exploitable as CSRF?',
    choices: [
      'A cross-site form POST to a state-changing endpoint',
      'A cross-site GET that has side effects (e.g., `/transfer?to=evil&amount=1000`) — Lax allows top-level GETs',
      'Any cross-site fetch() call',
      'A fetch() with credentials: omit',
    ],
    correctIndex: 1,
    explanation: 'SameSite=Lax blocks cross-site cookies on cross-site POSTs and most subresource requests, but it allows cookies on top-level navigations (clicking a link). If a state-changing endpoint accepts GET, an attacker-crafted link still triggers CSRF. The standard fix is: never allow GET to change state, plus add CSRF tokens / SameSite=Strict for sensitive flows.',
    distractorRationale: {
      0: 'Cross-site form POSTs are blocked by SameSite=Lax (cookie not sent), so this is the protected case.',
      2: 'fetch() with default credentials respects SameSite, so cross-site fetches do not carry the cookie.',
      3: '`credentials: omit` explicitly tells fetch not to send cookies — no CSRF possible.',
    },
    source: { name: 'OWASP CSRF Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
  },

  {
    id: 'web-021',
    topic: 'web',
    subtopic: 'subdomain-takeover',
    difficulty: 'senior',
    question: 'An organisation has `blog.example.com CNAME ghost.example.io.` but the underlying Ghost site has been deleted. What attack is now possible and what is the canonical mitigation?',
    choices: [
      'Subdomain takeover — an attacker registers the dangling third-party resource and serves arbitrary content under the trusted FQDN, enabling cookie theft (if cookies are scoped to *.example.com), phishing, and CORS bypass. Mitigation: remove dangling CNAMEs as part of decommission, and run continuous DNS hygiene scans.',
      'DNS cache poisoning — the attacker sets a TTL of 0',
      'BGP hijacking — the attacker announces the IP block',
      'TLS downgrade — the attacker forces HTTP/1.0',
    ],
    correctIndex: 0,
    explanation: 'Subdomain takeover is the dangling-DNS-pointer issue: when a CNAME points at a third-party service that has been removed, an attacker who registers the freed name on the third-party platform serves content under your subdomain. OWASP and the EdOverflow takeover guide both treat this as a recurring high-severity finding.',
    distractorRationale: {
      1: 'DNS cache poisoning targets resolvers, not third-party service decommissions.',
      2: 'BGP hijacking is at the routing layer, not DNS.',
      3: 'TLS downgrade is a transport attack; not what dangling CNAMEs cause.',
    },
    source: { name: 'OWASP Web Security Testing Guide — Test for Subdomain Takeover', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/10-Test_for_Subdomain_Takeover' },
  },

  {
    id: 'web-022',
    topic: 'web',
    subtopic: 'graphql',
    difficulty: 'senior',
    question: 'You are testing a GraphQL endpoint. Which check is the MOST distinctive senior-level finding, beyond the OWASP API Top 10 basics?',
    choices: [
      'Verifying HTTPS is enabled',
      'Sending an introspection query (`__schema`) to enumerate types/queries/mutations, then probing for missing object-level authorisation, batching/aliasing abuse, and field-suggestion oracles even when introspection is disabled',
      'Checking if cookies have HttpOnly',
      'Confirming that the response is JSON',
    ],
    correctIndex: 1,
    explanation: 'GraphQL-specific senior tests: introspection enumeration, batching and aliasing to bypass rate-limit / brute-force, field-suggestion oracles when introspection is off, and broken object-level authorisation across nested queries (BOLA in OWASP API Top 10). Generic web checks (HTTPS, HttpOnly) miss the protocol-specific risks.',
    distractorRationale: {
      0: 'HTTPS is a baseline, not a GraphQL-specific finding.',
      2: 'HttpOnly is generic web hardening.',
      3: 'JSON content type is just protocol mechanics.',
    },
    source: { name: 'OWASP GraphQL Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html' },
  },

  {
    id: 'web-023',
    topic: 'web',
    subtopic: 'nosql-injection',
    difficulty: 'senior',
    question: 'A login endpoint accepts JSON `{"user":"admin","pass":"x"}` and queries MongoDB. Which payload is a classic NoSQL auth bypass and why does it work?',
    choices: [
      '`{"user":"admin","pass":{"$ne":null}}` — the `$ne` operator turns the password check into "not null", which any stored hash satisfies, returning the admin user',
      '`{"user":"admin\'--","pass":"x"}` — SQL comment',
      '`{"user":"<script>","pass":"x"}` — XSS payload',
      '`{"user":"../admin","pass":"x"}` — path traversal',
    ],
    correctIndex: 0,
    explanation: 'When the framework deserialises JSON straight into a query, MongoDB query operators ($ne, $gt, $regex) become available. `$ne: null` matches any stored password, bypassing authentication. The fix is to coerce expected primitives (string only) before constructing the query. OWASP and PortSwigger both cover NoSQLi.',
    distractorRationale: {
      1: 'SQL comment syntax does not affect MongoDB queries.',
      2: 'XSS is a client-side concern, not a NoSQL operator injection.',
      3: 'Path traversal is for file-system access, not query operators.',
    },
    source: { name: 'PortSwigger Web Security Academy — NoSQL injection', url: 'https://portswigger.net/web-security/nosql-injection' },
  },

  {
    id: 'web-024',
    topic: 'web',
    subtopic: 'command-injection',
    difficulty: 'senior',
    question: 'A diagnostics endpoint accepts a hostname and runs `ping -c 1 <hostname>` via `os.system`. The developer added a regex to block spaces. What is the cleanest senior-level recommendation?',
    choices: [
      'Add more regex to block more characters',
      'Move from string concatenation + shell to an argv-based exec API (`subprocess.run([...], shell=False)`), and apply strict allow-list validation (e.g., RFC-compliant hostname only) before execution',
      'Add a CAPTCHA',
      'Run the command as a different user',
    ],
    correctIndex: 1,
    explanation: 'Defending against command injection by blacklisting characters is fragile — substitutions, encoding and shell features keep finding bypasses. The proper fix is to remove the shell from the path: pass arguments as a list to the OS, never concatenate user input into a shell string, and validate against an allow-list. OWASP\'s command-injection guidance is explicit.',
    distractorRationale: {
      0: 'Blacklists are forever-leaky; this is an inferior strategy.',
      2: 'CAPTCHAs slow but do not block injection.',
      3: 'Reduced privilege limits damage but does not prevent the injection.',
    },
    source: { name: 'OWASP Command Injection Defense Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html' },
  },

  {
    id: 'web-025',
    topic: 'web',
    subtopic: '2fa-bypass',
    difficulty: 'senior',
    question: 'A 2FA-protected login submits the OTP to `/api/2fa/verify` with `{"user_id":1234,"otp":"123456"}`. After submitting your own OTP, you change `user_id` to a target\'s and the response says "verified". What is this and why does it slip past most QA?',
    choices: [
      'Time-based brute force — the OTP must be re-entered',
      'A horizontal access-control / IDOR flaw on the 2FA verification endpoint: the back-end checks the OTP against the supplied user_id rather than against the user established by the session, so the attacker uses their own valid OTP to clear the 2FA gate for any account',
      'A timing side-channel — the response delay leaks OTP bits',
      'A Content-Type confusion',
    ],
    correctIndex: 1,
    explanation: 'A frequent senior-level real-world bug: the 2FA verifier trusts a request-supplied user_id instead of the session subject. The attacker generates their own OTP, then switches user_id to the target — server-side authorisation is missing. PortSwigger\'s authentication labs document multiple variants of this.',
    distractorRationale: {
      0: 'Brute force against 6-digit OTPs is a different class (rate-limit issue), not what is described.',
      2: 'Timing side-channels would not produce a clean "verified" response on a forged user_id.',
      3: 'Content-Type confusion is unrelated to authorisation logic.',
    },
    source: { name: 'PortSwigger Web Security Academy — Authentication: 2FA bypass', url: 'https://portswigger.net/web-security/authentication/multi-factor' },
  },

  {
    id: 'web-026',
    topic: 'web',
    subtopic: 'session-fixation',
    difficulty: 'senior',
    question: 'After a user authenticates, the application reuses the pre-authentication session ID rather than issuing a new one. What attack does this enable?',
    choices: [
      'Session fixation — attacker sets the victim\'s session ID before login (via URL parameter, cookie injection, or related-domain cookie); after the victim logs in, the attacker reuses that same ID and is now authenticated as the victim',
      'CSRF',
      'Clickjacking',
      'XXE',
    ],
    correctIndex: 0,
    explanation: 'Session fixation succeeds when the application keeps a pre-auth session valid through login. The mitigation is to invalidate the existing session and issue a fresh one upon successful authentication — every framework supports this (`session.regenerate` / equivalent). OWASP\'s session management cheat sheet is explicit.',
    distractorRationale: {
      1: 'CSRF tricks the browser into making requests; it is not about session ID reuse.',
      2: 'Clickjacking is a UI redress attack.',
      3: 'XXE involves XML parser entity processing — different class.',
    },
    source: { name: 'OWASP Session Management Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html' },
  },

  {
    id: 'web-027',
    topic: 'web',
    subtopic: 'mass-assignment',
    difficulty: 'senior',
    question: 'A registration endpoint accepts JSON and the framework auto-binds it to the User model. You include `"isAdmin": true` and the new account has admin privileges. What is this called and how is it fixed?',
    choices: [
      'Mass assignment / over-posting; fix with explicit DTOs / strong-parameter allow-lists, never bind framework models directly to request bodies',
      'JWT injection; fix by rotating signing keys',
      'CSRF; fix by adding a token',
      'XSS; fix by output encoding',
    ],
    correctIndex: 0,
    explanation: 'Mass assignment (Rails) / over-posting (.NET) / parameter binding (Spring) is when the framework binds every request field to the model — including fields the user should not control. The fix is explicit DTOs with allow-lists of writable fields. OWASP API Security Top 10 lists this as API6:2023.',
    distractorRationale: {
      1: 'Token signing is unrelated to model binding.',
      2: 'CSRF tokens authenticate request origin, not field allow-listing.',
      3: 'Output encoding is for XSS, not server-side data binding.',
    },
    source: { name: 'OWASP API Security Top 10 — API6:2023 Unrestricted Resource Consumption / Mass Assignment guidance', url: 'https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/' },
  },

  {
    id: 'web-028',
    topic: 'web',
    subtopic: 'saml',
    difficulty: 'senior',
    question: 'In a SAML signature wrapping (XSW) attack, what is the underlying bug that the attack exploits?',
    choices: [
      'The IdP signs an assertion, but the verifier evaluates a different (unsigned) assertion node injected elsewhere in the document because the signature reference and the validation read different XPath positions',
      'The IdP shares its private key with the SP',
      'The SAML response is sent over HTTP',
      'The SP uses a self-signed certificate',
    ],
    correctIndex: 0,
    explanation: 'SAML XSW exploits a mismatch between which element is signed and which element is consumed. The attacker wraps the signed assertion inside an envelope so the signature still verifies against the original, while the application reads a different attacker-controlled assertion. The fix is to enforce that signature verification and consumption operate on the same element. CISA, NIST, and the OASIS SAML profiles describe the canonical defences.',
    distractorRationale: {
      1: 'IdPs never share private keys; this is a strawman.',
      2: 'Transport security is independent of XSW; the attack works over HTTPS too.',
      3: 'Certificate self-signing is a trust-chain issue, not the XSW vulnerability.',
    },
    source: { name: 'OWASP — SAML Security Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html' },
  },

  {
    id: 'web-029',
    topic: 'web',
    subtopic: 'business-logic',
    difficulty: 'senior',
    question: 'An e-commerce checkout discounts items by 10% per coupon and allows multiple coupons. You add the same coupon code 12 times and the price goes negative, crediting your account. What category is this?',
    choices: [
      'SQL injection',
      'Business-logic vulnerability (insufficient validation of cumulative state) — not detectable by automated scanners; requires understanding the business rules to spot',
      'XSS',
      'XXE',
    ],
    correctIndex: 1,
    explanation: 'Business-logic flaws live in the gap between the developer\'s assumptions and what is actually enforced. They rarely show up in automated scans; you find them by modelling the workflow and abusing edge cases (negative quantities, currency wrap-around, duplicate coupons). OWASP\'s business-logic testing guidance is the senior-level reference.',
    distractorRationale: {
      0: 'No SQL is being injected.',
      2: 'XSS is client-side script execution.',
      3: 'XXE is XML entity processing.',
    },
    source: { name: 'PortSwigger Web Security Academy — Business logic vulnerabilities', url: 'https://portswigger.net/web-security/logic-flaws' },
  },

  {
    id: 'web-030',
    topic: 'web',
    subtopic: 'asvs',
    difficulty: 'senior',
    question: 'A senior pentester is asked which framework to use to define a comprehensive web-app security baseline (verifiable controls, not just findings). Which OWASP project is the canonical answer?',
    choices: [
      'OWASP Top 10 — it is a verification standard',
      'OWASP Application Security Verification Standard (ASVS) — defines testable security requirements at L1/L2/L3 maturity levels',
      'OWASP ZAP',
      'OWASP Juice Shop',
    ],
    correctIndex: 1,
    explanation: 'OWASP ASVS provides verifiable security requirements (V1 architecture through V14 configuration). The Top 10 is an awareness/risk list, not a verification standard. ZAP and Juice Shop are tools/labs. Knowing this distinction separates senior-level practitioners.',
    distractorRationale: {
      0: 'OWASP Top 10 is awareness, not a verification standard.',
      2: 'ZAP is a scanner.',
      3: 'Juice Shop is an intentionally vulnerable training app.',
    },
    source: { name: 'OWASP Application Security Verification Standard', url: 'https://owasp.org/www-project-application-security-verification-standard/' },
  },
];
